# Generated by Django 5.2.7 on 2025-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_user_home_unit_alter_user_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shifts_per_week_override',
            field=models.IntegerField(blank=True, help_text='Override default shifts per week for this staff member', null=True),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(choices=[('DAY_SENIOR', 'Day Shift (SSCW/SCW)'), ('DAY_ASSISTANT', 'Day Shift (SCA)'), ('NIGHT_SENIOR', 'Night Shift (SSCW/SCW)'), ('NIGHT_ASSISTANT', 'Night Shift (SCA)'), ('ADMIN', 'Supernumerary Admin Day')], max_length=50, unique=True),
        ),
    ]
