# Generated by Django 5.2.7 on 2025-12-19 14:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('STAFF', 'Care Staff Member'), ('SENIOR', 'Senior Carer'), ('MANAGER', 'Unit Manager'), ('HOS', 'Head of Service'), ('ADMIN', 'Administrative Staff'), ('OTHER', 'Other')], max_length=20)),
                ('care_home', models.CharField(blank=True, help_text='Which care home do you work at?', max_length=100)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_duration_minutes', models.IntegerField(blank=True, help_text='How long did you use the demo?', null=True)),
                ('overall_rating', models.IntegerField(help_text='Overall experience (1=Poor, 5=Excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ease_of_use', models.IntegerField(help_text='How easy was the system to use? (1=Very Difficult, 5=Very Easy)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_recommend', models.BooleanField(default=True, help_text='Would you recommend this system to colleagues?')),
                ('rota_viewing_rating', models.IntegerField(blank=True, help_text='Viewing shift rotas (1=Poor, 5=Excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('shift_swapping_rating', models.IntegerField(blank=True, help_text='Shift swap requests (1=Poor, 5=Excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('leave_request_rating', models.IntegerField(blank=True, help_text='Leave request process (1=Poor, 5=Excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ai_assistant_rating', models.IntegerField(blank=True, help_text='AI Assistant chatbot (1=Poor, 5=Excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dashboard_rating', models.IntegerField(blank=True, help_text='Dashboard overview (1=Poor, 5=Excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mobile_experience_rating', models.IntegerField(blank=True, help_text='Mobile/tablet experience (1=Poor, 5=Excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('most_useful_features', models.TextField(blank=True, help_text='Which features did you find most useful and why?')),
                ('least_useful_features', models.TextField(blank=True, help_text='Which features did you find least useful and why?')),
                ('missing_features', models.TextField(blank=True, help_text='What features are missing that you need?')),
                ('navigation_issues', models.TextField(blank=True, help_text='Any difficulties navigating the system?')),
                ('confusing_areas', models.TextField(blank=True, help_text='What was confusing or unclear?')),
                ('design_feedback', models.TextField(blank=True, help_text='Feedback on layout, colors, typography?')),
                ('currently_use_system', models.CharField(blank=True, help_text='What system do you currently use (if any)?', max_length=200)),
                ('better_than_current', models.CharField(blank=True, choices=[('MUCH_BETTER', 'Much Better'), ('BETTER', 'Somewhat Better'), ('SAME', 'About the Same'), ('WORSE', 'Somewhat Worse'), ('MUCH_WORSE', 'Much Worse'), ('NO_CURRENT', 'No Current System')], max_length=20)),
                ('what_makes_it_better', models.TextField(blank=True, help_text='What makes this system better/worse than your current system?')),
                ('ready_to_use_daily', models.BooleanField(default=False, help_text='Is this system ready for daily use?')),
                ('concerns_before_rollout', models.TextField(blank=True, help_text='Any concerns before full rollout?')),
                ('training_needs', models.TextField(blank=True, help_text='What training would you need?')),
                ('bugs_encountered', models.TextField(blank=True, help_text='Describe any bugs or errors you encountered')),
                ('additional_comments', models.TextField(blank=True, help_text='Any other feedback, suggestions, or comments?')),
                ('willing_to_followup', models.BooleanField(default=False, help_text='Can we contact you for follow-up questions?')),
                ('contact_email', models.EmailField(blank=True, help_text='Email for follow-up (optional)', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Feedback',
                'verbose_name_plural': 'Demo Feedback Responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('ROTA', 'Rota Management'), ('LEAVE', 'Leave Management'), ('STAFF', 'Staff Management'), ('REPORTING', 'Reports & Analytics'), ('MOBILE', 'Mobile Experience'), ('INTEGRATION', 'System Integration'), ('PERFORMANCE', 'Performance/Speed'), ('UI_UX', 'User Interface'), ('OTHER', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Nice to Have'), ('MEDIUM', 'Important'), ('HIGH', 'Critical'), ('URGENT', 'Blocking Issue')], default='MEDIUM', max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Under Review'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Development'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Not Planned')], default='NEW', max_length=20)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feature_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Request',
                'verbose_name_plural': 'Feature Requests',
                'ordering': ['-priority', '-votes', '-requested_at'],
            },
        ),
    ]
