# Generated by Django 4.2.27 on 2026-01-24 01:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0059_alter_user_shift_preference'),
        ('incident_safety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='e.g., SAP-2026-001 (Safety Action Plan)', max_length=50, unique=True)),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Corrective Action - Fix existing problem'), ('PREVENTIVE', 'Preventive Action - Prevent future problems'), ('IMPROVEMENT', 'Improvement Action - Enhance process')], max_length=20)),
                ('priority', models.CharField(choices=[('IMMEDIATE', 'Immediate (24 hours)'), ('HIGH', 'High (1 week)'), ('MEDIUM', 'Medium (1 month)'), ('LOW', 'Low (3 months)')], max_length=20)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed - Awaiting Verification'), ('VERIFIED', 'Verified Effective'), ('NOT_EFFECTIVE', 'Not Effective - Needs Revision'), ('CLOSED', 'Closed')], default='IDENTIFIED', max_length=20)),
                ('problem_statement', models.TextField(help_text='What problem is this action addressing?')),
                ('action_description', models.TextField(help_text='Detailed description of the action to be taken')),
                ('expected_outcome', models.TextField(help_text='What success looks like')),
                ('identified_date', models.DateField(default=django.utils.timezone.now)),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('implementation_plan', models.TextField(blank=True, help_text='Step-by-step plan for implementing this action')),
                ('resources_required', models.TextField(blank=True, help_text='Budget, staff time, equipment needed')),
                ('barriers_identified', models.TextField(blank=True, help_text='Potential obstacles to implementation')),
                ('percent_complete', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_notes', models.TextField(blank=True, help_text='Regular updates on progress')),
                ('verification_method', models.TextField(blank=True, help_text='How will we verify this action is effective?')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_outcome', models.TextField(blank=True, help_text='Was the action effective? Evidence?')),
                ('effectiveness_review_due', models.DateField(blank=True, null=True)),
                ('effectiveness_review_completed', models.BooleanField(default=False)),
                ('effectiveness_review_notes', models.TextField(blank=True, help_text='Long-term effectiveness assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_action_plans_owned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_action_plans_created', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_action_plans', to='scheduling.incidentreport')),
                ('root_cause_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_action_plans', to='incident_safety.rootcauseanalysis')),
                ('supporting_staff', models.ManyToManyField(blank=True, related_name='safety_action_plans_supporting', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_action_plans_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Action Plan',
                'verbose_name_plural': 'Safety Action Plans',
                'ordering': ['priority', 'target_completion_date'],
            },
        ),
        migrations.DeleteModel(
            name='CorrectivePreventiveAction',
        ),
    ]
