# Generated by Django 4.2.27 on 2026-01-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_safety', '0002_rename_capa_to_safety_action_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyactionplan',
            name='reference_number',
            field=models.CharField(help_text='e.g., HSAP-2026-001 (Health and Safety Action Plan)', max_length=50, unique=True),
        ),
    ]
