"""
Django settings for rotasystems project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
try:
    from celery.schedules import crontab
except ImportError:
    crontab = None
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment variable for security
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Load allowed hosts from environment (comma-separated list)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_celery_beat',  # Celery Beat for periodic tasks
    # 'django_q',  # Django-Q disabled due to Python 3.14 compatibility - using cron instead
    'scheduling',
    'scheduling.management',
    'staff_records',
    'rotasystems.core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'scheduling.middleware.AuditLoggingMiddleware',  # Automatic audit logging
]

ROOT_URLCONF = 'rotasystems.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rotasystems.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Load database configuration from environment
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.sqlite3':
    # SQLite configuration (development)
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
        }
    }
else:
    # PostgreSQL or other database (production)
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = config('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))

MEDIA_URL = '/media/'
MEDIA_ROOT = config('MEDIA_ROOT', default=str(BASE_DIR / 'media'))

# Organize uploads by type
TRAINING_CERTIFICATES_DIR = 'training/certificates/'
INCIDENT_PHOTOS_DIR = 'incidents/photos/'
BODY_MAPS_DIR = 'incidents/body_maps/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'scheduling.User'

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'scheduling.backends.SAPAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# CORS Settings (for frontend development)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",
]

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Time Zone
TIME_ZONE = 'Europe/London'

# Django-Q Configuration
Q_CLUSTER = {
    'name': 'rotasystem',
    'workers': 4,
    'recycle': 500,
    'timeout': 300,
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'redis': {
        'host': '127.0.0.1',
        'port': 6379,
        'db': 0,
        'password': None,
        'socket_timeout': None,
        'charset': 'utf-8',
        'errors': 'strict',
        'unix_socket_path': None,
    }
}

# ===== Email Configuration =====
# Uses environment variables for secure credential storage
# To switch between console (testing) and SMTP (production):
#   - Console: Unset EMAIL_HOST environment variable
#   - Production: Set EMAIL_HOST, EMAIL_USER, EMAIL_PASSWORD environment variables

# Determine backend based on environment variables
if os.environ.get('EMAIL_HOST'):
    # Production SMTP - configured via environment variables
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST')  # e.g., smtp.gmail.com or smtp.office365.com
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
    EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'Staff Rota System <{EMAIL_HOST_USER}>')
    SERVER_EMAIL = DEFAULT_FROM_EMAIL
else:
    # Development/Testing - Console backend (emails print to terminal)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'Staff Rota System <webmaster@localhost>'
    SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email timeout settings
EMAIL_TIMEOUT = 30  # seconds

# ===== Email Configuration Guide =====
# 
# GMAIL SETUP:
# 1. Go to https://myaccount.google.com/apppasswords
# 2. Generate an "App Password" (16-character password)
# 3. Set environment variables:
#    export EMAIL_HOST="smtp.gmail.com"
#    export EMAIL_PORT="587"
#    export EMAIL_USER="your-email@gmail.com"
#    export EMAIL_PASSWORD="abcd efgh ijkl mnop"  # App password
#    export DEFAULT_FROM_EMAIL="Staff Rota System <your-email@gmail.com>"
#
# OFFICE 365 SETUP:
# 1. Use your Office 365 credentials
# 2. Set environment variables:
#    export EMAIL_HOST="smtp.office365.com"
#    export EMAIL_PORT="587"
#    export EMAIL_USER="your-email@company.com"
#    export EMAIL_PASSWORD="your-password"
#    export DEFAULT_FROM_EMAIL="Staff Rota System <your-email@company.com>"
#
# Add to ~/.zshrc or ~/.bash_profile to persist across sessions
# EMAIL_USE_TLS = True  # or EMAIL_USE_SSL = True for port 465
# EMAIL_HOST_USER = 'your-email@yourserver.com'
# EMAIL_HOST_PASSWORD = 'your-password'
# DEFAULT_FROM_EMAIL = 'Staff Rota System <your-email@yourserver.com>'

# ===== Compliance Notification Recipients =====
# Replace with actual email addresses of people who should receive alerts
COMPLIANCE_NOTIFICATION_EMAILS = [
    'manager@example.com',  # Replace with actual manager email
    # 'compliance@example.com',  # Add more recipients as needed
    # 'seniormanager@example.com',
]

# ===== Site URL =====
# Used in email links - update when deploying to production
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# ===== Security Settings =====
# Production security settings - configured via environment variables

# HTTPS/SSL Settings (only enable in production with valid SSL certificate)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Database Connection Pooling (production)
CONN_MAX_AGE = config('CONN_MAX_AGE', default=0, cast=int)

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# ===== Logging Configuration =====
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': BASE_DIR / 'logs' / 'django_errors.log',
                'formatter': 'verbose',
            },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

# ===== Automated Staffing Workflow Configuration =====
STAFFING_WORKFLOW = {
    # Timeouts and deadlines
    'OT_RESPONSE_WINDOW_HOURS': 1,  # Staff have 1 hour to respond to OT offers
    'AGENCY_APPROVAL_TIMEOUT_MINUTES': 15,  # Senior Officer has 15 minutes to approve agency
    
    # Long-term absence detection
    'LONG_TERM_SHIFT_THRESHOLD': 3,  # ≥3 shifts triggers long-term planning
    'LONG_TERM_DAY_THRESHOLD': 5,    # OR ≥5 days triggers long-term planning
    
    # OT priority weights (must sum to 100)
    'OT_PRIORITY_WEIGHTS': {
        'FAIR_ROTATION': 50,      # 50% weight for fair distribution
        'QUALIFICATION': 30,      # 30% weight for qualifications/experience
        'PROXIMITY': 20,          # 20% weight for travel distance/time
    },
    
    # WTD (Working Time Directive) compliance
    'WTD_MAX_HOURS_PER_WEEK': 48,     # Maximum 48 hours per week
    'WTD_MIN_REST_HOURS': 11,          # Minimum 11 hours rest between shifts
    'WTD_ROLLING_WEEKS': 17,           # Calculate average over 17 weeks
    
    # Reallocation search parameters
    'REALLOCATION_MAX_TRAVEL_MINUTES': 30,  # Maximum 30-minute travel time
    'REALLOCATION_PRIORITY_ORDER': [
        'same_qualification',
        'higher_qualification',
        'willing_to_travel',
    ],
    
    # Escalation configuration
    'ESCALATION_SENIOR_OFFICER_EMAIL': 'senior.officer@orchard-grove.co.uk',
    'ESCALATION_SENIOR_OFFICER_PHONE': '+447700900123',  # Update with real number
    'AUTO_APPROVE_ON_TIMEOUT': True,  # Auto-approve agency after 15-min timeout
    
    # Notification preferences
    'ENABLE_SMS_NOTIFICATIONS': True,
    'ENABLE_EMAIL_NOTIFICATIONS': True,
    'ENABLE_PUSH_NOTIFICATIONS': False,  # Not yet implemented
    
    # Cost tracking
    'AGENCY_HOURLY_RATE_MULTIPLIER': 1.8,  # Agency costs 1.8x regular rate
    'OT_HOURLY_RATE_MULTIPLIER': 1.5,       # OT costs 1.5x regular rate
    
    # Budget limits (monthly, per care home)
    'MONTHLY_AGENCY_BUDGET': 9000,    # £9,000 per month per home
    'MONTHLY_OT_BUDGET': 5000,        # £5,000 per month per home
    
    # Process optimization
    'CONCURRENT_REALLOCATION_AND_OT': True,  # Run Priority 1 & 2 simultaneously
    'MAX_OT_OFFERS_PER_BATCH': 20,           # Maximum staff to offer OT per batch
    'REALLOCATION_SEARCH_RADIUS_KM': 15,     # Search within 15km for reallocation
}

# Senior Officer contact details
SENIOR_OFFICER_EMAIL = STAFFING_WORKFLOW['ESCALATION_SENIOR_OFFICER_EMAIL']
SENIOR_OFFICER_PHONE = STAFFING_WORKFLOW['ESCALATION_SENIOR_OFFICER_PHONE']

# HR department contact
HR_EMAIL = 'hr@orchard-grove.co.uk'

# Base URL for notification links (update for production)
BASE_URL = config('BASE_URL', default='http://localhost:8000')


# ==================== Celery Configuration ====================
# Automated workflow monitoring tasks

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Change for production
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ==================== Celery Configuration ====================
# Automated workflow monitoring tasks
# NOTE: Install celery and redis to enable these features:
# pip install celery redis django-celery-beat

try:
    from celery.schedules import crontab
    CELERY_AVAILABLE = True
except ImportError:
    CELERY_AVAILABLE = False

if CELERY_AVAILABLE:
    CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Change for production
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'Europe/London'
    
    # Celery Beat schedule for periodic tasks
    CELERY_BEAT_SCHEDULE = {
        'monitor-ot-deadlines': {
            'task': 'scheduling.tasks.monitor_ot_offer_deadlines',
            'schedule': 60.0,  # Every 1 minute
            'options': {'expires': 50}
        },
        'monitor-agency-approvals': {
            'task': 'scheduling.tasks.monitor_agency_approval_deadlines',
            'schedule': 60.0,  # Every 1 minute
            'options': {'expires': 50}
        },
        'monitor-reallocation-deadlines': {
            'task': 'scheduling.tasks.monitor_reallocation_deadlines',
            'schedule': 60.0,  # Every 1 minute
            'options': {'expires': 50}
        },
        'workflow-health-check': {
            'task': 'scheduling.tasks.monitor_workflow_health',
            'schedule': 300.0,  # Every 5 minutes
            'options': {'expires': 250}
        },
        'post-shift-admin-reminders': {
            'task': 'scheduling.tasks.send_post_shift_admin_reminders',
            'schedule': crontab(hour=9, minute=0),  # Daily at 09:00
        },
        'long-term-absence-review': {
            'task': 'scheduling.tasks.review_long_term_absences',
            'schedule': crontab(hour=8, minute=0),  # Daily at 08:00
        },
        'wdt-compliance-monitoring': {
            'task': 'scheduling.tasks.monitor_wdt_compliance',
            'schedule': crontab(day_of_week=0, hour=20, minute=0),  # Sundays at 20:00
        },
        'weekly-workflow-report': {
            'task': 'scheduling.tasks.generate_weekly_workflow_report',
            'schedule': crontab(day_of_week=1, hour=9, minute=0),  # Mondays at 09:00
        },
    }
