# Generated by Django 4.2.27 on 2026-01-14 18:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0058_alter_user_sms_notifications_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_code', models.CharField(help_text='Unique document identifier (e.g., POL-001)', max_length=50, unique=True)),
                ('document_type', models.CharField(choices=[('POLICY', 'Policy'), ('PROCEDURE', 'Procedure'), ('GUIDANCE', 'Guidance Document'), ('FORM', 'Form/Template'), ('PROTOCOL', 'Clinical Protocol'), ('STANDARD', 'Standard Operating Procedure'), ('CHARTER', 'Charter/Strategy'), ('MANUAL', 'Manual/Handbook'), ('OTHER', 'Other')], max_length=20)),
                ('version_number', models.CharField(default='1.0', help_text='Version number (e.g., 1.0, 2.1)', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('summary', models.TextField(help_text='Brief summary/purpose of document')),
                ('content', models.TextField(blank=True, help_text='Main document content (supports Markdown)')),
                ('file_upload', models.FileField(blank=True, help_text='PDF/DOCX file upload', null=True, upload_to='documents/%Y/%m/')),
                ('compliance_frameworks', models.JSONField(blank=True, default=list, help_text='List of compliance frameworks this document addresses')),
                ('regulatory_references', models.TextField(blank=True, help_text='Specific regulatory requirements/standards addressed')),
                ('review_frequency_months', models.IntegerField(default=12, help_text='How often document should be reviewed (months)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('last_reviewed_date', models.DateField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, help_text='When this version becomes effective', null=True)),
                ('requires_acknowledgement', models.BooleanField(default=False, help_text='Staff must acknowledge reading this document')),
                ('acknowledgement_due_days', models.IntegerField(default=14, help_text='Days staff have to acknowledge after publication', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=500)),
                ('attachments_count', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Person who approved this version', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_documents', to=settings.AUTH_USER_MODEL)),
                ('care_home', models.ForeignKey(blank=True, help_text='Leave blank for organization-wide documents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scheduling.carehome')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyImpactAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equality_impact_level', models.CharField(choices=[('POSITIVE', 'Positive Impact'), ('NEUTRAL', 'Neutral/No Impact'), ('NEGATIVE', 'Negative Impact (requires mitigation)'), ('UNKNOWN', 'Unknown/Requires Further Analysis')], max_length=20)),
                ('equality_analysis', models.TextField(help_text='Analysis of impact on protected characteristics (age, disability, race, etc.)')),
                ('mitigation_actions', models.TextField(blank=True, help_text='Actions to mitigate negative equality impacts')),
                ('quality_impact_level', models.CharField(choices=[('POSITIVE', 'Positive Impact'), ('NEUTRAL', 'Neutral/No Impact'), ('NEGATIVE', 'Negative Impact (requires mitigation)'), ('UNKNOWN', 'Unknown/Requires Further Analysis')], max_length=20)),
                ('quality_analysis', models.TextField(help_text='Analysis of impact on care quality and resident outcomes')),
                ('quality_measures', models.TextField(blank=True, help_text='How quality impact will be measured/monitored')),
                ('implementation_risks', models.TextField(blank=True, help_text='Risks identified during implementation')),
                ('resource_requirements', models.TextField(blank=True, help_text='Resources needed for successful implementation')),
                ('consultation_completed', models.BooleanField(default=False)),
                ('consultation_summary', models.TextField(blank=True, help_text='Summary of stakeholder feedback')),
                ('assessed_date', models.DateField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_impact_assessments', to=settings.AUTH_USER_MODEL)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_assessments', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(limit_choices_to={'document_type__in': ['POLICY', 'PROCEDURE']}, on_delete=django.db.models.deletion.CASCADE, related_name='impact_assessment', to='document_management.document')),
            ],
            options={
                'verbose_name': 'Policy Impact Assessment',
            },
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('SCHEDULED', 'Scheduled Review'), ('AD_HOC', 'Ad-Hoc Review'), ('POST_INCIDENT', 'Post-Incident Review'), ('REGULATORY', 'Regulatory Requirement')], max_length=20)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('NO_CHANGE', 'No Changes Required'), ('MINOR_UPDATE', 'Minor Updates Required'), ('MAJOR_REVISION', 'Major Revision Required'), ('RETIRE', 'Recommend Retirement')], max_length=20)),
                ('findings', models.TextField(blank=True, help_text='Review findings and recommendations')),
                ('action_items', models.TextField(blank=True, help_text='Required actions from review')),
                ('compliance_verified', models.BooleanField(default=False, help_text='Regulatory compliance verified')),
                ('compliance_notes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_reviewers', models.ManyToManyField(blank=True, help_text='Additional stakeholders for review', related_name='additional_document_reviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='document_management.document')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_categories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='document_management.documentcategory')),
            ],
            options={
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='document_attachments/%Y/%m/')),
                ('file_type', models.CharField(blank=True, help_text='e.g., PDF, DOCX, XLSX', max_length=50)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='document_management.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document_management.documentcategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(help_text='Document owner responsible for maintenance', on_delete=django.db.models.deletion.PROTECT, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='Previous version this document replaces', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_documents', to='document_management.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StaffAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_by', models.DateField(help_text='Date by which acknowledgement is required')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_method', models.CharField(blank=True, choices=[('ONLINE', 'Online Portal'), ('PAPER', 'Paper Signature'), ('EMAIL', 'Email Confirmation'), ('MEETING', 'Team Meeting')], max_length=20)),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, help_text='Quiz score percentage if comprehension test required', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, help_text='Any comments or questions from staff member')),
                ('reminder_sent_count', models.IntegerField(default=0, editable=False)),
                ('last_reminder_sent', models.DateTimeField(blank=True, editable=False, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_acknowledgements', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement_requirements', to='document_management.document')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-required_by'],
                'indexes': [models.Index(fields=['required_by'], name='document_ma_require_4a4959_idx'), models.Index(fields=['acknowledged_at'], name='document_ma_acknowl_f0c1ab_idx')],
                'unique_together': {('document', 'staff_member')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='document_versions/%Y/%m/')),
                ('summary', models.TextField(blank=True)),
                ('change_summary', models.TextField(help_text='Summary of changes in this version')),
                ('change_type', models.CharField(choices=[('MAJOR', 'Major Revision'), ('MINOR', 'Minor Update'), ('CORRECTION', 'Correction/Fix'), ('REVIEW', 'Scheduled Review')], default='MINOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='document_management.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_code'], name='document_ma_documen_38b379_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='document_ma_status_10a794_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['next_review_date'], name='document_ma_next_re_2f413b_idx'),
        ),
    ]
