# Generated by Django 5.2.7 on 2025-10-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_user_shift_preference_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='applicable_roles',
            field=models.CharField(default='SSCW,SCW,SCA', help_text='Comma-separated role names', max_length=100),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(choices=[('DAY_SENIOR', 'Day Shift (SSCW/SCW)'), ('DAY_ASSISTANT', 'Day Shift (SCA)'), ('NIGHT_SENIOR', 'Night Shift (SSCW/SCW)'), ('NIGHT_ASSISTANT', 'Night Shift (SCA)')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shift_preference',
            field=models.CharField(blank=True, choices=[('DAY_SENIOR', 'Day Shift (SSCW/SCW)'), ('DAY_ASSISTANT', 'Day Shift (SCA)'), ('NIGHT_SENIOR', 'Night Shift (SSCW/SCW)'), ('NIGHT_ASSISTANT', 'Night Shift (SCA)')], max_length=15, null=True),
        ),
    ]
