# Generated by Django 5.2.7 on 2025-12-03 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingAlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('SMS', 'SMS Message'), ('EMAIL', 'Email Message'), ('PUSH', 'Push Notification')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='For emails', max_length=200)),
                ('message_template', models.TextField(help_text='Use {variables} like {unit}, {date}, {shift_type}, {shortage}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('SHORTAGE', 'Staff Shortage'), ('ABSENCE', 'Last Minute Absence'), ('EMERGENCY', 'Emergency Cover')], default='SHORTAGE', max_length=20)),
                ('shift_date', models.DateField()),
                ('required_staff', models.IntegerField(help_text='Minimum staff required')),
                ('current_staff', models.IntegerField(help_text='Currently scheduled staff')),
                ('shortage', models.IntegerField(help_text='Number of additional staff needed')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Responses'), ('PARTIALLY_FILLED', 'Partially Filled'), ('FILLED', 'Fully Filled'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Alert expires after this time')),
                ('total_responses', models.IntegerField(default=0)),
                ('accepted_responses', models.IntegerField(default=0)),
                ('declined_responses', models.IntegerField(default=0)),
                ('sms_sent', models.IntegerField(default=0, help_text='Number of SMS sent')),
                ('email_sent', models.IntegerField(default=0, help_text='Number of emails sent')),
                ('message', models.TextField(blank=True, help_text='Custom message to staff')),
                ('priority', models.IntegerField(default=5, help_text='1-10, higher is more urgent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.shifttype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_alerts', to='scheduling.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffingAlertResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted Shift'), ('DECLINED', 'Declined Shift'), ('EXPIRED', 'No Response (Expired)'), ('WITHDRAWN', 'Acceptance Withdrawn')], default='PENDING', max_length=20)),
                ('response_method', models.CharField(blank=True, choices=[('EMAIL_LINK', 'Email Link Click'), ('SMS_LINK', 'SMS Link Click'), ('WEB_LOGIN', 'Web Login'), ('PHONE', 'Phone Call'), ('MANUAL', 'Manually Added')], max_length=20, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='scheduling.staffingalert')),
                ('shift_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_response', to='scheduling.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staffingalert',
            index=models.Index(fields=['shift_date', 'status'], name='scheduling__shift_d_0db80f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingalert',
            index=models.Index(fields=['status', 'created_at'], name='scheduling__status_48af64_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingalertresponse',
            index=models.Index(fields=['response_token'], name='scheduling__respons_45f68f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingalertresponse',
            index=models.Index(fields=['status', 'created_at'], name='scheduling__status_9225f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffingalertresponse',
            unique_together={('alert', 'user')},
        ),
    ]
