# Generated by Django 5.2.7 on 2025-12-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_add_care_home_to_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_senior_management_team',
            field=models.BooleanField(default=False, help_text='SMT member with governance oversight across all homes'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(choices=[('OG_PEAR', 'Pear'), ('OG_GRAPE', 'Grape'), ('OG_ORANGE', 'Orange'), ('OG_CHERRY', 'Cherry'), ('OG_BRAMLEY', 'Bramley'), ('OG_PLUM', 'Plum'), ('OG_PEACH', 'Peach'), ('OG_STRAWBERRY', 'Strawberry'), ('OG_MGMT', 'Mgmt'), ('MB_DAISY', 'Daisy'), ('MB_ASTER', 'Aster'), ('MB_POPPY_SRD', 'Poppy (SRD)'), ('MB_BLUEBELL', 'Bluebell'), ('MB_MARIGOLD', 'Marigold'), ('MB_FOXGLOVE', 'Foxglove'), ('MB_CORNFLOWER', 'Cornflower'), ('MB_HONEYSUCKLE', 'Honeysuckle'), ('MB_PRIMROSE', 'Primrose'), ('HH_THISTLE_SRD', 'Thistle (SRD)'), ('HH_VIOLET', 'Violet'), ('HH_IRIS', 'Iris'), ('HH_HEATHER', 'Heather'), ('HH_SNOWDROP_SRD', 'Snowdrop (SRD)'), ('HH_BLUEBELL', 'Bluebell'), ('HH_DAISY', 'Daisy'), ('HH_PRIMROSE', 'Primrose'), ('HH_ROWAN', 'Rowan'), ('RS_DAFFODIL', 'Daffodil'), ('RS_MAPLE', 'Maple'), ('RS_ROSE', 'Rose'), ('RS_LILY', 'Lily'), ('RS_LOTUS', 'Lotus'), ('RS_ORCHID', 'Orchid'), ('RS_JASMINE', 'Jasmine'), ('RS_POPLAR', 'Poplar'), ('VG_AZALEA', 'Azalea'), ('VG_CROCUS', 'Crocus'), ('VG_LILY', 'Lily'), ('VG_ROSE', 'Rose'), ('VG_TULIP', 'Tulip'), ('VG_MGMT', 'Mgmt')], max_length=50, unique=True),
        ),
    ]
