# Generated by Django 4.2.27 on 2025-12-21 21:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0024_staffingforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProphetModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True, help_text='Date the forecast was made for')),
                ('actual_value', models.FloatField(help_text='Actual number of shifts on forecast_date')),
                ('forecast_value', models.FloatField(help_text='Predicted number of shifts')),
                ('mape', models.FloatField(help_text='Mean Absolute Percentage Error for this forecast', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('drift_score', models.FloatField(blank=True, help_text='KS test p-value indicating distribution drift (lower = more drift)', null=True)),
                ('model_version', models.CharField(help_text="Prophet model version identifier (e.g., 'v1.2024-12-15')", max_length=50)),
                ('model_version_date', models.DateField(help_text='Date the model was trained')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prophet_metrics', to='scheduling.carehome')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prophet_metrics', to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Prophet Model Metric',
                'verbose_name_plural': 'Prophet Model Metrics',
                'db_table': 'scheduling_prophet_model_metrics',
                'ordering': ['-forecast_date', '-created_at'],
                'indexes': [models.Index(fields=['care_home', 'unit', 'forecast_date'], name='scheduling__care_ho_0a1b61_idx'), models.Index(fields=['model_version_date'], name='scheduling__model_v_5cf69b_idx'), models.Index(fields=['mape'], name='scheduling__mape_ccbdf4_idx')],
            },
        ),
    ]
