# Generated by Django 4.2.27 on 2025-12-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0025_prophetmodelmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftswaprequest',
            name='automated_decision',
            field=models.BooleanField(default=False, help_text='True if auto-approved by system'),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='qualification_match_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0-100 score for qualification match', max_digits=5),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='role_mismatch',
            field=models.BooleanField(default=False, help_text='Flags different roles requiring manual review'),
        ),
        migrations.AddField(
            model_name='shiftswaprequest',
            name='wdt_compliance_check',
            field=models.BooleanField(default=False, help_text='WTD compliance verified'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_APPROVED', 'Auto-Approved'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled'), ('MANUAL_REVIEW', 'Manual Review Required')], default='PENDING', max_length=20),
        ),
    ]
