# Generated by Django 4.2.27 on 2025-12-30 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0041_message_userpresence_systemactivity_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('gd', 'Scottish Gaelic (Gàidhlig)'), ('cy', 'Welsh (Cymraeg)'), ('pl', 'Polish (Polski)'), ('ro', 'Romanian (Română)'), ('es', 'Spanish (Español)'), ('ar', 'Arabic (العربية)'), ('ur', 'Urdu (اردو)'), ('zh-hans', 'Simplified Chinese (简体中文)')], default='en', max_length=10)),
                ('date_format', models.CharField(default='%d/%m/%Y', help_text='Date format string', max_length=20)),
                ('time_format', models.CharField(default='%H:%M', help_text='Time format string (24h by default)', max_length=20)),
                ('use_12_hour', models.BooleanField(default=False, help_text='Use 12-hour clock format')),
                ('timezone', models.CharField(default='Europe/London', max_length=50)),
                ('currency_symbol', models.CharField(default='£', max_length=5)),
                ('auto_detect_language', models.BooleanField(default=False, help_text='Auto-detect language from browser')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'language_code'], name='scheduling__user_id_a3c4db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Translation key', max_length=200)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('gd', 'Scottish Gaelic (Gàidhlig)'), ('cy', 'Welsh (Cymraeg)'), ('pl', 'Polish (Polski)'), ('ro', 'Romanian (Română)'), ('es', 'Spanish (Español)'), ('ar', 'Arabic (العربية)'), ('ur', 'Urdu (اردو)'), ('zh-hans', 'Simplified Chinese (简体中文)')], max_length=10)),
                ('translated_text', models.TextField(help_text='Translated text')),
                ('context', models.CharField(blank=True, help_text='Context for translation (e.g., "shift", "report")', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_translations', to=settings.AUTH_USER_MODEL)),
                ('care_home', models.ForeignKey(blank=True, help_text='Care home-specific translation (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', 'language_code'],
                'indexes': [models.Index(fields=['key', 'language_code'], name='scheduling__key_8cc9cb_idx'), models.Index(fields=['care_home', 'language_code'], name='scheduling__care_ho_1d1379_idx')],
                'unique_together': {('key', 'language_code', 'care_home')},
            },
        ),
    ]
