# Generated by Django 4.2.27 on 2025-12-30 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0047_userpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('trigger_type', models.CharField(default='manual', max_length=50)),
                ('trigger_config', models.JSONField(default=dict)),
                ('run_count', models.IntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'scheduling_workflow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('context', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('trigger_type', models.CharField(default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_executions_triggered', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduling.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Execution',
                'verbose_name_plural': 'Workflow Executions',
                'db_table': 'scheduling_workflow_execution',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('condition', 'Condition Check'), ('action', 'Execute Action'), ('delay', 'Wait/Delay'), ('branch', 'Branch/Split'), ('merge', 'Merge Branches'), ('end', 'End Workflow')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(default=dict)),
                ('action_type', models.CharField(blank=True, choices=[('send_email', 'Send Email'), ('send_notification', 'Send In-App Notification'), ('create_shift', 'Create Shift'), ('update_shift', 'Update Shift'), ('approve_leave', 'Approve Leave Request'), ('reject_leave', 'Reject Leave Request'), ('assign_staff', 'Assign Staff to Shift'), ('update_status', 'Update Status'), ('create_task', 'Create Task'), ('send_webhook', 'Send Webhook'), ('custom', 'Custom Action')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_failure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_from', to='scheduling.workflowstep')),
                ('on_success', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_from', to='scheduling.workflowstep')),
                ('parent_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_steps', to='scheduling.workflowstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scheduling.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'db_table': 'scheduling_workflow_step',
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual Trigger'), ('schedule', 'Scheduled (Cron)'), ('event', 'Event-Based'), ('webhook', 'Webhook')], max_length=50)),
                ('event_type', models.CharField(blank=True, choices=[('shift_created', 'Shift Created'), ('shift_updated', 'Shift Updated'), ('shift_deleted', 'Shift Deleted'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('staff_assigned', 'Staff Assigned to Shift'), ('compliance_violation', 'Compliance Violation Detected'), ('training_due', 'Training Due'), ('custom', 'Custom Event')], max_length=50)),
                ('schedule_expression', models.CharField(blank=True, max_length=200)),
                ('conditions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='scheduling.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Trigger',
                'verbose_name_plural': 'Workflow Triggers',
                'db_table': 'scheduling_workflow_trigger',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('leave', 'Leave Management'), ('shift', 'Shift Management'), ('compliance', 'Compliance'), ('notification', 'Notifications'), ('approval', 'Approval Process'), ('custom', 'Custom Workflow')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted')),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Template',
                'verbose_name_plural': 'Workflow Templates',
                'db_table': 'scheduling_workflow_template',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='scheduling.workflowexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='scheduling.workflowstep')),
            ],
            options={
                'verbose_name': 'Workflow Step Execution',
                'verbose_name_plural': 'Workflow Step Executions',
                'db_table': 'scheduling_workflow_step_execution',
                'ordering': ['execution', 'step__order'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_instances', to='scheduling.workflowtemplate'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow', '-created_at'], name='scheduling__workflo_e7651a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status'], name='scheduling__status_ae6dab_idx'),
        ),
    ]
