# Generated by Django 4.2.27 on 2025-12-30 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0051_recent_activity_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sap',
            field=models.CharField(help_text='6-digit SAP number (e.g., 123456)', max_length=6, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_sap', message='SAP number must be exactly 6 digits (e.g., 123456)', regex='^\\d{6}$')]),
        ),
    ]
