# Generated by Django 5.2.7 on 2025-10-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_shifttype_applicable_roles_alter_shifttype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color_code',
            field=models.CharField(choices=[('#e74c3c', 'Red'), ('#3498db', 'Blue'), ('#2ecc71', 'Green'), ('#9b59b6', 'Purple'), ('#f39c12', 'Orange'), ('#e67e22', 'Dark Orange')], default='#3498db', max_length=7),
        ),
    ]
