# Generated by Django 5.2.7 on 2025-10-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_role_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_unit',
            field=models.ForeignKey(blank=True, help_text='Permanent home unit for this staff member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_staff', to='scheduling.unit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_staff', to='scheduling.unit'),
        ),
    ]
