# Generated by Django 5.2.7 on 2025-10-15 22:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_user_shifts_per_week_override_alter_shifttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_period', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], max_length=5)),
                ('shifts_per_week', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('target_staff', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requirements', to='scheduling.role')),
            ],
            options={
                'ordering': ['role__name', 'shift_period', '-shifts_per_week'],
                'unique_together': {('role', 'shift_period', 'shifts_per_week')},
            },
        ),
    ]
