# Generated by Django 5.2.7 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_careplan_review_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careplanreview',
            name='completed_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='careplanreview',
            name='due_date',
            field=models.DateField(db_index=True, help_text='Date review is due by'),
        ),
        migrations.AlterField(
            model_name='careplanreview',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date review is scheduled for', null=True),
        ),
        migrations.AlterField(
            model_name='careplanreview',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due Soon (7 days)'), ('OVERDUE', 'Overdue'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Manager Approval'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='UPCOMING', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled'), ('MANUAL_REVIEW', 'Manual Review Required')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('UNCOVERED', 'Uncovered'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date', 'unit'], name='scheduling__date_07b4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['user', 'date'], name='scheduling__user_id_967cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date', 'shift_type'], name='scheduling__date_bb5e64_idx'),
        ),
    ]
