# Generated by Django 4.2.27 on 2025-12-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0023_aiquerylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True, help_text='Date being forecasted')),
                ('predicted_shifts', models.DecimalField(decimal_places=2, help_text='Predicted number of shifts needed', max_digits=5)),
                ('confidence_lower', models.DecimalField(decimal_places=2, help_text='Lower bound of 80% confidence interval', max_digits=5)),
                ('confidence_upper', models.DecimalField(decimal_places=2, help_text='Upper bound of 80% confidence interval', max_digits=5)),
                ('trend_component', models.DecimalField(blank=True, decimal_places=2, help_text='Long-term trend (increasing/decreasing demand)', max_digits=5, null=True)),
                ('weekly_component', models.DecimalField(blank=True, decimal_places=2, help_text='Day-of-week effect (weekend reduction, etc.)', max_digits=5, null=True)),
                ('yearly_component', models.DecimalField(blank=True, decimal_places=2, help_text='Seasonal effect (winter pressure, summer holidays)', max_digits=5, null=True)),
                ('model_version', models.CharField(default='1.0', help_text='Prophet model version used for this forecast', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When forecast was generated')),
                ('mae', models.DecimalField(blank=True, decimal_places=2, help_text='Mean Absolute Error from validation (shifts/day)', max_digits=5, null=True)),
                ('mape', models.DecimalField(blank=True, decimal_places=2, help_text='Mean Absolute Percentage Error from validation (%)', max_digits=5, null=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='scheduling.carehome')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Staffing Forecast',
                'verbose_name_plural': 'Staffing Forecasts',
                'ordering': ['forecast_date', 'care_home', 'unit'],
                'indexes': [models.Index(fields=['forecast_date', 'care_home'], name='scheduling__forecas_65f713_idx'), models.Index(fields=['forecast_date', 'unit'], name='scheduling__forecas_dc29f7_idx'), models.Index(fields=['care_home', 'unit', 'forecast_date'], name='scheduling__care_ho_5cb8de_idx')],
                'unique_together': {('care_home', 'unit', 'forecast_date', 'model_version')},
            },
        ),
    ]
