# Generated by Django 4.2.27 on 2025-12-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_sms_notifications'),
        ('scheduling', '0030_agencyblastbatch_agencyresponse_and_more'),
    ]

    operations = [
    ]
