# Generated by Django 4.2.27 on 2025-12-30 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0032_savedreport_scheduledreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="KPI name (e.g., 'Staff Turnover Rate')", max_length=200)),
                ('description', models.TextField(help_text='What this KPI measures and why it matters')),
                ('category', models.CharField(choices=[('STAFFING', 'Staffing Metrics'), ('OCCUPANCY', 'Occupancy Metrics'), ('FINANCIAL', 'Financial Metrics'), ('COMPLIANCE', 'Compliance Metrics'), ('QUALITY', 'Quality of Care'), ('EFFICIENCY', 'Operational Efficiency')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('COUNT', 'Count'), ('AVERAGE', 'Average'), ('RATIO', 'Ratio'), ('CURRENCY', 'Currency Amount')], max_length=20)),
                ('formula_description', models.TextField(help_text="Human-readable formula (e.g., '(Staff Left / Total Staff) * 100')")),
                ('measurement_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='MONTHLY', help_text='How often this KPI should be measured', max_length=20)),
                ('higher_is_better', models.BooleanField(default=True, help_text='True if higher values are better, False if lower values are better')),
                ('critical_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Critical alert threshold', max_digits=10, null=True)),
                ('warning_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Warning alert threshold', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_home', models.ForeignKey(blank=True, help_text='Specific care home (null for system-wide KPI)', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, help_text='Specific unit (null for home-wide or system-wide KPI)', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'KPI Definition',
                'verbose_name_plural': 'KPI Definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Target year')),
                ('quarter', models.IntegerField(blank=True, help_text='Quarter (1-4) for quarterly targets', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('month', models.IntegerField(blank=True, help_text='Month (1-12) for monthly targets', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value to achieve', max_digits=10)),
                ('stretch_target', models.DecimalField(blank=True, decimal_places=2, help_text='Ambitious stretch target', max_digits=10, null=True)),
                ('minimum_acceptable', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum acceptable performance', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Target setting rationale or context', null=True)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='scheduling.kpidefinition')),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_kpi_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Target',
                'verbose_name_plural': 'KPI Targets',
                'ordering': ['-year', '-quarter', '-month'],
                'unique_together': {('kpi', 'year', 'quarter', 'month')},
            },
        ),
        migrations.CreateModel(
            name='KPIMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(help_text='Date of measurement')),
                ('period_start', models.DateField(help_text='Start of measurement period')),
                ('period_end', models.DateField(help_text='End of measurement period')),
                ('measured_value', models.DecimalField(decimal_places=2, help_text='Actual measured value', max_digits=10)),
                ('calculation_details', models.JSONField(default=dict, help_text='Breakdown of how value was calculated (numerator, denominator, etc.)')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Target value at time of measurement', max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='Difference from target (measured - target)', max_digits=10, null=True)),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage variance from target', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('EXCELLENT', 'Exceeds Target'), ('GOOD', 'Meets Target'), ('WARNING', 'Below Target'), ('CRITICAL', 'Critical Threshold Breached')], help_text='Performance status vs target', max_length=20)),
                ('alert_generated', models.BooleanField(default=False, help_text='True if this measurement triggered an alert')),
                ('alert_message', models.TextField(blank=True, help_text='Alert message if threshold breached', null=True)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('is_automated', models.BooleanField(default=True, help_text='True if automatically calculated, False if manually entered')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='scheduling.kpidefinition')),
                ('measured_by', models.ForeignKey(blank=True, help_text='User who recorded measurement (null for automated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Measurement',
                'verbose_name_plural': 'KPI Measurements',
                'ordering': ['-measurement_date'],
                'indexes': [models.Index(fields=['kpi', '-measurement_date'], name='scheduling__kpi_id_69129c_idx'), models.Index(fields=['status', 'alert_generated'], name='scheduling__status_124c9e_idx')],
                'unique_together': {('kpi', 'measurement_date')},
            },
        ),
    ]
