# Generated by Django 4.2.27 on 2025-12-30 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0033_kpidefinition_kpitarget_kpimeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Visualization name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visualization_type', models.CharField(choices=[('STAFFING_HEATMAP', 'Staffing Heat Map'), ('SHIFT_TIMELINE', 'Shift Timeline'), ('OCCUPANCY_TREND', 'Occupancy Trend'), ('TRAINING_MATRIX', 'Training Matrix'), ('LEAVE_CALENDAR', 'Leave Calendar'), ('AGENCY_BREAKDOWN', 'Agency Breakdown'), ('COST_ANALYSIS', 'Cost Analysis'), ('PERFORMANCE_RADAR', 'Performance Radar'), ('CUSTOM', 'Custom Visualization')], help_text='Type of visualization', max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Complete visualization configuration')),
                ('is_public', models.BooleanField(default=False, help_text='Share with other managers')),
                ('use_count', models.IntegerField(default=0, help_text='Number of times used in dashboards')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(blank=True, help_text='Specific care home (null for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='scheduling.carehome')),
                ('created_by', models.ForeignKey(help_text='Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Visualization',
                'verbose_name_plural': 'Data Visualizations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dashboard name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Dashboard description')),
                ('layout_config', models.JSONField(default=dict, help_text='Grid layout configuration (rows, columns, widget positions)')),
                ('is_public', models.BooleanField(default=False, help_text='Share with other managers')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default dashboard for care home')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(blank=True, help_text='Specific care home (null for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='scheduling.carehome')),
                ('created_by', models.ForeignKey(help_text='Dashboard creator', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Layout',
                'verbose_name_plural': 'Dashboard Layouts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Widget title', max_length=200)),
                ('chart_type', models.CharField(choices=[('LINE', 'Line Chart'), ('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('DOUGHNUT', 'Doughnut Chart'), ('RADAR', 'Radar Chart'), ('HEATMAP', 'Heat Map'), ('GAUGE', 'Gauge'), ('TABLE', 'Data Table'), ('STAT_CARD', 'Stat Card')], default='LINE', help_text='Type of chart/visualization', max_length=20)),
                ('data_source', models.CharField(choices=[('STAFF_COUNT', 'Staff Count'), ('SHIFT_COUNT', 'Shift Count'), ('OCCUPANCY', 'Occupancy Rate'), ('LEAVE_REQUESTS', 'Leave Requests'), ('TRAINING_STATUS', 'Training Status'), ('AGENCY_USAGE', 'Agency Usage'), ('OVERTIME_HOURS', 'Overtime Hours'), ('TURNOVER_RATE', 'Staff Turnover'), ('COMPLIANCE_RATE', 'Compliance Rate'), ('INCIDENT_COUNT', 'Incident Count'), ('KPI_METRIC', 'KPI Metric'), ('CUSTOM_QUERY', 'Custom Query')], help_text='Primary data source', max_length=50)),
                ('data_config', models.JSONField(default=dict, help_text='Data source configuration (filters, aggregation, grouping)')),
                ('chart_config', models.JSONField(default=dict, help_text='Chart.js configuration (colors, labels, options)')),
                ('grid_position', models.JSONField(default=dict, help_text='Position in dashboard grid (row, col, rowspan, colspan)')),
                ('refresh_interval', models.CharField(choices=[('MANUAL', 'Manual Only'), ('REALTIME', 'Real-time'), ('5MIN', 'Every 5 Minutes'), ('15MIN', 'Every 15 Minutes'), ('1HOUR', 'Every Hour'), ('1DAY', 'Daily')], default='MANUAL', help_text='How often to refresh data', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(help_text='Parent dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='scheduling.dashboardlayout')),
            ],
            options={
                'verbose_name': 'Chart Widget',
                'verbose_name_plural': 'Chart Widgets',
                'ordering': ['dashboard', 'grid_position'],
            },
        ),
    ]
