# Generated by Django 4.2.27 on 2025-12-30 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0034_datavisualization_dashboardlayout_chartwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('STAFF_COUNT', 'Staff Count'), ('SHIFT_VOLUME', 'Shift Volume'), ('OCCUPANCY', 'Occupancy Rate'), ('AGENCY_USAGE', 'Agency Usage'), ('OVERTIME', 'Overtime Hours'), ('TURNOVER', 'Staff Turnover'), ('LEAVE_REQUESTS', 'Leave Requests'), ('INCIDENTS', 'Incident Count'), ('TRAINING_COMPLETION', 'Training Completion'), ('COST', 'Cost Metrics')], help_text='Type of metric analyzed', max_length=50)),
                ('name', models.CharField(help_text='Analysis name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(help_text='Analysis start date')),
                ('end_date', models.DateField(help_text='Analysis end date')),
                ('trend_direction', models.CharField(choices=[('INCREASING', 'Increasing'), ('DECREASING', 'Decreasing'), ('STABLE', 'Stable'), ('VOLATILE', 'Volatile')], help_text='Overall trend direction', max_length=20)),
                ('slope', models.DecimalField(decimal_places=4, help_text='Linear regression slope', max_digits=10)),
                ('r_squared', models.DecimalField(blank=True, decimal_places=4, help_text='Coefficient of determination (goodness of fit)', max_digits=5, null=True)),
                ('time_series_data', models.JSONField(default=dict, help_text='Raw time series data points {date: value}')),
                ('decomposition', models.JSONField(default=dict, help_text='Trend, seasonal, residual components')),
                ('statistics', models.JSONField(default=dict, help_text='Mean, median, std dev, min, max, etc.')),
                ('forecast_data', models.JSONField(default=dict, help_text='Predicted future values')),
                ('confidence_interval', models.DecimalField(blank=True, decimal_places=2, help_text='Forecast confidence level (%)', max_digits=5, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(help_text='User who ran analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend_analyses', to=settings.AUTH_USER_MODEL)),
                ('care_home', models.ForeignKey(blank=True, help_text='Specific care home (null for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='scheduling.carehome')),
                ('unit', models.ForeignKey(blank=True, help_text='Specific unit (null for wider scope)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_analyses', to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Trend Analysis',
                'verbose_name_plural': 'Trend Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalityPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('DAILY', 'Daily Pattern'), ('WEEKLY', 'Weekly Pattern'), ('MONTHLY', 'Monthly Pattern'), ('QUARTERLY', 'Quarterly Pattern'), ('YEARLY', 'Yearly Pattern')], help_text='Type of seasonal pattern', max_length=20)),
                ('strength', models.DecimalField(decimal_places=2, help_text='Pattern strength (0-100%)', max_digits=5)),
                ('pattern_data', models.JSONField(default=dict, help_text='Pattern values by period (e.g., by day of week)')),
                ('peak_periods', models.JSONField(default=list, help_text='Periods with highest values')),
                ('trough_periods', models.JSONField(default=list, help_text='Periods with lowest values')),
                ('p_value', models.DecimalField(blank=True, decimal_places=5, help_text='Statistical significance (p-value)', max_digits=6, null=True)),
                ('is_significant', models.BooleanField(default=False, help_text='True if pattern is statistically significant')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('trend_analysis', models.ForeignKey(help_text='Parent trend analysis', on_delete=django.db.models.deletion.CASCADE, related_name='seasonality_patterns', to='scheduling.trendanalysis')),
            ],
            options={
                'verbose_name': 'Seasonality Pattern',
                'verbose_name_plural': 'Seasonality Patterns',
                'ordering': ['-strength'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('SPIKE', 'Spike (Sudden Increase)'), ('DROP', 'Drop (Sudden Decrease)'), ('OUTLIER', 'Outlier (Statistical)'), ('SHIFT', 'Level Shift'), ('TREND_CHANGE', 'Trend Change')], help_text='Type of anomaly detected', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Severity level', max_length=10)),
                ('detected_date', models.DateField(help_text='Date of anomaly')),
                ('actual_value', models.DecimalField(decimal_places=2, help_text='Actual value at anomaly', max_digits=10)),
                ('expected_value', models.DecimalField(decimal_places=2, help_text='Expected value (from trend)', max_digits=10)),
                ('deviation', models.DecimalField(decimal_places=2, help_text='Deviation from expected', max_digits=10)),
                ('deviation_percentage', models.DecimalField(decimal_places=2, help_text='Percentage deviation', max_digits=6)),
                ('z_score', models.DecimalField(blank=True, decimal_places=3, help_text='Standard deviations from mean', max_digits=6, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Detection confidence (%)', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Description of anomaly and potential causes')),
                ('alert_generated', models.BooleanField(default=False, help_text='True if alert was sent')),
                ('acknowledged', models.BooleanField(default=False, help_text='True if anomaly acknowledged by manager')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When acknowledged', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User who acknowledged', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_anomalies', to=settings.AUTH_USER_MODEL)),
                ('trend_analysis', models.ForeignKey(help_text='Parent trend analysis', on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='scheduling.trendanalysis')),
            ],
            options={
                'verbose_name': 'Anomaly Detection',
                'verbose_name_plural': 'Anomaly Detections',
                'ordering': ['-severity', '-detected_date'],
                'indexes': [models.Index(fields=['trend_analysis', '-detected_date'], name='scheduling__trend_a_72f02b_idx'), models.Index(fields=['severity', 'acknowledged'], name='scheduling__severit_7b04db_idx')],
            },
        ),
    ]
