# Generated by Django 4.2.27 on 2025-12-30 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0035_trendanalysis_seasonalitypattern_anomalydetection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pattern_type', models.CharField(choices=[('PEAK', 'Peak Period'), ('TROUGH', 'Trough Period'), ('BALANCED', 'Balanced Coverage'), ('UNDERSTAFFED', 'Understaffed'), ('OVERSTAFFED', 'Overstaffed')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('shift_type', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('average_staff_count', models.DecimalField(decimal_places=2, max_digits=6)),
                ('required_staff_count', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pattern_data', models.JSONField(default=dict, help_text='Daily staffing levels and trends')),
                ('frequency', models.IntegerField(default=0, help_text='Number of times this pattern occurs')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recommendation', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Priority')], default='MEDIUM', max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Shift Pattern',
                'verbose_name_plural': 'Shift Patterns',
                'ordering': ['-analyzed_at', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='CoverageGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_date', models.DateField()),
                ('shift_type', models.CharField(max_length=20)),
                ('required_staff', models.IntegerField()),
                ('actual_staff', models.IntegerField()),
                ('gap_size', models.IntegerField(help_text='Required - Actual')),
                ('gap_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Severity')], max_length=20)),
                ('impact_score', models.DecimalField(decimal_places=2, help_text='Impact score (0-100)', max_digits=5)),
                ('is_filled', models.BooleanField(default=False)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_gaps', to=settings.AUTH_USER_MODEL)),
                ('shift_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_gaps', to='scheduling.shiftpattern')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Coverage Gap',
                'verbose_name_plural': 'Coverage Gaps',
                'ordering': ['-gap_date', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('distribution_data', models.JSONField(default=dict, help_text='Workload distribution by staff, shift type, day of week')),
                ('balance_score', models.DecimalField(decimal_places=2, help_text='Distribution balance score (0-100, higher is better)', max_digits=5)),
                ('gini_coefficient', models.DecimalField(blank=True, decimal_places=4, help_text='Gini coefficient for inequality (0-1, lower is better)', max_digits=5, null=True)),
                ('average_shifts_per_staff', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_shifts_per_staff', models.IntegerField()),
                ('min_shifts_per_staff', models.IntegerField()),
                ('standard_deviation', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shift_type_balance', models.JSONField(default=dict, help_text='Distribution across EARLY, LATE, NIGHT, etc.')),
                ('recommendations', models.TextField(blank=True)),
                ('is_balanced', models.BooleanField(default=False, help_text='True if distribution is considered fair/balanced')),
                ('unfairness_score', models.DecimalField(decimal_places=2, default=0, help_text='Unfairness score (0-100, lower is better)', max_digits=5)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('shift_pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload_distributions', to='scheduling.shiftpattern')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Workload Distribution',
                'verbose_name_plural': 'Workload Distributions',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['care_home', '-analyzed_at'], name='scheduling__care_ho_cf6833_idx'), models.Index(fields=['is_balanced'], name='scheduling__is_bala_97f7cb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='shiftpattern',
            index=models.Index(fields=['care_home', 'pattern_type'], name='scheduling__care_ho_6bda15_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftpattern',
            index=models.Index(fields=['day_of_week', 'shift_type'], name='scheduling__day_of__2aea24_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragegap',
            index=models.Index(fields=['care_home', 'gap_date'], name='scheduling__care_ho_8604b2_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragegap',
            index=models.Index(fields=['severity', 'is_filled'], name='scheduling__severit_05cbb8_idx'),
        ),
        migrations.AddIndex(
            model_name='coveragegap',
            index=models.Index(fields=['-gap_date', 'shift_type'], name='scheduling__gap_dat_4f7934_idx'),
        ),
    ]
