# Generated by Django 4.2.27 on 2025-12-30 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0036_shiftpattern_coveragegap_workloaddistribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('permanent_staff_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agency_staff_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('training_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('benefits_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_shifts', models.IntegerField(default=0)),
                ('permanent_shifts', models.IntegerField(default=0)),
                ('agency_shifts', models.IntegerField(default=0)),
                ('overtime_shifts', models.IntegerField(default=0)),
                ('cost_per_shift', models.DecimalField(decimal_places=2, max_digits=8)),
                ('permanent_cost_per_shift', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('agency_cost_per_shift', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('agency_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of shifts filled by agency staff', max_digits=5)),
                ('cost_efficiency_score', models.DecimalField(decimal_places=2, help_text='Cost efficiency score (0-100, higher is better)', max_digits=5)),
                ('cost_breakdown_data', models.JSONField(default=dict, help_text='Daily cost breakdown and trends')),
                ('cost_by_category', models.JSONField(default=dict, help_text='Cost distribution by category')),
                ('potential_savings', models.DecimalField(decimal_places=2, default=0, help_text='Potential cost savings identified', max_digits=10)),
                ('savings_recommendations', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Cost Analysis',
                'verbose_name_plural': 'Cost Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('historical_start_date', models.DateField()),
                ('historical_end_date', models.DateField()),
                ('forecast_start_date', models.DateField()),
                ('forecast_end_date', models.DateField()),
                ('forecast_months', models.IntegerField(help_text='Number of months forecasted')),
                ('forecast_method', models.CharField(choices=[('LINEAR', 'Linear Regression'), ('AVERAGE', 'Historical Average'), ('SEASONAL', 'Seasonal Adjustment'), ('TREND', 'Trend Analysis')], max_length=20)),
                ('historical_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('historical_average_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forecasted_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forecasted_monthly_average', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_forecast', models.JSONField(default=dict, help_text='Month-by-month forecast data')),
                ('confidence_level', models.DecimalField(decimal_places=2, help_text='Forecast confidence (0-100%)', max_digits=5)),
                ('margin_of_error', models.DecimalField(decimal_places=2, help_text='Margin of error (±%)', max_digits=6)),
                ('budget_target', models.DecimalField(blank=True, decimal_places=2, help_text='Target budget for period', max_digits=10, null=True)),
                ('budget_variance', models.DecimalField(blank=True, decimal_places=2, help_text='Forecast - Target', max_digits=10, null=True)),
                ('is_within_budget', models.BooleanField(default=False, help_text='True if forecast is within budget')),
                ('trend_direction', models.CharField(choices=[('INCREASING', 'Increasing'), ('DECREASING', 'Decreasing'), ('STABLE', 'Stable')], default='STABLE', max_length=20)),
                ('trend_percentage', models.DecimalField(decimal_places=2, help_text='Trend change percentage', max_digits=6)),
                ('recommendations', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Budget Forecast',
                'verbose_name_plural': 'Budget Forecasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyCostComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agency_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agency_shift_count', models.IntegerField()),
                ('agency_cost_per_shift', models.DecimalField(decimal_places=2, max_digits=8)),
                ('agency_hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('permanent_total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('permanent_shift_count', models.IntegerField()),
                ('permanent_cost_per_shift', models.DecimalField(decimal_places=2, max_digits=8)),
                ('permanent_hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_difference', models.DecimalField(decimal_places=2, help_text='Agency cost - Permanent cost', max_digits=10)),
                ('cost_difference_percentage', models.DecimalField(decimal_places=2, help_text='Percentage difference', max_digits=6)),
                ('agency_premium', models.DecimalField(decimal_places=2, help_text='Agency premium over permanent (percentage)', max_digits=6)),
                ('total_premium_paid', models.DecimalField(decimal_places=2, help_text='Total extra cost paid for agency staff', max_digits=10)),
                ('if_all_permanent_cost', models.DecimalField(decimal_places=2, help_text='Cost if all shifts were permanent', max_digits=10)),
                ('potential_monthly_savings', models.DecimalField(decimal_places=2, help_text='Potential savings per month', max_digits=10)),
                ('recommendation', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Priority')], default='MEDIUM', max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('cost_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_comparisons', to='scheduling.costanalysis')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Agency Cost Comparison',
                'verbose_name_plural': 'Agency Cost Comparisons',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='costanalysis',
            index=models.Index(fields=['care_home', '-analyzed_at'], name='scheduling__care_ho_23861f_idx'),
        ),
        migrations.AddIndex(
            model_name='costanalysis',
            index=models.Index(fields=['start_date', 'end_date'], name='scheduling__start_d_a11bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetforecast',
            index=models.Index(fields=['care_home', '-created_at'], name='scheduling__care_ho_9be469_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetforecast',
            index=models.Index(fields=['forecast_start_date', 'forecast_end_date'], name='scheduling__forecas_d05ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='agencycostcomparison',
            index=models.Index(fields=['care_home', '-analyzed_at'], name='scheduling__care_ho_e9c82d_idx'),
        ),
        migrations.AddIndex(
            model_name='agencycostcomparison',
            index=models.Index(fields=['start_date', 'end_date'], name='scheduling__start_d_82ce40_idx'),
        ),
    ]
