# Generated by Django 4.2.27 on 2025-12-30 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0042_userlanguagepreference_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('STAFF', 'Staff Report'), ('SHIFTS', 'Shifts Report'), ('LEAVE', 'Leave Report'), ('BUDGET', 'Budget Report'), ('COMPLIANCE', 'Compliance Report'), ('CUSTOM', 'Custom Query Report')], max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Make this report available to all users')),
                ('shared_with_roles', models.JSONField(default=list, help_text='List of role names that can access this report')),
                ('data_sources', models.JSONField(help_text='Base model and related fields to query')),
                ('filters', models.JSONField(default=dict, help_text='Filter conditions in JSON format')),
                ('grouping', models.JSONField(default=dict, help_text='Grouping and aggregation configuration')),
                ('sorting', models.JSONField(default=list, help_text='Sorting configuration')),
                ('columns', models.JSONField(default=list, help_text='Column definitions for display')),
                ('formatting', models.JSONField(default=dict, help_text='Display formatting options')),
                ('default_export_format', models.CharField(choices=[('PDF', 'PDF Document'), ('EXCEL', 'Excel Spreadsheet'), ('CSV', 'CSV File'), ('JSON', 'JSON Data')], default='EXCEL', max_length=10)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, max_length=20)),
                ('schedule_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_count', models.IntegerField(default=0)),
                ('avg_execution_time', models.FloatField(default=0.0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fields', models.JSONField(help_text='Available fields with types and labels')),
                ('relationships', models.JSONField(default=dict, help_text='Related models that can be joined')),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('run_time', models.TimeField()),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('quarter_month', models.IntegerField(blank=True, null=True)),
                ('year_month', models.IntegerField(blank=True, null=True)),
                ('email_recipients', models.JSONField(default=list)),
                ('export_format', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scheduling.customreporttemplate')),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='scheduling.customreporttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_custom_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'template')},
            },
        ),
        migrations.CreateModel(
            name='CustomSavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used for this report generation')),
                ('data', models.JSONField(default=list, help_text='Generated report data rows')),
                ('row_count', models.IntegerField(default=0)),
                ('export_format', models.CharField(blank=True, max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_custom_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='scheduling.customreporttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['template', '-generated_at'], name='scheduling__templat_5ad2b5_idx'), models.Index(fields=['generated_by', '-generated_at'], name='scheduling__generat_eb0daf_idx'), models.Index(fields=['status'], name='scheduling__status_078e8b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customreporttemplate',
            index=models.Index(fields=['created_by', '-created_at'], name='scheduling__created_183dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='customreporttemplate',
            index=models.Index(fields=['is_public'], name='scheduling__is_publ_1b60c0_idx'),
        ),
    ]
