# Generated by Django 4.2.27 on 2025-12-30 17:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import scheduling.models_documents


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0048_workflow_automation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=scheduling.models_documents.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar', '7z'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of file', max_length=64)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('access_level', models.CharField(choices=[('public', 'Public - All users can view'), ('staff', 'Staff Only - All staff can view'), ('managers', 'Managers Only - Only managers can view'), ('private', 'Private - Only specified users'), ('confidential', 'Confidential - Restricted access')], default='staff', max_length=20)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of role names that can access this document')),
                ('version', models.IntegerField(default=1)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='accessible_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'scheduling_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scheduling.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='scheduling.documentcomment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Comment',
                'verbose_name_plural': 'Document Comments',
                'db_table': 'scheduling_document_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-folder', help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='scheduling.documentcategory')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'db_table': 'scheduling_document_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='scheduling.documentcategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='scheduling.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_download', models.BooleanField(default=True)),
                ('can_reshare', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_downloads', models.IntegerField(blank=True, help_text='Maximum number of downloads allowed (null = unlimited)', null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='scheduling.document')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_shared_with_me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Share',
                'verbose_name_plural': 'Document Shares',
                'db_table': 'scheduling_document_share',
                'ordering': ['-created_at'],
                'unique_together': {('document', 'shared_with')},
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('preview', 'Previewed'), ('share', 'Shared')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='scheduling.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Log',
                'verbose_name_plural': 'Document Access Logs',
                'db_table': 'scheduling_document_access',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['document', '-accessed_at'], name='scheduling__documen_1a1275_idx'), models.Index(fields=['user', '-accessed_at'], name='scheduling__user_id_7339e8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='scheduling__uploade_6058af_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', '-uploaded_at'], name='scheduling__categor_f7daf0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['access_level'], name='scheduling__access__2098e0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_latest_version', 'is_archived'], name='scheduling__is_late_c562e5_idx'),
        ),
    ]
