# Generated by Django 4.2.27 on 2026-01-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='survey_type',
            field=models.CharField(choices=[('RESIDENT_ADMISSION', 'Resident - Admission'), ('RESIDENT_ONGOING', 'Resident - Ongoing Care'), ('RESIDENT_DISCHARGE', 'Resident - Discharge'), ('FAMILY_ADMISSION', 'Family - Admission'), ('FAMILY_ONGOING', 'Family - Ongoing Care'), ('FAMILY_BEREAVEMENT', 'Family - Bereavement'), ('STAFF_EXPERIENCE', 'Staff - Experience Survey'), ('PROFESSIONAL_PARTNERSHIP', 'Professional - Partnership Survey')], help_text='Type of satisfaction survey', max_length=30),
        ),
    ]
