#!/bin/bash
# Automated Compliance Check Installer
# Generated by setup_scheduled_tasks command

set -e

echo "=== Installing Scheduled Compliance Checks ==="
echo ""

# Create log directory
echo "Creating log directory..."
sudo mkdir -p /var/log/rotasystem
sudo chown $USER:staff /var/log/rotasystem
echo "✓ Log directory created"

# Backup existing crontab
echo ""
echo "Backing up existing crontab..."
crontab -l > /tmp/crontab_backup_$(date +%Y%m%d_%H%M%S).txt 2>/dev/null || echo "No existing crontab"

# Create new crontab entries
echo ""
echo "Creating crontab entries..."

# Get existing crontab
crontab -l > /tmp/current_crontab 2>/dev/null || touch /tmp/current_crontab

# Add new entries if they don't exist
grep -q "Daily compliance checks" /tmp/current_crontab || cat >> /tmp/current_crontab << 'EOF'

# ===== Staff Rota Automated Compliance Checks =====

# Daily compliance checks at 2:00 AM
0 2 * * * cd /Users/deansockalingum/Staff\ Rota/rotasystems && /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 manage.py run_compliance_checks --start-date $(date +\%Y-\%m-\%d) --end-date $(date -v+7d +\%Y-\%m-\%d) >> /var/log/rotasystem/compliance.log 2>&1

# Daily violation digest at 8:00 AM
0 8 * * * cd /Users/deansockalingum/Staff\ Rota/rotasystems && /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 manage.py shell -c "from scheduling.utils.notifications import send_daily_violation_digest; send_daily_violation_digest()" >> /var/log/rotasystem/notifications.log 2>&1

# Weekly compliance summary every Monday at 9:00 AM
0 9 * * 1 cd /Users/deansockalingum/Staff\ Rota/rotasystems && /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 manage.py shell -c "from scheduling.utils.notifications import send_weekly_compliance_summary; send_weekly_compliance_summary()" >> /var/log/rotasystem/notifications.log 2>&1

# ===== Annual Leave Reminder Emails =====

# Monthly leave reminder - 1st of each month at 9:00 AM (all staff with 5+ days remaining)
0 9 1 * * cd /Users/deansockalingum/Staff\ Rota/rotasystems && /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 manage.py send_leave_reminders --min-days 5 >> /var/log/rotasystem/leave_reminders.log 2>&1

# Quarterly urgent reminder - 1st of Jan/Apr/Jul/Oct at 9:00 AM (all staff with any leave remaining)
0 9 1 1,4,7,10 * cd /Users/deansockalingum/Staff\ Rota/rotasystems && /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 manage.py send_leave_reminders --min-days 1 >> /var/log/rotasystem/leave_reminders.log 2>&1

# Year-end urgent reminder - December 1st at 9:00 AM (all staff with unused leave)
0 9 1 12 * cd /Users/deansockalingum/Staff\ Rota/rotasystems && /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 manage.py send_leave_reminders >> /var/log/rotasystem/leave_reminders.log 2>&1

# Mid-December final warning - December 15th at 9:00 AM (urgent - less than 10 days to use leave)
0 9 15 12 * cd /Users/deansockalingum/Staff\ Rota/rotasystems && /Library/Frameworks/Python.framework/Versions/3.14/bin/python3 manage.py send_leave_reminders >> /var/log/rotasystem/leave_reminders.log 2>&1

EOF

# Install new crontab
crontab /tmp/current_crontab
rm /tmp/current_crontab

echo "✓ Crontab entries installed"
echo ""
echo "=== Installation Complete ==="
echo ""
echo "Scheduled tasks:"
echo "  - Daily compliance checks: 2:00 AM"
echo "  - Daily violation digest: 8:00 AM"
echo "  - Weekly summary: Monday 9:00 AM"
echo ""
echo "Annual Leave Reminders:"
echo "  - Monthly reminder (5+ days): 1st of month at 9:00 AM"
echo "  - Quarterly reminder (1+ days): Jan/Apr/Jul/Oct 1st at 9:00 AM"
echo "  - Year-end urgent (all): December 1st at 9:00 AM"
echo "  - Final warning: December 15th at 9:00 AM"
echo ""
echo "Logs location: /var/log/rotasystem/"
echo "  - compliance.log (compliance checks)"
echo "  - notifications.log (violation digests)"
echo "  - leave_reminders.log (leave reminder emails)"
echo ""
echo "To view current crontab: crontab -l"
echo "To remove crontab: crontab -r"
