# Generated by Django 5.2.7 on 2025-12-10 21:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_staffingalerttemplate_staffingalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeOfferBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active - Awaiting Responses'), ('ACCEPTED', 'Accepted - Shift Filled'), ('EXPIRED', 'Expired - No Responses'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Overtime Offer Batch',
                'verbose_name_plural': 'Overtime Offer Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ORCHARD_GROVE', 'Orchard Grove'), ('MEADOWBURN', 'Meadowburn'), ('HAWTHORN_HOUSE', 'Hawthorn House'), ('RIVERSIDE', 'Riverside'), ('VICTORIA_GARDENS', 'Victoria Gardens')], max_length=100, unique=True)),
                ('bed_capacity', models.IntegerField(help_text='Total number of beds in this home')),
                ('current_occupancy', models.IntegerField(default=0, help_text='Current number of residents')),
                ('location_address', models.TextField()),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('care_inspectorate_id', models.CharField(help_text='Care Inspectorate registration number', max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('budget_agency_monthly', models.DecimalField(decimal_places=2, default=Decimal('9000.00'), help_text='Monthly agency spend budget', max_digits=10)),
                ('budget_overtime_monthly', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Monthly overtime budget', max_digits=10)),
                ('main_phone', models.CharField(blank=True, max_length=20)),
                ('main_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_manager', models.ForeignKey(blank=True, limit_choices_to={'role__is_management': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_homes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Care Home',
                'verbose_name_plural': 'Care Homes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_rank', models.IntegerField(help_text='1 = highest priority based on algorithm')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ot_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=3)),
                ('estimated_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_offers', to='scheduling.shift')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_offers_received', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='scheduling.overtimeofferbatch')),
            ],
            options={
                'verbose_name': 'Overtime Offer',
                'verbose_name_plural': 'Overtime Offers',
                'ordering': ['batch', 'priority_rank'],
            },
        ),
        migrations.CreateModel(
            name='PostShiftAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('sickness_confirmed', models.BooleanField(default=False)),
                ('sickness_notes', models.TextField(blank=True)),
                ('off_duty_changes', models.JSONField(default=list, help_text='List of any off-duty changes made')),
                ('overtime_worked', models.BooleanField(default=False)),
                ('ot_hours_confirmed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('agency_used', models.BooleanField(default=False)),
                ('agency_staff_details', models.JSONField(blank=True, help_text='Details of agency staff used', null=True)),
                ('agency_hours_confirmed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('agency_cost_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amar_updated', models.BooleanField(default=False)),
                ('rota_updated', models.BooleanField(default=False)),
                ('payroll_updated', models.BooleanField(default=False)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_shift_admins_completed', to=settings.AUTH_USER_MODEL)),
                ('ot_staff', models.ManyToManyField(blank=True, related_name='ot_admin_records', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_shift_admin', to='scheduling.shift')),
            ],
            options={
                'verbose_name': 'Post-Shift Administration',
                'verbose_name_plural': 'Post-Shift Administration Records',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='SicknessAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_datetime', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('expected_duration_days', models.IntegerField(help_text='Expected number of days absent')),
                ('is_long_term', models.BooleanField(default=False, help_text='True if ≥3 shifts OR ≥5 days')),
                ('status', models.CharField(choices=[('LOGGED', 'Sickness Logged'), ('ROTA_UPDATED', 'Rota Updated'), ('REQUEST_DRAFTED', 'Cover Request Drafted'), ('MANAGER_NOTIFIED', 'Manager Notified'), ('IN_PROGRESS', 'Cover Process In Progress'), ('RESOLVED', 'Cover Arranged'), ('CANCELLED', 'Cancelled')], default='LOGGED', max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('fit_note_required', models.BooleanField(default=False)),
                ('fit_note_received', models.BooleanField(default=False)),
                ('fit_note_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('return_to_work_interview_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_shifts', models.ManyToManyField(blank=True, related_name='sickness_absences', to='scheduling.shift')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sickness_reports_made', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sickness_absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sickness Absence',
                'verbose_name_plural': 'Sickness Absences',
                'ordering': ['-reported_datetime'],
            },
        ),
        migrations.CreateModel(
            name='LongTermCoverPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('total_shifts_affected', models.IntegerField()),
                ('status', models.CharField(choices=[('PLANNING_INITIATED', 'Planning Initiated'), ('STRATEGY_GENERATED', 'Strategy Generated'), ('MANAGER_REVIEW', 'Awaiting Manager Review'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PLANNING_INITIATED', max_length=50)),
                ('strategy', models.JSONField(blank=True, help_text='Recommended mix of reallocation/OT/agency', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_plan', to='scheduling.sicknessabsence')),
            ],
            options={
                'verbose_name': 'Long-Term Cover Plan',
                'verbose_name_plural': 'Long-Term Cover Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffingCoverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('requested_by_system', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_MANAGER_REVIEW', 'Pending Manager Review'), ('SEARCHING_INTERNAL', 'Searching Internal Cover'), ('WAITING_REALLOCATION', 'Waiting for Reallocation Response'), ('WAITING_OT', 'Waiting for OT Responses'), ('ESCALATED_TO_AGENCY', 'Escalated to Agency'), ('RESOLVED_REALLOCATION', 'Resolved - Reallocation'), ('RESOLVED_OVERTIME', 'Resolved - Overtime'), ('RESOLVED_AGENCY', 'Resolved - Agency'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed to Fill')], default='PENDING_MANAGER_REVIEW', max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, help_text='Method: REALLOCATION, OVERTIME, or AGENCY', max_length=50)),
                ('reallocation_deadline', models.DateTimeField(blank=True, null=True)),
                ('ot_response_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_requests', to='scheduling.sicknessabsence')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_requests', to='scheduling.shift')),
            ],
            options={
                'verbose_name': 'Staffing Cover Request',
                'verbose_name_plural': 'Staffing Cover Requests',
                'ordering': ['-created_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ReallocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_staff_list', models.JSONField(default=list, help_text='List of staff IDs with surplus capacity')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired (No Response)')], default='PENDING_APPROVAL', max_length=50)),
                ('response_deadline', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reallocations_selected', to=settings.AUTH_USER_MODEL)),
                ('source_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_from', to='scheduling.carehome')),
                ('target_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocation_targets', to='scheduling.shift')),
                ('cover_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocation_requests', to='scheduling.staffingcoverrequest')),
            ],
            options={
                'verbose_name': 'Reallocation Request',
                'verbose_name_plural': 'Reallocation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='overtimeofferbatch',
            name='cover_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_offer_batches', to='scheduling.staffingcoverrequest'),
        ),
        migrations.CreateModel(
            name='AgencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Senior Officer Approval'), ('APPROVED', 'Approved'), ('AUTO_APPROVED', 'Auto-Approved (Timeout)'), ('DECLINED', 'Declined'), ('SENT_TO_AGENCY', 'Sent to Agency'), ('FILLED', 'Filled by Agency')], default='PENDING_APPROVAL', max_length=50)),
                ('approval_deadline', models.DateTimeField()),
                ('approved_by', models.CharField(blank=True, help_text="Name of approver or 'SYSTEM_AUTO_APPROVAL'", max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated cost for this shift', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escalation_log', models.JSONField(default=list, help_text='Log of all escalation actions')),
                ('preferred_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_requests', to='scheduling.agencycompany')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_requests', to='scheduling.shift')),
                ('cover_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_requests', to='scheduling.staffingcoverrequest')),
            ],
            options={
                'verbose_name': 'Agency Request',
                'verbose_name_plural': 'Agency Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sicknessabsence',
            index=models.Index(fields=['staff_member', '-reported_datetime'], name='scheduling__staff_m_18bb43_idx'),
        ),
        migrations.AddIndex(
            model_name='sicknessabsence',
            index=models.Index(fields=['status', 'is_long_term'], name='scheduling__status_4ddc83_idx'),
        ),
        migrations.AddIndex(
            model_name='sicknessabsence',
            index=models.Index(fields=['start_date', 'end_date'], name='scheduling__start_d_44c287_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingcoverrequest',
            index=models.Index(fields=['status', '-created_datetime'], name='scheduling__status_a26cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingcoverrequest',
            index=models.Index(fields=['shift', 'status'], name='scheduling__shift_i_3927c6_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingcoverrequest',
            index=models.Index(fields=['priority', 'status'], name='scheduling__priorit_be8ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='agencyrequest',
            index=models.Index(fields=['status', 'approval_deadline'], name='scheduling__status_ef03f2_idx'),
        ),
    ]
