# Generated by Django 4.2.27 on 2025-12-26 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0027_task11_feedback_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_role', models.CharField(choices=[('all', 'All Users'), ('staff', 'Staff Only'), ('management', 'Management Only'), ('senior', 'Senior Management Only')], default='all', max_length=20)),
                ('target_page', models.CharField(blank=True, help_text='URL pattern to show tip on', max_length=200)),
                ('tip_type', models.CharField(choices=[('info', 'Information'), ('tip', 'Helpful Tip'), ('warning', 'Warning'), ('success', 'Success Message')], default='tip', max_length=20)),
                ('icon', models.CharField(default='fa-lightbulb', max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTourStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(choices=[('welcome', 'Welcome Tour'), ('dashboard', 'Dashboard Tour'), ('rota', 'Rota Tour'), ('staff', 'Staff Management Tour'), ('ai', 'AI Assistant Tour'), ('mobile', 'Mobile Tips Tour')], max_length=50)),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_element', models.CharField(blank=True, max_length=200)),
                ('tooltip_position', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='bottom', max_length=10)),
                ('action_text', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tour_name', 'order', 'step_number'],
                'unique_together': {('tour_name', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_completed', models.BooleanField(default=False)),
                ('dashboard_tour_completed', models.BooleanField(default=False)),
                ('rota_tour_completed', models.BooleanField(default=False)),
                ('staff_tour_completed', models.BooleanField(default=False)),
                ('ai_intro_completed', models.BooleanField(default=False)),
                ('mobile_tips_completed', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skip_onboarding', models.BooleanField(default=False)),
                ('show_tooltips', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progress',
                'ordering': ['-created_at'],
            },
        ),
    ]
