# Generated by Django 4.2.27 on 2025-12-30 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0040_leavepattern_leaveimpactanalysis_leaveforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('DIRECT', 'Direct Message'), ('GROUP', 'Group Message'), ('SYSTEM', 'System Message'), ('ANNOUNCEMENT', 'Announcement')], default='DIRECT', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('thread_id', models.CharField(blank=True, max_length=50)),
                ('attachment_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_important', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.carehome')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='scheduling.message')),
                ('recipients', models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('related_leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.leaverequest')),
                ('related_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.shift')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('AWAY', 'Away'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('current_page', models.CharField(blank=True, max_length=200)),
                ('custom_status', models.CharField(blank=True, max_length=100)),
                ('status_emoji', models.CharField(blank=True, max_length=10)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('device_info', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'last_seen'], name='scheduling__status_e37f0e_idx'), models.Index(fields=['user', 'status'], name='scheduling__user_id_cc133e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('SHIFT_CREATED', 'Shift Created'), ('SHIFT_UPDATED', 'Shift Updated'), ('SHIFT_DELETED', 'Shift Deleted'), ('SHIFT_ASSIGNED', 'Shift Assigned'), ('LEAVE_REQUESTED', 'Leave Requested'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('SWAP_REQUESTED', 'Swap Requested'), ('SWAP_APPROVED', 'Swap Approved'), ('SWAP_REJECTED', 'Swap Rejected'), ('STAFF_ADDED', 'Staff Added'), ('STAFF_UPDATED', 'Staff Updated'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('COMPLIANCE_CHECK', 'Compliance Check'), ('REPORT_GENERATED', 'Report Generated'), ('SYSTEM_CONFIG', 'System Configuration Changed'), ('MESSAGE_SENT', 'Message Sent'), ('NOTIFICATION_CREATED', 'Notification Created')], max_length=30)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.carehome')),
                ('related_leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.leaverequest')),
                ('related_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.shift')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_about', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scheduling__user_id_b44bae_idx'), models.Index(fields=['care_home', '-created_at'], name='scheduling__care_ho_718695_idx'), models.Index(fields=['activity_type', '-created_at'], name='scheduling__activit_1acefd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SHIFT_ASSIGNED', 'Shift Assigned'), ('SHIFT_CHANGED', 'Shift Changed'), ('SHIFT_CANCELLED', 'Shift Cancelled'), ('LEAVE_APPROVED', 'Leave Request Approved'), ('LEAVE_REJECTED', 'Leave Request Rejected'), ('SWAP_REQUEST', 'Shift Swap Request'), ('SWAP_APPROVED', 'Swap Approved'), ('SWAP_REJECTED', 'Swap Rejected'), ('MESSAGE_RECEIVED', 'Message Received'), ('MENTION', 'Mentioned in Message'), ('COMPLIANCE_ALERT', 'Compliance Alert'), ('PERFORMANCE_REVIEW', 'Performance Review Due'), ('CERTIFICATION_EXPIRY', 'Certification Expiring'), ('SYSTEM_ALERT', 'System Alert')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.leaverequest')),
                ('related_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.message')),
                ('related_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.shift')),
                ('related_swap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.shiftswaprequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='scheduling__recipie_7ea415_idx'), models.Index(fields=['recipient', 'notification_type'], name='scheduling__recipie_2d8489_idx'), models.Index(fields=['priority', '-created_at'], name='scheduling__priorit_646ec7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='scheduling__sender__27d7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread_id', '-created_at'], name='scheduling__thread__244189_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', '-created_at'], name='scheduling__message_09dbb0_idx'),
        ),
    ]
