# Generated by Django 4.2.27 on 2025-12-30 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0044_apiclient_webhookendpoint_webhookdelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('metric', models.CharField(choices=[('CPU', 'CPU Usage'), ('MEMORY', 'Memory Usage'), ('DISK', 'Disk Usage'), ('ERROR_RATE', 'Error Rate'), ('RESPONSE_TIME', 'Response Time'), ('UPTIME', 'System Uptime'), ('HEALTH_CHECK', 'Health Check Failure')], max_length=50)),
                ('condition', models.CharField(choices=[('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('EQUALS', 'Equals')], max_length=20)),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_emails', models.JSONField(blank=True, default=list)),
                ('notification_interval_minutes', models.IntegerField(default=60)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['metric', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=20)),
                ('error_type', models.CharField(choices=[('EXCEPTION', 'Python Exception'), ('HTTP_ERROR', 'HTTP Error'), ('DATABASE_ERROR', 'Database Error'), ('VALIDATION_ERROR', 'Validation Error'), ('PERMISSION_ERROR', 'Permission Error'), ('TIMEOUT', 'Timeout'), ('INTEGRATION_ERROR', 'Integration Error')], max_length=50)),
                ('message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_occurred', models.DateTimeField(auto_now_add=True)),
                ('last_occurred', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('DATABASE', 'Database'), ('API', 'External API'), ('EMAIL', 'Email Service'), ('STORAGE', 'File Storage'), ('CACHE', 'Cache Service'), ('WEBHOOK', 'Webhook Endpoint'), ('CUSTOM', 'Custom Service')], max_length=50)),
                ('endpoint_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('check_interval_seconds', models.IntegerField(default=300)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('is_healthy', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('alert_after_failures', models.IntegerField(default=3)),
                ('alert_emails', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UP', 'System Up'), ('DOWN', 'System Down'), ('MAINTENANCE', 'Maintenance'), ('DEGRADED', 'Degraded Performance')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('affected_services', models.JSONField(blank=True, default=list)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('is_planned', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scheduled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('CPU', 'CPU Usage'), ('MEMORY', 'Memory Usage'), ('DISK', 'Disk Usage'), ('DATABASE', 'Database Performance'), ('RESPONSE_TIME', 'Response Time'), ('REQUEST_COUNT', 'Request Count'), ('ERROR_RATE', 'Error Rate'), ('ACTIVE_USERS', 'Active Users')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='percent', max_length=20)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='HEALTHY', max_length=20)),
                ('threshold_warning', models.FloatField(blank=True, null=True)),
                ('threshold_critical', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='scheduling__metric__9f114b_idx'), models.Index(fields=['status', '-timestamp'], name='scheduling__status_472064_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('HTTP', 'HTTP Request'), ('DATABASE', 'Database Query'), ('TASK', 'Background Task'), ('REPORT', 'Report Generation')], max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('duration_ms', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('query_count', models.IntegerField(default=1)),
                ('memory_mb', models.FloatField(blank=True, null=True)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('success', models.BooleanField()),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='scheduling.healthcheckendpoint')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='healthcheckendpoint',
            index=models.Index(fields=['is_active', 'is_healthy'], name='scheduling__is_acti_33d882_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheckendpoint',
            index=models.Index(fields=['-last_checked_at'], name='scheduling__last_ch_f8aa5e_idx'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemuptime',
            index=models.Index(fields=['status', '-started_at'], name='scheduling__status_c0702d_idx'),
        ),
        migrations.AddIndex(
            model_name='systemuptime',
            index=models.Index(fields=['is_planned', '-started_at'], name='scheduling__is_plan_259faa_idx'),
        ),
        migrations.AddIndex(
            model_name='performancelog',
            index=models.Index(fields=['log_type', '-timestamp'], name='scheduling__log_typ_2a5bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='performancelog',
            index=models.Index(fields=['endpoint', '-timestamp'], name='scheduling__endpoin_c634cf_idx'),
        ),
        migrations.AddIndex(
            model_name='performancelog',
            index=models.Index(fields=['-duration_ms'], name='scheduling__duratio_f82a89_idx'),
        ),
        migrations.AddIndex(
            model_name='performancelog',
            index=models.Index(fields=['user', '-timestamp'], name='scheduling__user_id_e9f1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheckresult',
            index=models.Index(fields=['endpoint', '-timestamp'], name='scheduling__endpoin_e8fe87_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcheckresult',
            index=models.Index(fields=['success', '-timestamp'], name='scheduling__success_45e3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['severity', '-timestamp'], name='scheduling__severit_f98c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['error_type', '-timestamp'], name='scheduling__error_t_82abad_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['is_resolved', '-timestamp'], name='scheduling__is_reso_34d08e_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['-occurrence_count'], name='scheduling__occurre_8c2ce3_idx'),
        ),
    ]
