# Generated by Django 4.2.27 on 2025-12-30 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import scheduling.models_videos


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0049_document_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order in playlist')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search and filtering', max_length=500)),
                ('video_type', models.CharField(choices=[('upload', 'Uploaded Video'), ('youtube', 'YouTube Video'), ('vimeo', 'Vimeo Video'), ('external', 'External Link')], default='upload', max_length=20)),
                ('video_file', models.FileField(blank=True, help_text='Upload video file (MP4, WebM, OGG, MOV, AVI)', null=True, upload_to=scheduling.models_videos.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg', 'mov', 'avi'])])),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, help_text='Custom thumbnail image (auto-generated if not provided)', null=True, upload_to=scheduling.models_videos.thumbnail_upload_path)),
                ('duration', models.IntegerField(blank=True, help_text='Video duration in seconds', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes (for uploaded videos)', null=True)),
                ('access_level', models.CharField(choices=[('public', 'Public - All users'), ('staff', 'Staff - All authenticated staff'), ('managers', 'Managers - Managers only'), ('trainers', 'Trainers - Training coordinators only'), ('custom', 'Custom - Specific users/roles')], default='staff', max_length=20)),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='Roles with access to this video (for custom access level)')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Is this video mandatory for completion?')),
                ('completion_threshold', models.IntegerField(default=90, help_text='Percentage of video that must be watched to mark as complete', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('completion_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users with access to this video (for custom access level)', related_name='accessible_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Public playlists visible to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Users with access to this playlist', related_name='shared_playlists', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_playlists', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(related_name='playlists', through='scheduling.PlaylistVideo', to='scheduling.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-folder', help_text='FontAwesome icon class (e.g., fa-folder, fa-video)', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for category badge', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='scheduling.videocategory')),
            ],
            options={
                'verbose_name_plural': 'Video Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='scheduling.videocategory'),
        ),
        migrations.AddField(
            model_name='video',
            name='training_module',
            field=models.ForeignKey(blank=True, help_text='Link to training course for integration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_videos', to='scheduling.trainingcourse'),
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.videoplaylist'),
        ),
        migrations.AddField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.video'),
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_ratings', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='scheduling.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video', '-created_at'], name='scheduling__video_i_c857b4_idx'), models.Index(fields=['user', '-created_at'], name='scheduling__user_id_aba8bb_idx')],
                'unique_together': {('video', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_time', models.IntegerField(default=0, help_text='Total seconds watched (excluding rewinds)')),
                ('last_position', models.IntegerField(default=0, help_text='Last watched position in seconds')),
                ('progress_percentage', models.IntegerField(default=0, help_text='Percentage of video watched', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='scheduling.video')),
            ],
            options={
                'ordering': ['-last_watched_at'],
                'indexes': [models.Index(fields=['user', '-last_watched_at'], name='scheduling__user_id_a2afeb_idx'), models.Index(fields=['video', 'is_completed'], name='scheduling__video_i_db5f5f_idx'), models.Index(fields=['user', 'is_completed'], name='scheduling__user_id_3f7c11_idx')],
                'unique_together': {('video', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='videoplaylist',
            index=models.Index(fields=['user', '-created_at'], name='scheduling__user_id_042a03_idx'),
        ),
        migrations.AddIndex(
            model_name='videoplaylist',
            index=models.Index(fields=['is_public', '-created_at'], name='scheduling__is_publ_29f05c_idx'),
        ),
        migrations.AddIndex(
            model_name='videocategory',
            index=models.Index(fields=['parent', 'order'], name='scheduling__parent__c71d89_idx'),
        ),
        migrations.AddIndex(
            model_name='videocategory',
            index=models.Index(fields=['is_active', 'order'], name='scheduling__is_acti_b0acb9_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category', '-created_at'], name='scheduling__categor_3604f6_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_published', '-created_at'], name='scheduling__is_publ_225302_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured', '-created_at'], name='scheduling__is_feat_8e953c_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['training_module', 'is_published'], name='scheduling__trainin_81e6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='playlistvideo',
            index=models.Index(fields=['playlist', 'order'], name='scheduling__playlis_5ca092_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistvideo',
            unique_together={('playlist', 'video')},
        ),
    ]
