# Generated by Django 4.2.27 on 2026-01-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('sendgrid', 'SendGrid'), ('microsoft365', 'Microsoft 365 / Outlook'), ('custom', 'Custom SMTP Server')], default='custom', help_text='Select your email provider. This will auto-fill common settings.', max_length=20)),
                ('host', models.CharField(help_text='SMTP server hostname (e.g., smtp.gmail.com, smtp.sendgrid.net)', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL, 25 for unencrypted)')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption (recommended for port 587)')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption (for port 465). Do not use with TLS.')),
                ('username', models.EmailField(help_text='SMTP username (usually your email address)', max_length=254)),
                ('password', models.CharField(help_text='SMTP password or app password (will be encrypted in database)', max_length=512)),
                ('from_email', models.EmailField(help_text='Default "From" email address (e.g., noreply@yourdomain.com)', max_length=254)),
                ('is_active', models.BooleanField(default=False, help_text='Only one configuration can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_test_date', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_test_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
