# Generated by Django 5.2.7 on 2025-10-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_records', '0003_sicknessrecord_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicknessrecord',
            name='estimated_return_to_work',
            field=models.DateField(blank=True, help_text='Expected return-to-work date.', null=True),
        ),
        migrations.AlterField(
            model_name='sicknessrecord',
            name='first_working_day',
            field=models.DateField(help_text='First working day absent due to sickness.'),
        ),
    ]
