# Generated by Django 5.2.7 on 2025-11-27 23:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_compliancerule_compliancecheck_complianceviolation_and_more'),
        ('staff_records', '0004_alter_sicknessrecord_estimated_return_to_work_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_year_start', models.DateField(help_text='Start date of this leave year (e.g., 1st April 2025)')),
                ('leave_year_end', models.DateField(help_text='End date of this leave year (e.g., 31st March 2026)')),
                ('total_entitlement_hours', models.DecimalField(decimal_places=2, help_text='Total annual leave entitlement in hours (e.g., 196 hours = 28 days × 7 hours)', max_digits=6)),
                ('contracted_hours_per_week', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Contracted working hours per week for pro-rata calculations', max_digits=5)),
                ('hours_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total hours of leave used (approved requests)', max_digits=6)),
                ('hours_pending', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total hours in pending requests', max_digits=6)),
                ('hours_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hours remaining = entitlement - used - pending', max_digits=6)),
                ('carryover_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hours carried over from previous leave year', max_digits=6)),
                ('carryover_expiry_date', models.DateField(blank=True, help_text='Date by which carried over leave must be used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_entitlements', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='staff_records.staffprofile')),
            ],
            options={
                'ordering': ['-leave_year_start'],
                'unique_together': {('profile', 'leave_year_start')},
            },
        ),
        migrations.CreateModel(
            name='AnnualLeaveTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INITIAL', 'Initial Entitlement'), ('ADJUSTMENT', 'Manual Adjustment'), ('CARRYOVER', 'Carryover from Previous Year'), ('DEDUCTION', 'Leave Request Deduction'), ('REFUND', 'Leave Request Cancelled/Denied'), ('CORRECTION', 'Error Correction')], max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours added (positive) or deducted (negative)', max_digits=6)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Hours remaining after this transaction', max_digits=6)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the request was approved (for DEDUCTION transactions)', null=True)),
                ('description', models.TextField(help_text='Description of this transaction for audit purposes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this transaction was recorded')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_transactions', to=settings.AUTH_USER_MODEL)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_transactions', to='staff_records.annualleaveentitlement')),
                ('related_request', models.ForeignKey(blank=True, help_text='Link to the leave request that triggered this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_transactions', to='scheduling.leaverequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SicknessAbsenceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Calendar year for this summary')),
                ('total_absence_days', models.IntegerField(default=0, help_text='Total working days lost to sickness in this year')),
                ('total_absence_instances', models.IntegerField(default=0, help_text='Number of separate sickness episodes in this year')),
                ('bradford_factor_score', models.IntegerField(default=0, help_text='Bradford Factor = Instances² × Total Days')),
                ('rolling_12m_days', models.IntegerField(default=0, help_text='Total days lost in last 12 months from end of this year')),
                ('rolling_12m_instances', models.IntegerField(default=0, help_text='Number of instances in last 12 months')),
                ('rolling_12m_bradford', models.IntegerField(default=0, help_text='Bradford Factor for rolling 12 months')),
                ('trigger_level_reached', models.BooleanField(default=False, help_text='True if Bradford Factor exceeds threshold (usually 200)')),
                ('trigger_threshold', models.IntegerField(default=200, help_text='Bradford Factor threshold for formal review')),
                ('formal_review_conducted', models.BooleanField(default=False)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_outcome', models.TextField(blank=True)),
                ('support_plan_in_place', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sickness_summaries', to='staff_records.staffprofile')),
            ],
            options={
                'ordering': ['-year', 'profile__user__last_name'],
                'unique_together': {('profile', 'year')},
            },
        ),
    ]
