# Generated by Django 4.2.27 on 2026-01-15 12:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('policy_number', models.CharField(help_text='Unique policy identifier (e.g., POL-001)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('clinical', 'Clinical Care'), ('operational', 'Operational'), ('hr', 'Human Resources'), ('health_safety', 'Health & Safety'), ('safeguarding', 'Safeguarding'), ('infection_control', 'Infection Prevention & Control'), ('quality', 'Quality Assurance'), ('regulatory', 'Regulatory Compliance'), ('finance', 'Finance & Business'), ('it_data', 'IT & Data Protection')], max_length=30)),
                ('effective_date', models.DateField(help_text='Date policy becomes effective')),
                ('next_review_date', models.DateField(help_text='Date policy must be reviewed')),
                ('review_frequency_months', models.PositiveIntegerField(default=12, help_text='Review frequency in months', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('active', 'Active'), ('archived', 'Archived'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('version', models.DecimalField(decimal_places=1, default=1.0, help_text='Current version number (e.g., 1.0, 2.5)', max_digits=4)),
                ('summary', models.TextField(help_text='Brief summary of policy scope and purpose')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search', max_length=500)),
                ('regulatory_framework', models.TextField(blank=True, help_text='CQC/Care Inspectorate references and regulatory requirements')),
                ('department', models.CharField(blank=True, help_text='Responsible department', max_length=100)),
                ('file_path', models.FileField(blank=True, help_text='Policy document file (PDF/Word)', upload_to='policies/')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Requires staff acknowledgement')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Policy author/owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['-effective_date', 'policy_number'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('procedure_number', models.CharField(help_text='Unique procedure identifier (e.g., PROC-001)', max_length=50, unique=True)),
                ('steps', models.TextField(help_text='Detailed step-by-step instructions')),
                ('equipment_required', models.TextField(blank=True, help_text='Equipment or materials needed')),
                ('safety_notes', models.TextField(blank=True, help_text='Safety precautions and warnings')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(help_text='Parent policy', on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='policies_procedures.policy')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedure',
                'verbose_name_plural': 'Procedures',
                'ordering': ['procedure_number'],
            },
        ),
        migrations.CreateModel(
            name='PolicyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('review_outcome', models.CharField(choices=[('no_changes', 'No Changes Required'), ('minor_updates', 'Minor Updates'), ('major_revision', 'Major Revision Required'), ('retire', 'Retire Policy')], max_length=20)),
                ('recommendations', models.TextField(help_text='Reviewer recommendations and findings')),
                ('next_review_date', models.DateField(help_text='Recommended next review date')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_policy_reviews', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='policies_procedures.policy')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Review',
                'verbose_name_plural': 'Policy Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='PolicyComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('compliance_status', models.CharField(choices=[('fully_compliant', 'Fully Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable')], max_length=25)),
                ('findings', models.TextField(help_text='Detailed compliance findings')),
                ('actions_required', models.TextField(blank=True, help_text='Actions needed to achieve compliance')),
                ('due_date', models.DateField(blank=True, help_text='Date actions must be completed', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('checker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_compliance_checks', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='policies_procedures.policy')),
            ],
            options={
                'verbose_name': 'Policy Compliance Check',
                'verbose_name_plural': 'Policy Compliance Checks',
                'ordering': ['-check_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('reviewed', 'Reviewed'), ('acknowledged', 'Acknowledged'), ('archived', 'Archived'), ('superseded', 'Superseded'), ('compliance_check', 'Compliance Check')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(help_text='Description of action performed')),
                ('previous_values', models.JSONField(blank=True, help_text='Previous field values (for updates)', null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='policies_procedures.policy')),
            ],
            options={
                'verbose_name': 'Audit Trail Entry',
                'verbose_name_plural': 'Audit Trail',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Step sequence number')),
                ('description', models.TextField(help_text='Detailed step description')),
                ('critical_point', models.BooleanField(default=False, help_text='Critical control point requiring verification')),
                ('evidence_required', models.CharField(blank=True, help_text='Evidence or documentation required', max_length=200)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_steps', to='policies_procedures.procedure')),
            ],
            options={
                'verbose_name': 'Procedure Step',
                'verbose_name_plural': 'Procedure Steps',
                'ordering': ['procedure', 'step_number'],
                'unique_together': {('procedure', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.DecimalField(decimal_places=1, help_text='Version number (e.g., 1.0, 2.5)', max_digits=4)),
                ('change_summary', models.TextField(help_text='Summary of changes in this version')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(help_text='Archived version of policy document', upload_to='policies/versions/')),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current active version?')),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_versions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policies_procedures.policy')),
            ],
            options={
                'verbose_name': 'Policy Version',
                'verbose_name_plural': 'Policy Versions',
                'ordering': ['-version_number'],
                'unique_together': {('policy', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_date', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(help_text='Digital signature or name', max_length=200)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address for audit trail')),
                ('acknowledgement_method', models.CharField(choices=[('digital', 'Digital Signature'), ('paper', 'Paper Form'), ('verbal', 'Verbal Confirmation'), ('training', 'Training Session')], default='digital', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Staff comments or questions')),
                ('is_overdue', models.BooleanField(default=False, help_text='Acknowledgement was required but not completed on time')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='policies_procedures.policy')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Acknowledgement',
                'verbose_name_plural': 'Policy Acknowledgements',
                'ordering': ['-acknowledged_date'],
                'indexes': [models.Index(fields=['policy', 'acknowledged_date'], name='policies_pr_policy__d5f5fb_idx'), models.Index(fields=['staff_member', 'acknowledged_date'], name='policies_pr_staff_m_3aebda_idx')],
                'unique_together': {('policy', 'staff_member')},
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_pr_policy__3f2e17_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['category', 'status'], name='policies_pr_categor_d9a2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['next_review_date'], name='policies_pr_next_re_c26931_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['policy', '-timestamp'], name='policies_pr_policy__9df9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action_type', '-timestamp'], name='policies_pr_action__4baf11_idx'),
        ),
    ]
