"""
Django settings for rotasystems project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
try:
    from celery.schedules import crontab
except ImportError:
    crontab = None
from decouple import config, Csv

# Detect if we're running tests
TESTING = 'test' in sys.argv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from environment variable for security
# In test/CI environments, use a default insecure key
SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-key-j8k2m9n4p5q6r7s8t9u0v1w2x3y4z5a6b7c8d9e0f1g2h3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Load allowed hosts from environment (comma-separated list)
# For PWA testing: Allow local network access for mobile testing
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='demo.therota.co.uk,localhost,127.0.0.1,192.168.1.125', cast=Csv())

# For development: Allow all local network IPs
if DEBUG:
    ALLOWED_HOSTS.append('*')  # Allow all hosts in debug mode for mobile testing


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',  # Task 38: Token auth for mobile API
    'corsheaders',
    'django_celery_beat',  # Celery Beat for periodic tasks
    # Phase 6: Security & ML apps
    'axes',  # Account lockout protection
    'auditlog',  # Audit logging for compliance
    # Task 48: Two-Factor Authentication
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',  # Backup codes
    # Core apps
    'scheduling',
    'scheduling.management',
    'staff_records',
    'rotasystems.core',
    'email_config',  # UI-based email configuration
    # TQM Module 1: Quality Audits & Inspections
    'quality_audits',  # PDSA Tracker, Audit Templates, CAPA System
    # TQM Module 2: Incident & Safety Management
    'incident_safety',  # RCA, CAPA, Duty of Candour, Trend Analysis
    # TQM Module 3: Experience & Feedback
    'experience_feedback',  # Satisfaction Surveys, Complaints, EBCD, QoL Assessments
    # TQM Module 4: Training & Competency
    'training_competency.apps.TrainingCompetencyConfig',  # Competency Frameworks, Skills Matrix, Learning Pathways
    # TQM Module 5: Policies & Procedures
    'policies_procedures',  # Policy Lifecycle, Version Control, Digital Acknowledgements, Compliance Tracking
    # TQM Module 5 (Legacy): Document & Policy Management
    'document_management',  # Document Repository, Version Control, Policy Lifecycle, Staff Acknowledgements
    # TQM Module 6: Risk Management
    'risk_management',  # Risk Register, Risk Assessment (5x5 Matrix), Mitigation Planning, Risk Reviews
    # TQM Module 7: Performance Metrics & KPIs
    'performance_kpis',  # KPI Library, Executive Dashboards, Balanced Scorecard
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Performance: Compress responses
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Task 37: Language detection
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # Task 48: 2FA verification
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Phase 6: Security middleware
    'axes.middleware.AxesMiddleware',  # Account lockout protection
    'csp.middleware.CSPMiddleware',  # Content Security Policy
    # Custom middleware
    'scheduling.middleware.AuditLoggingMiddleware',  # Automatic audit logging
]

ROOT_URLCONF = 'rotasystems.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,  # Must be False when using custom loaders
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'scheduling.context_processors.system_mode',  # Add DEMO/PRODUCTION mode indicator
            ],
            # Performance: Cache compiled templates in production
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ] if not DEBUG else [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = 'rotasystems.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Load database configuration from environment
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.sqlite3':
    # SQLite configuration (development)
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
        }
    }
else:
    # PostgreSQL or other database (production)
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
            # Performance: Connection pooling settings
            'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
            'OPTIONS': {
                'connect_timeout': 10,
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# Phase 6: Enhanced password security following NCSC guidance & Scottish Design (usability)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 10,  # Scottish Design: Balance security with usability (reduced from 12)
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Phase 6: Django-Axes Configuration (Account Lockout Protection)
# Scottish Design: Balance security with 24/7 care operations
# Note: AUTHENTICATION_BACKENDS configured below with SAP backend (line ~336)

AXES_FAILURE_LIMIT = 5  # Lock account after 5 failed attempts
AXES_COOLOFF_TIME = 1  # Lockout for 1 hour (in hours)
AXES_RESET_ON_SUCCESS = True  # Reset counter on successful login
AXES_LOCKOUT_TEMPLATE = 'lockout.html'  # Custom lockout page
AXES_VERBOSE = True  # Log lockout attempts for monitoring

# Phase 6: Session Security
# Scottish Design: 1-hour timeout for healthcare compliance
SESSION_COOKIE_AGE = 3600  # 1 hour (3600 seconds)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax')  # Changed from Strict to prevent logout CSRF issues, but allow override for tests
SESSION_SAVE_EVERY_REQUEST = True  # Update expiry on every request

# Phase 6: CSRF Protection
# PWA Compatibility: Allow JavaScript access to CSRF token for fetch requests
CSRF_COOKIE_SECURE = not DEBUG  # HTTPS only in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for PWA/AJAX (was True)
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='https://demo.therota.co.uk,http://192.168.1.125:8000,http://localhost:8000,http://localhost:8001,http://127.0.0.1:8001', cast=Csv())

# Phase 6: Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking

# Phase 6: HTTPS/SSL Settings (Production only)
# For production (not DEBUG and not TESTING), enable full HSTS
if not DEBUG and not TESTING:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    # Development/Testing: Disable HSTS to allow local HTTP testing
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Phase 6: Content Security Policy
CSP_DEFAULT_SRC = ["'self'"]
CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://code.jquery.com"]
CSP_STYLE_SRC = ["'self'", "'unsafe-inline'", "https://cdn.jsdelivr.net", "https://stackpath.bootstrapcdn.com"]
CSP_IMG_SRC = ["'self'", "data:", "https:"]
CSP_FONT_SRC = ["'self'", "https://cdn.jsdelivr.net", "https://stackpath.bootstrapcdn.com"]
CSP_CONNECT_SRC = ["'self'"]
CSP_FRAME_ANCESTORS = ["'none'"]  # Prevent embedding in iframes

# Phase 6: Field Encryption Key (for sensitive data)
# Scottish Design: Privacy by design
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY', default=None)

# Phase 6: Production Logging Configuration
# Scottish Design: Transparency and accountability
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'filters': {
            'require_debug_false': {
                '()': 'django.utils.log.RequireDebugFalse',
            },
        },
        'handlers': {
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
            'file': {
                'level': 'INFO',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': config('LOG_FILE', default='/var/log/rota/django.log'),
                'maxBytes': 1024 * 1024 * 15,  # 15MB
                'backupCount': 10,
                'formatter': 'verbose',
            },
            'security': {
                'level': 'WARNING',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': config('SECURITY_LOG_FILE', default='/var/log/rota/security.log'),
                'maxBytes': 1024 * 1024 * 10,  # 10MB
                'backupCount': 20,
                'formatter': 'verbose',
            },
            'mail_admins': {
                'level': 'ERROR',
                'class': 'django.utils.log.AdminEmailHandler',
                'filters': ['require_debug_false'],
                'formatter': 'verbose',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': True,
            },
            'django.request': {
                'handlers': ['file', 'mail_admins'],
                'level': 'ERROR',
                'propagate': False,
            },
            'django.security': {
                'handlers': ['security'],
                'level': 'WARNING',
                'propagate': False,
            },
            'axes': {
                'handlers': ['security'],
                'level': 'INFO',
                'propagate': False,
            },
            'auditlog': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }
else:
    # Development logging - console only
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }

# Phase 6: Admin Email Notifications for Production Errors
ADMINS = [
    ('IT Support', config('ADMIN_EMAIL', default='itsupport@orchardgrove.com')),
]
MANAGERS = ADMINS


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Task 37: Multi-language Support Configuration
LANGUAGE_CODE = 'en-gb'  # Default language (British English for UK care homes)

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('gd', 'Scottish Gaelic'),
    ('cy', 'Welsh'),
    ('pl', 'Polish'),
    ('ro', 'Romanian'),
    ('es', 'Spanish'),
    ('ar', 'Arabic'),
    ('ur', 'Urdu'),
    ('zh-hans', 'Simplified Chinese'),
]

# Path to locale files for translations
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Europe/London'  # UK timezone for Glasgow HSCP

USE_I18N = True  # Enable internationalization
USE_L10N = True  # Enable localized formatting
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Performance: Django Caching Configuration
# Use Redis in production, in-memory cache for development
if not DEBUG and config('REDIS_URL', default=None):
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': config('REDIS_URL'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {'max_connections': 50},
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'PARSER_CLASS': 'redis.connection.PythonParser',
                'PICKLE_VERSION': -1,  # Use latest pickle protocol
            },
            'KEY_PREFIX': 'rota',
            'TIMEOUT': 300,  # Default 5 minutes
        }
    }
else:
    # Development: Use local memory cache (fast, no Redis needed)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 1000
            }
        }
    }

# Performance: Cache aliases for different use cases
CACHES['template_fragments'] = {
    **CACHES['default'],
    'TIMEOUT': 900,  # 15 minutes for template fragments
}

CACHES['static_data'] = {
    **CACHES['default'],
    'TIMEOUT': 3600,  # 1 hour for relatively static data (homes, roles)
}

CACHES['dashboard'] = {
    **CACHES['default'],
    'TIMEOUT': 300,  # 5 minutes for dashboard data
}
STATIC_URL = 'static/'
STATIC_ROOT = config('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))

MEDIA_URL = '/media/'
MEDIA_ROOT = config('MEDIA_ROOT', default=str(BASE_DIR / 'media'))

# Organize uploads by type
TRAINING_CERTIFICATES_DIR = 'training/certificates/'
INCIDENT_PHOTOS_DIR = 'incidents/photos/'
BODY_MAPS_DIR = 'incidents/body_maps/'
DOCUMENTS_DIR = 'documents/'  # Task 53: Document Management System

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'scheduling.User'

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # Account lockout protection (renamed from AxesBackend in v5.0+)
    'scheduling.backends.SAPAuthenticationBackend',  # SAP number authentication
    'django.contrib.auth.backends.ModelBackend',  # Django default
]

# REST Framework Configuration
# Task 38: Enhanced with token authentication for mobile app
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # For mobile apps
        'rest_framework.authentication.SessionAuthentication',  # For web
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS Settings (for frontend development)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://127.0.0.1:3000",
]

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Time Zone
TIME_ZONE = 'Europe/London'

# Django-Q Configuration
Q_CLUSTER = {
    'name': 'rotasystem',
    'workers': 4,
    'recycle': 500,
    'timeout': 300,
    'compress': True,
    'save_limit': 250,
    'queue_limit': 500,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'redis': {
        'host': '127.0.0.1',
        'port': 6379,
        'db': 0,
        'password': None,
        'socket_timeout': None,
        'charset': 'utf-8',
        'errors': 'strict',
        'unix_socket_path': None,
    }
}

# ===== Email Configuration =====
# Priority: 1) Database UI config, 2) Environment variables, 3) Console backend
# Allows HSCP administrators to configure email via Django admin UI

# Try database configuration first (UI-based setup)
try:
    from email_config.models import EmailConfiguration
    active_config = EmailConfiguration.objects.filter(is_active=True).first()
    
    if active_config:
        # Use database configuration (configured via admin UI)
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = active_config.host
        EMAIL_PORT = active_config.port
        EMAIL_USE_TLS = active_config.use_tls
        EMAIL_USE_SSL = active_config.use_ssl
        EMAIL_HOST_USER = active_config.username
        EMAIL_HOST_PASSWORD = active_config.get_decrypted_password()
        DEFAULT_FROM_EMAIL = active_config.from_email
        SERVER_EMAIL = active_config.from_email
    elif os.environ.get('EMAIL_HOST'):
        # Fallback to environment variables (legacy .env configuration)
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = os.environ.get('EMAIL_HOST')
        EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
        EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
        EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
        EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
        EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
        DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'Staff Rota System <{EMAIL_HOST_USER}>')
        SERVER_EMAIL = DEFAULT_FROM_EMAIL
    else:
        # Development/Testing - Console backend (emails print to terminal)
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        DEFAULT_FROM_EMAIL = 'Staff Rota System <webmaster@localhost>'
        SERVER_EMAIL = DEFAULT_FROM_EMAIL
except Exception as e:
    # Database not ready (migrations pending) or other error
    # Fallback to environment variables or console
    if os.environ.get('EMAIL_HOST'):
        EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        EMAIL_HOST = os.environ.get('EMAIL_HOST')
        EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
        EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
        EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() == 'true'
        EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
        EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
        DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'Staff Rota System <{EMAIL_HOST_USER}>')
        SERVER_EMAIL = DEFAULT_FROM_EMAIL
    else:
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        DEFAULT_FROM_EMAIL = 'Staff Rota System <webmaster@localhost>'
        SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email timeout settings
EMAIL_TIMEOUT = 30  # seconds

# ===== Email Configuration Guide =====
# 
# GMAIL SETUP:
# 1. Go to https://myaccount.google.com/apppasswords
# 2. Generate an "App Password" (16-character password)
# 3. Set environment variables:
#    export EMAIL_HOST="smtp.gmail.com"
#    export EMAIL_PORT="587"
#    export EMAIL_USER="your-email@gmail.com"
#    export EMAIL_PASSWORD="abcd efgh ijkl mnop"  # App password
#    export DEFAULT_FROM_EMAIL="Staff Rota System <your-email@gmail.com>"
#
# OFFICE 365 SETUP:
# 1. Use your Office 365 credentials
# 2. Set environment variables:
#    export EMAIL_HOST="smtp.office365.com"
#    export EMAIL_PORT="587"
#    export EMAIL_USER="your-email@company.com"
#    export EMAIL_PASSWORD="your-password"
#    export DEFAULT_FROM_EMAIL="Staff Rota System <your-email@company.com>"
#
# Add to ~/.zshrc or ~/.bash_profile to persist across sessions
# EMAIL_USE_TLS = True  # or EMAIL_USE_SSL = True for port 465
# EMAIL_HOST_USER = 'your-email@yourserver.com'
# EMAIL_HOST_PASSWORD = 'your-password'
# DEFAULT_FROM_EMAIL = 'Staff Rota System <your-email@yourserver.com>'

# ===== Compliance Notification Recipients =====
# Replace with actual email addresses of people who should receive alerts
COMPLIANCE_NOTIFICATION_EMAILS = [
    'manager@example.com',  # Replace with actual manager email
    # 'compliance@example.com',  # Add more recipients as needed
    # 'seniormanager@example.com',
]

# ===== Site URL =====
# Used in email links - update when deploying to production
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# ===== Task 21: Email Notification Settings =====
# Frequency for automated email tasks
EMAIL_SHIFT_REMINDER_HOURS = 24  # Send reminders X hours before shift
EMAIL_WEEKLY_ROTA_DAY = 6  # 0=Monday, 6=Sunday
EMAIL_WEEKLY_ROTA_HOUR = 18  # 18:00 (6 PM)

# ===== Task 22: SMS Notification Settings (Twilio) =====
# Enable/disable SMS globally (requires Twilio account)
TWILIO_ENABLED = config('TWILIO_ENABLED', default=False, cast=bool)

# Twilio credentials (load from environment variables for security)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')  # E.164 format: +447700900123

# SMS notification settings
SMS_MAX_LENGTH = 160  # Standard SMS length
SMS_EMERGENCY_ENABLED = True  # Always allow emergency SMS even if user opted out
SMS_RATE_LIMIT_PER_USER_HOUR = 5  # Max SMS per user per hour (prevent spam)

# ===== Security Settings =====
# Note: Core security settings (HSTS, SSL, cookies) are configured earlier in this file
# They are properly set based on DEBUG mode for development vs production

# Database Connection Pooling (production)
CONN_MAX_AGE = config('CONN_MAX_AGE', default=0, cast=int)

# ===== Logging Configuration =====
if not DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} {module} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'ERROR',
                'class': 'logging.FileHandler',
                'filename': BASE_DIR / 'logs' / 'django_errors.log',
                'formatter': 'verbose',
            },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'verbose',
            },
        },
        'root': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'loggers': {
            'django': {
                'handlers': ['console', 'file'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

# ===== Automated Staffing Workflow Configuration =====
STAFFING_WORKFLOW = {
    # Timeouts and deadlines
    'OT_RESPONSE_WINDOW_HOURS': 1,  # Staff have 1 hour to respond to OT offers
    'AGENCY_APPROVAL_TIMEOUT_MINUTES': 15,  # Senior Officer has 15 minutes to approve agency
    
    # Long-term absence detection
    'LONG_TERM_SHIFT_THRESHOLD': 3,  # ≥3 shifts triggers long-term planning
    'LONG_TERM_DAY_THRESHOLD': 5,    # OR ≥5 days triggers long-term planning
    
    # OT priority weights (must sum to 100)
    'OT_PRIORITY_WEIGHTS': {
        'FAIR_ROTATION': 50,      # 50% weight for fair distribution
        'QUALIFICATION': 30,      # 30% weight for qualifications/experience
        'PROXIMITY': 20,          # 20% weight for travel distance/time
    },
    
    # WTD (Working Time Directive) compliance
    'WTD_MAX_HOURS_PER_WEEK': 48,     # Maximum 48 hours per week
    'WTD_MIN_REST_HOURS': 11,          # Minimum 11 hours rest between shifts
    'WTD_ROLLING_WEEKS': 17,           # Calculate average over 17 weeks
    
    # Reallocation search parameters
    'REALLOCATION_MAX_TRAVEL_MINUTES': 30,  # Maximum 30-minute travel time
    'REALLOCATION_PRIORITY_ORDER': [
        'same_qualification',
        'higher_qualification',
        'willing_to_travel',
    ],
    
    # Escalation configuration
    'ESCALATION_SENIOR_OFFICER_EMAIL': 'senior.officer@orchard-grove.co.uk',
    'ESCALATION_SENIOR_OFFICER_PHONE': '+447700900123',  # Update with real number
    'AUTO_APPROVE_ON_TIMEOUT': True,  # Auto-approve agency after 15-min timeout
    
    # Notification preferences
    'ENABLE_SMS_NOTIFICATIONS': True,
    'ENABLE_EMAIL_NOTIFICATIONS': True,
    'ENABLE_PUSH_NOTIFICATIONS': False,  # Not yet implemented
    
    # Cost tracking
    'AGENCY_HOURLY_RATE_MULTIPLIER': 1.8,  # Agency costs 1.8x regular rate
    'OT_HOURLY_RATE_MULTIPLIER': 1.5,       # OT costs 1.5x regular rate
    
    # Budget limits (monthly, per care home)
    'MONTHLY_AGENCY_BUDGET': 9000,    # £9,000 per month per home
    'MONTHLY_OT_BUDGET': 5000,        # £5,000 per month per home
    
    # Process optimization
    'CONCURRENT_REALLOCATION_AND_OT': True,  # Run Priority 1 & 2 simultaneously
    'MAX_OT_OFFERS_PER_BATCH': 20,           # Maximum staff to offer OT per batch
    'REALLOCATION_SEARCH_RADIUS_KM': 15,     # Search within 15km for reallocation
}

# Senior Officer contact details
SENIOR_OFFICER_EMAIL = STAFFING_WORKFLOW['ESCALATION_SENIOR_OFFICER_EMAIL']
SENIOR_OFFICER_PHONE = STAFFING_WORKFLOW['ESCALATION_SENIOR_OFFICER_PHONE']

# HR department contact
HR_EMAIL = 'hr@orchard-grove.co.uk'

# Base URL for notification links (update for production)
BASE_URL = config('BASE_URL', default='http://localhost:8000')


# ==================== Celery Configuration ====================
# Automated workflow monitoring tasks

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Change for production
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ==================== Celery Configuration ====================
# Automated workflow monitoring tasks
# NOTE: Install celery and redis to enable these features:
# pip install celery redis django-celery-beat

try:
    from celery.schedules import crontab
    CELERY_AVAILABLE = True
except ImportError:
    CELERY_AVAILABLE = False

if CELERY_AVAILABLE:
    CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Change for production
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'Europe/London'
    
    # Celery Beat schedule for periodic tasks
    CELERY_BEAT_SCHEDULE = {
        'monitor-ot-deadlines': {
            'task': 'scheduling.tasks.monitor_ot_offer_deadlines',
            'schedule': 60.0,  # Every 1 minute
            'options': {'expires': 50}
        },
        'monitor-agency-approvals': {
            'task': 'scheduling.tasks.monitor_agency_approval_deadlines',
            'schedule': 60.0,  # Every 1 minute
            'options': {'expires': 50}
        },
        'monitor-reallocation-deadlines': {
            'task': 'scheduling.tasks.monitor_reallocation_deadlines',
            'schedule': 60.0,  # Every 1 minute
            'options': {'expires': 50}
        },
        'workflow-health-check': {
            'task': 'scheduling.tasks.monitor_workflow_health',
            'schedule': 300.0,  # Every 5 minutes
            'options': {'expires': 250}
        },
        'post-shift-admin-reminders': {
            'task': 'scheduling.tasks.send_post_shift_admin_reminders',
            'schedule': crontab(hour=9, minute=0),  # Daily at 09:00
        },
        'long-term-absence-review': {
            'task': 'scheduling.tasks.review_long_term_absences',
            'schedule': crontab(hour=8, minute=0),  # Daily at 08:00
        },
        'wdt-compliance-monitoring': {
            'task': 'scheduling.tasks.monitor_wdt_compliance',
            'schedule': crontab(day_of_week=0, hour=20, minute=0),  # Sundays at 20:00
        },
        # Task 21: Email Notification Schedules
        'send-shift-reminders': {
            'task': 'scheduling.tasks.send_shift_reminders',
            'schedule': 3600.0,  # Every hour
            'options': {'expires': 3500}
        },
        'send-weekly-rotas': {
            'task': 'scheduling.tasks.send_weekly_rotas',
            'schedule': crontab(day_of_week=6, hour=18, minute=0),  # Sundays at 18:00
        },
        # Task 22: SMS Notification Schedules
        'monitor-late-clockins': {
            'task': 'scheduling.tasks.monitor_late_clockins',
            'schedule': 900.0,  # Every 15 minutes
            'options': {'expires': 850}
        },
        'send-emergency-coverage-sms': {
            'task': 'scheduling.tasks.send_emergency_coverage_sms',
            'schedule': 1800.0,  # Every 30 minutes
            'options': {'expires': 1750}
        },
        'weekly-workflow-report': {
            'task': 'scheduling.tasks.generate_weekly_workflow_report',
            'schedule': crontab(day_of_week=1, hour=9, minute=0),  # Mondays at 09:00
        },
        # Task 47: Email Notification Queue - Daily & Weekly Schedules
        'daily-shift-reminders': {
            'task': 'scheduling.tasks.send_daily_shift_reminders',
            'schedule': crontab(hour=18, minute=0),  # Daily at 18:00
            'options': {'expires': 3500}
        },
        'weekly-schedule-summary': {
            'task': 'scheduling.tasks.send_weekly_schedule_summary',
            'schedule': crontab(day_of_week=0, hour=18, minute=0),  # Sundays at 18:00
            'options': {'expires': 3500}
        },
    }

# ===== Task 48: Two-Factor Authentication Settings =====

# OTP (One-Time Password) Settings
OTP_TOTP_ISSUER = 'Staff Rota System'  # Displayed in authenticator apps

# Session timeout for 2FA verification (optional)
# User must re-verify 2FA after this period
OTP_SESSION_TIMEOUT = 86400  # 24 hours (in seconds)

# Roles that require mandatory 2FA
REQUIRED_2FA_ROLES = [
    'is_staff',  # Django staff users
    'is_superuser',  # Django superusers
    'Manager',  # Staff with Manager role
]

# ===== Task 49: Elasticsearch Configuration =====
# Disabled in production - only enabled for local development with ES installed
# Enable Elasticsearch only if DEBUG=True and ES is available
if DEBUG and os.environ.get('ENABLE_ELASTICSEARCH', 'false').lower() == 'true':
    INSTALLED_APPS.append('django_elasticsearch_dsl')
    # Elasticsearch DSL settings
    ELASTICSEARCH_DSL = {
        'default': {
            'hosts': os.environ.get('ELASTICSEARCH_URL', 'http://localhost:9200'),
            'http_auth': (
                os.environ.get('ELASTICSEARCH_USER', ''),
                os.environ.get('ELASTICSEARCH_PASSWORD', '')
            ) if os.environ.get('ELASTICSEARCH_USER') else None,
            'request_timeout': 30,
            'max_retries': 3,
            'retry_on_timeout': True,
        },
    }

# Search settings
SEARCH_RESULTS_PER_PAGE = 20
SEARCH_AUTOCOMPLETE_MIN_LENGTH = 2
SEARCH_HIGHLIGHT_ENABLED = True
SEARCH_ANALYTICS_ENABLED = True  # Track search queries for analytics

# ===== Task 51: Sentry Error Tracking Configuration =====

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration

# Initialize Sentry
# Get DSN from environment variable (keep it secret!)
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')

if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        
        # Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
        # We recommend adjusting this value in production (0.1 = 10% of transactions)
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        
        # Set profiles_sample_rate to 1.0 to profile 100% of sampled transactions.
        # We recommend adjusting this value in production (0.1 = 10% of sampled transactions)
        profiles_sample_rate=float(os.environ.get('SENTRY_PROFILES_SAMPLE_RATE', '0.1')),
        
        # Send default PII (Personally Identifiable Information) such as user id, username, email
        send_default_pii=True,
        
        # Enable performance monitoring
        enable_tracing=True,
        
        # Set environment (development, staging, production)
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'development'),
        
        # Release tracking (use git commit SHA or version number)
        release=os.environ.get('SENTRY_RELEASE', 'staff-rota-system@1.0.0'),
        
        # Ignore common errors
        ignore_errors=[
            'PermissionDenied',
            'Http404',
        ],
        
        # Before sending an event, modify it
        before_send=lambda event, hint: event if not DEBUG else None,  # Don't send in DEBUG mode
    )

# Sentry settings for user feedback
SENTRY_USER_FEEDBACK_ENABLED = True
SENTRY_FEEDBACK_WIDGET_ENABLED = True
