# Generated by Django 4.2.27 on 2026-01-14 12:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0058_alter_user_sms_notifications_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CLIN-001, LEAD-005', max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Clear definition of what this competency means')),
                ('competency_type', models.CharField(choices=[('CLINICAL', 'Clinical Skill'), ('TECHNICAL', 'Technical Skill'), ('BEHAVIORAL', 'Behavioral Competency'), ('LEADERSHIP', 'Leadership Competency'), ('REGULATORY', 'Regulatory Requirement')], max_length=20)),
                ('assessment_criteria', models.TextField(help_text='How this competency will be assessed (observable behaviors)')),
                ('evidence_required', models.TextField(blank=True, help_text='What evidence demonstrates competency (e.g., witness statements, portfolios)')),
                ('review_frequency_months', models.IntegerField(default=12, help_text='How often should this competency be reassessed?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencies_created', to=settings.AUTH_USER_MODEL)),
                ('linked_training_courses', models.ManyToManyField(blank=True, help_text='Training courses that develop this competency', related_name='competencies_addressed', to='scheduling.trainingcourse')),
            ],
            options={
                'verbose_name_plural': 'Competency Frameworks',
                'ordering': ['competency_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_duration_months', models.IntegerField(help_text='Expected time to complete pathway')),
                ('total_learning_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - Being Developed'), ('ACTIVE', 'Active - Available for Enrollment'), ('UNDER_REVIEW', 'Under Review'), ('ARCHIVED', 'Archived - No Longer Active')], default='DRAFT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways_approved', to=settings.AUTH_USER_MODEL)),
                ('from_role', models.ForeignKey(help_text='Starting role (e.g., Care Assistant)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways_from', to='scheduling.role')),
                ('owner', models.ForeignKey(help_text='Learning & Development Manager responsible', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Learning Pathways',
                'ordering': ['from_role', 'to_role', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoleCompetencyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.CharField(choices=[('AWARENESS', 'Awareness - Basic understanding'), ('WORKING', 'Working - Can perform with supervision'), ('PROFICIENT', 'Proficient - Can perform independently'), ('EXPERT', 'Expert - Can teach and assess others')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Must be achieved before role can be performed independently')),
                ('grace_period_days', models.IntegerField(default=90, help_text='Days allowed to achieve competency after starting role')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_competency.competencyframework')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.role')),
            ],
            options={
                'ordering': ['role', 'is_mandatory', 'competency'],
                'unique_together': {('role', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='PathwayTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_competency.learningpathway')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.trainingcourse')),
            ],
            options={
                'ordering': ['pathway', 'sequence_order'],
                'unique_together': {('pathway', 'training_course')},
            },
        ),
        migrations.CreateModel(
            name='PathwayCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=1)),
                ('required_level', models.CharField(choices=[('AWARENESS', 'Awareness - Basic understanding'), ('WORKING', 'Working - Can perform with supervision'), ('PROFICIENT', 'Proficient - Can perform independently'), ('EXPERT', 'Expert - Can teach and assess others')], max_length=20)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_competency.competencyframework')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_competency.learningpathway')),
            ],
            options={
                'ordering': ['pathway', 'sequence_order'],
                'unique_together': {('pathway', 'competency')},
            },
        ),
        migrations.AddField(
            model_name='learningpathway',
            name='required_competencies',
            field=models.ManyToManyField(related_name='pathways', through='training_competency.PathwayCompetency', to='training_competency.competencyframework'),
        ),
        migrations.AddField(
            model_name='learningpathway',
            name='required_training',
            field=models.ManyToManyField(related_name='pathways', through='training_competency.PathwayTraining', to='scheduling.trainingcourse'),
        ),
        migrations.AddField(
            model_name='learningpathway',
            name='to_role',
            field=models.ForeignKey(help_text='Target role (e.g., Senior Carer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways_to', to='scheduling.role'),
        ),
        migrations.AddField(
            model_name='competencyframework',
            name='required_for_roles',
            field=models.ManyToManyField(related_name='required_competencies', through='training_competency.RoleCompetencyRequirement', to='scheduling.role'),
        ),
        migrations.CreateModel(
            name='TrainingMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('MANDATORY', 'Mandatory - Must complete before working'), ('ESSENTIAL', 'Essential - Must complete within grace period'), ('RECOMMENDED', 'Recommended - Supports role performance'), ('OPTIONAL', 'Optional - Professional development')], max_length=20)),
                ('must_complete_within_days', models.IntegerField(blank=True, help_text='For ESSENTIAL training: days allowed after starting role', null=True)),
                ('must_complete_before_solo_work', models.BooleanField(default=False, help_text='Staff cannot work unsupervised until this is complete')),
                ('priority_order', models.IntegerField(default=1, help_text='Order in which training should be completed (1=highest priority)')),
                ('rationale', models.TextField(blank=True, help_text='Why this training is required for this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('care_home', models.ForeignKey(blank=True, help_text='Leave blank for organization-wide requirement', null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('prerequisite_courses', models.ManyToManyField(blank=True, help_text='Courses that must be completed first', related_name='required_for_courses', to='scheduling.trainingcourse')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requirements', to='scheduling.role')),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.trainingcourse')),
            ],
            options={
                'verbose_name': 'Training Matrix Entry',
                'verbose_name_plural': 'Training Matrix',
                'ordering': ['role', 'priority_order', 'training_course'],
                'unique_together': {('role', 'training_course', 'care_home')},
            },
        ),
        migrations.CreateModel(
            name='StaffLearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], default='NOT_STARTED', max_length=20)),
                ('percent_complete', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('staff_notes', models.TextField(blank=True, help_text="Staff member's own notes and reflections")),
                ('manager_notes', models.TextField(blank=True, help_text='Line manager observations and support provided')),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports_learning', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(blank=True, help_text='Designated mentor/coach', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training_competency.learningpathway')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('staff_member', 'pathway')},
            },
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=django.utils.timezone.now)),
                ('assessment_method', models.CharField(choices=[('OBSERVATION', 'Direct Observation'), ('SIMULATION', 'Simulated Scenario'), ('WRITTEN', 'Written Test/Exam'), ('PORTFOLIO', 'Portfolio Review'), ('INTERVIEW', 'Professional Discussion'), ('PEER_REVIEW', 'Peer Assessment')], max_length=20)),
                ('achieved_level', models.CharField(blank=True, choices=[('AWARENESS', 'Awareness - Basic understanding'), ('WORKING', 'Working - Can perform with supervision'), ('PROFICIENT', 'Proficient - Can perform independently'), ('EXPERT', 'Expert - Can teach and assess others')], max_length=20)),
                ('outcome', models.CharField(choices=[('NOT_YET_STARTED', 'Not Yet Started'), ('IN_PROGRESS', 'In Progress'), ('COMPETENT', 'Competent'), ('HIGHLY_COMPETENT', 'Highly Competent'), ('NOT_YET_COMPETENT', 'Not Yet Competent - Further Development Needed')], default='IN_PROGRESS', max_length=30)),
                ('evidence_description', models.TextField(blank=True, help_text='What evidence was reviewed/observed?')),
                ('assessor_comments', models.TextField(blank=True)),
                ('staff_reflection', models.TextField(blank=True, help_text="Staff member's own reflection on their performance")),
                ('development_needs_identified', models.TextField(blank=True, help_text='Areas for further development')),
                ('action_plan', models.TextField(blank=True, help_text='Specific actions to address development needs')),
                ('next_review_date', models.DateField(blank=True, help_text='When should this competency be reassessed?', null=True)),
                ('expires_on', models.DateField(blank=True, help_text='Some competencies may expire if not used regularly', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tqm_competency_assessments_conducted', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='training_competency.competencyframework')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date'],
                'indexes': [models.Index(fields=['staff_member', '-assessment_date'], name='training_co_staff_m_584557_idx'), models.Index(fields=['competency', 'outcome'], name='training_co_compete_8068c7_idx')],
            },
        ),
    ]
