"""
Management command to set up scheduled compliance checks and email notifications.

This command creates cron job entries for automated compliance monitoring.
"""

from django.core.management.base import BaseCommand
from datetime import time


class Command(BaseCommand):
    help = 'Set up scheduled compliance checks and email notifications'

    def add_arguments(self, parser):
        parser.add_argument(
            '--show-cron',
            action='store_true',
            help='Display crontab entries to add manually',
        )
        parser.add_argument(
            '--install-cron',
            action='store_true',
            help='Generate shell script for cron installation',
        )

    def handle(self, *args, **options):
        """Set up scheduled tasks."""
        
        if options['show_cron']:
            self.show_cron_entries()
        elif options['install_cron']:
            self.generate_cron_script()
        else:
            self.stdout.write(self.style.SUCCESS('Scheduled Task Setup'))
            self.stdout.write('')
            self.stdout.write('This command helps you set up automated compliance checks.')
            self.stdout.write('')
            self.stdout.write('Options:')
            self.stdout.write('  --show-cron      Show crontab entries to add manually')
            self.stdout.write('  --install-cron   Generate installation script')
            self.stdout.write('')
            self.stdout.write('For Django-Q setup, see: SCHEDULED_COMPLIANCE_CHECKS.md')

    def show_cron_entries(self):
        """Display crontab entries for manual installation."""
        import os
        import sys
        
        project_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
        python_path = sys.executable
        
        self.stdout.write(self.style.SUCCESS('\n=== CRON ENTRIES FOR MANUAL INSTALLATION ===\n'))
        
        self.stdout.write('Add these lines to your crontab (crontab -e):\n')
        
        # Daily compliance checks at 2 AM
        self.stdout.write(f'''# Daily compliance checks at 2:00 AM
0 2 * * * cd {project_dir} && {python_path} manage.py run_compliance_checks --start-date $(date +\\%Y-\\%m-\\%d) --end-date $(date -d '+7 days' +\\%Y-\\%m-\\%d) >> /var/log/rotasystem/compliance.log 2>&1
''')
        
        # Daily email digest at 8 AM
        self.stdout.write(f'''# Daily violation digest at 8:00 AM
0 8 * * * cd {project_dir} && {python_path} manage.py shell -c "from scheduling.utils.notifications import send_daily_violation_digest; send_daily_violation_digest()" >> /var/log/rotasystem/notifications.log 2>&1
''')
        
        # Weekly summary Monday 9 AM
        self.stdout.write(f'''# Weekly compliance summary every Monday at 9:00 AM
0 9 * * 1 cd {project_dir} && {python_path} manage.py shell -c "from scheduling.utils.notifications import send_weekly_compliance_summary; send_weekly_compliance_summary()" >> /var/log/rotasystem/notifications.log 2>&1
''')
        
        self.stdout.write(self.style.WARNING('\nIMPORTANT: Create log directory first:'))
        self.stdout.write('  sudo mkdir -p /var/log/rotasystem')
        self.stdout.write(f'  sudo chown {os.getenv("USER")}:{os.getenv("USER")} /var/log/rotasystem\n')

    def generate_cron_script(self):
        """Generate a shell script for easy cron installation."""
        import os
        import sys
        
        project_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
        python_path = sys.executable
        script_path = os.path.join(project_dir, 'install_scheduled_tasks.sh')
        
        script_content = f'''#!/bin/bash
# Automated Compliance Check Installer
# Generated by setup_scheduled_tasks command

set -e

echo "=== Installing Scheduled Compliance Checks ==="
echo ""

# Create log directory
echo "Creating log directory..."
sudo mkdir -p /var/log/rotasystem
sudo chown $USER:$USER /var/log/rotasystem
echo "✓ Log directory created"

# Backup existing crontab
echo ""
echo "Backing up existing crontab..."
crontab -l > /tmp/crontab_backup_$(date +%Y%m%d_%H%M%S).txt 2>/dev/null || echo "No existing crontab"

# Create new crontab entries
echo ""
echo "Creating crontab entries..."

# Get existing crontab
crontab -l > /tmp/current_crontab 2>/dev/null || touch /tmp/current_crontab

# Add new entries if they don't exist
grep -q "Daily compliance checks" /tmp/current_crontab || cat >> /tmp/current_crontab << 'EOF'

# ===== Staff Rota Automated Compliance Checks =====

# Daily compliance checks at 2:00 AM
0 2 * * * cd {project_dir} && {python_path} manage.py run_compliance_checks --start-date $(date +\\%Y-\\%m-\\%d) --end-date $(date -d '+7 days' +\\%Y-\\%m-\\%d) >> /var/log/rotasystem/compliance.log 2>&1

# Daily violation digest at 8:00 AM
0 8 * * * cd {project_dir} && {python_path} manage.py shell -c "from scheduling.utils.notifications import send_daily_violation_digest; send_daily_violation_digest()" >> /var/log/rotasystem/notifications.log 2>&1

# Weekly compliance summary every Monday at 9:00 AM
0 9 * * 1 cd {project_dir} && {python_path} manage.py shell -c "from scheduling.utils.notifications import send_weekly_compliance_summary; send_weekly_compliance_summary()" >> /var/log/rotasystem/notifications.log 2>&1

EOF

# Install new crontab
crontab /tmp/current_crontab
rm /tmp/current_crontab

echo "✓ Crontab entries installed"
echo ""
echo "=== Installation Complete ==="
echo ""
echo "Scheduled tasks:"
echo "  - Daily compliance checks: 2:00 AM"
echo "  - Daily violation digest: 8:00 AM"
echo "  - Weekly summary: Monday 9:00 AM"
echo ""
echo "Logs location: /var/log/rotasystem/"
echo ""
echo "To view current crontab: crontab -l"
echo "To remove crontab: crontab -r"
'''
        
        with open(script_path, 'w') as f:
            f.write(script_content)
        
        os.chmod(script_path, 0o755)
        
        self.stdout.write(self.style.SUCCESS(f'\n✓ Installation script created: {script_path}\n'))
        self.stdout.write('Run the script with:')
        self.stdout.write(f'  bash {script_path}\n')
