# Generated by Django 5.2.7 on 2025-10-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='required_headcount',
            field=models.IntegerField(default=0, help_text='Target number of staff required for this role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SCW', 'Senior Care Worker'), ('SCA', 'Senior Care Assistant'), ('SSCW', 'Senior Social Care Worker'), ('ACTC', 'Activities Coordinator'), ('ACTA', 'Activities Assistant'), ('SEC', 'Security'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], max_length=100, unique=True),
        ),
    ]
