# Generated by Django 5.2.7 on 2025-12-03 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_trainingcourse_alter_auditreport_report_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('hourly_rate_day', models.DecimalField(decimal_places=2, default=0, help_text='Standard day shift hourly rate', max_digits=6)),
                ('hourly_rate_night', models.DecimalField(decimal_places=2, default=0, help_text='Standard night shift hourly rate', max_digits=6)),
                ('account_number', models.CharField(blank=True, help_text='For billing purposes', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agency Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='agency_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual rate charged for this shift', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='agency_staff_name',
            field=models.CharField(blank=True, help_text='Name of agency staff member', max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_classification',
            field=models.CharField(choices=[('REGULAR', 'Regular Shift'), ('OVERTIME', 'Overtime'), ('AGENCY', 'Agency Staff')], default='REGULAR', help_text='Regular, Overtime, or Agency', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_pattern',
            field=models.CharField(choices=[('DAY_0800_2000', '08:00 - 20:00 (Day Shift)'), ('NIGHT_2000_0800', '20:00 - 08:00 (Night Shift)'), ('CUSTOM', 'Custom Times')], default='DAY_0800_2000', help_text='Standard shift pattern', max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='custom_end_time',
            field=models.TimeField(blank=True, help_text='Required if shift_pattern is CUSTOM', null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='custom_start_time',
            field=models.TimeField(blank=True, help_text='Required if shift_pattern is CUSTOM', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='agency_company',
            field=models.ForeignKey(blank=True, help_text='Required if shift_classification is AGENCY', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.agencycompany'),
        ),
    ]
