# Generated by Django 5.2.7 on 2025-12-03 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_agencycompany_shift_agency_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePlanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('INITIAL', '4-Week Initial Review'), ('SIX_MONTH', '6-Monthly Review'), ('UNSCHEDULED', 'Unscheduled Review')], max_length=20)),
                ('due_date', models.DateField(help_text='Date review is due by')),
                ('scheduled_date', models.DateField(blank=True, help_text='Date review is scheduled for', null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due Soon (7 days)'), ('OVERDUE', 'Overdue'), ('IN_PROGRESS', 'In Progress'), ('PENDING_APPROVAL', 'Pending Manager Approval'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('manager_approved', models.BooleanField(default=False)),
                ('manager_approval_date', models.DateField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('care_needs_assessment', models.TextField(blank=True, help_text='Assessment of current care needs')),
                ('goals_progress', models.TextField(blank=True, help_text='Progress towards care plan goals')),
                ('changes_required', models.TextField(blank=True, help_text='Changes to care plan required')),
                ('family_involvement', models.TextField(blank=True, help_text='Family/NOK involvement notes')),
                ('days_overdue', models.IntegerField(default=0, help_text='Automatically calculated')),
                ('is_compliant', models.BooleanField(default=True, help_text='False if review is overdue')),
                ('alert_7_days_sent', models.BooleanField(default=False)),
                ('alert_due_sent', models.BooleanField(default=False)),
                ('alert_overdue_sent', models.BooleanField(default=False)),
                ('alert_manager_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_careplan_reviews', to=settings.AUTH_USER_MODEL)),
                ('keyworker', models.ForeignKey(help_text='Keyworker responsible for this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('manager_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reviews', to=settings.AUTH_USER_MODEL)),
                ('unit_manager', models.ForeignKey(help_text='Manager responsible for approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_to_approve', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'resident__unit'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanReviewDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='e.g., Assessment Form, Family Notes', max_length=100)),
                ('file', models.FileField(upload_to='careplan_reviews/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scheduling.careplanreview')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(help_text='Unique resident identifier', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('room_number', models.CharField(help_text='Room number (1-15 per unit)', max_length=10)),
                ('admission_date', models.DateField(help_text='Date resident was admitted to the home')),
                ('is_active', models.BooleanField(default=True, help_text='False if resident has been discharged/deceased')),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyworker', models.ForeignKey(blank=True, help_text="Care staff responsible for this resident's reviews", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyworker_residents', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='scheduling.unit')),
                ('unit_manager', models.ForeignKey(blank=True, help_text='SSCW/SSCWN responsible for oversight', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_residents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['unit', 'room_number'],
            },
        ),
        migrations.AddField(
            model_name='careplanreview',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_reviews', to='scheduling.resident'),
        ),
    ]
