# Generated by Django 5.2.7 on 2025-12-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_add_ideal_staffing'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_level',
            field=models.CharField(choices=[('FULL', 'Full Access - SM/OM can approve, manage rotas, view all data'), ('MOST', 'Most Access - SSCW can view schedules, team data, submit requests'), ('LIMITED', 'Limited Access - Staff can view own info, submit requests only')], default='LIMITED', help_text='Access level for home-specific dashboards', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_senior_management_team',
            field=models.BooleanField(default=False, help_text='Head of Service team member (SM, OM, HOS, IDI) with governance oversight across all homes'),
        ),
    ]
