# Generated by Django 4.2.27 on 2025-12-26 12:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0026_task11_feedback_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_detail_level', models.CharField(choices=[('BRIEF', 'Brief (summary only)'), ('STANDARD', 'Standard (balanced)'), ('DETAILED', 'Detailed (comprehensive)')], default='STANDARD', max_length=20)),
                ('preferred_tone', models.CharField(choices=[('FORMAL', 'Formal/Professional'), ('FRIENDLY', 'Friendly/Casual'), ('TECHNICAL', 'Technical/Data-focused')], default='FRIENDLY', max_length=20)),
                ('avg_queries_per_session', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('most_common_intent', models.CharField(blank=True, max_length=50)),
                ('avg_satisfaction_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('prefers_examples', models.BooleanField(default=True, help_text='Include examples in responses')),
                ('prefers_step_by_step', models.BooleanField(default=False, help_text='Break down into steps')),
                ('prefers_visualizations', models.BooleanField(default=True, help_text='Include charts/graphs')),
                ('total_queries', models.IntegerField(default=0)),
                ('total_feedback_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ai_preferences',
            },
        ),
        migrations.CreateModel(
            name='AIQueryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Original query text')),
                ('intent_detected', models.CharField(help_text='Intent classified by system', max_length=50)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='0-100 confidence', max_digits=5)),
                ('response_text', models.TextField(help_text='AI response provided')),
                ('response_data', models.JSONField(blank=True, help_text='Structured data returned', null=True)),
                ('rating', models.IntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='User satisfaction rating')),
                ('feedback_type', models.CharField(blank=True, choices=[('HELPFUL', 'Response was helpful'), ('INACCURATE', 'Response was inaccurate'), ('INCOMPLETE', 'Response was incomplete'), ('TOO_TECHNICAL', 'Too technical'), ('TOO_SIMPLE', 'Too simple'), ('WRONG_INTENT', 'Misunderstood query'), ('GOOD_FORMAT', 'Good formatting'), ('BAD_FORMAT', 'Poor formatting')], max_length=20, null=True)),
                ('feedback_comment', models.TextField(blank=True, help_text='Optional user comment')),
                ('refinement_query', models.TextField(blank=True, help_text="User's refined query (if provided)")),
                ('refinement_successful', models.BooleanField(default=False, help_text='Did refinement help?')),
                ('learned_from', models.BooleanField(default=False, help_text='Used for model training')),
                ('learned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, help_text='User session identifier', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_query_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_query_fe_user_id_befb9a_idx'), models.Index(fields=['intent_detected', 'rating'], name='ai_query_fe_intent__b2b4a2_idx'), models.Index(fields=['rating', '-created_at'], name='ai_query_fe_rating_2c0b01_idx')],
            },
        ),
    ]
