# Generated by Django 4.2.27 on 2025-12-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0029_overtimecoveragerequest_staffovertimepreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyBlastBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_deadline', models.DateTimeField(help_text='Deadline for agency responses (default 30 min)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Responses'), ('PARTIAL', 'Partial Responses Received'), ('BOOKED', 'Booked with Agency'), ('TIMEOUT', 'Deadline Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50)),
                ('budget_limit', models.DecimalField(decimal_places=2, help_text='Maximum acceptable rate for auto-booking', max_digits=8)),
                ('final_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed rate', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_batches', to='scheduling.agencyrequest')),
                ('booked_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_blasts', to='scheduling.agencycompany')),
            ],
            options={
                'verbose_name': 'Agency Blast Batch',
                'verbose_name_plural': 'Agency Blast Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Priority rank (1=highest)')),
                ('status', models.CharField(choices=[('SENT', 'Email Sent'), ('EMAIL_FAILED', 'Email Delivery Failed'), ('OPENED', 'Email Opened'), ('ACCEPTED', 'Accepted at Budget Rate'), ('QUOTED', 'Custom Quote Provided'), ('DECLINED', 'Declined'), ('BOOKED', 'Booking Confirmed'), ('CANCELLED', 'Cancelled - Filled by Another')], default='SENT', max_length=50)),
                ('quoted_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate quoted by agency (if provided)', max_digits=8, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_minutes', models.IntegerField(blank=True, help_text='Minutes between sent and response', null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_responses', to='scheduling.agencycompany')),
                ('blast_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_responses', to='scheduling.agencyblastbatch')),
            ],
            options={
                'verbose_name': 'Agency Response',
                'verbose_name_plural': 'Agency Responses',
                'ordering': ['rank'],
                'unique_together': {('blast_batch', 'agency')},
            },
        ),
        migrations.AddIndex(
            model_name='agencyblastbatch',
            index=models.Index(fields=['status', 'response_deadline'], name='scheduling__status_7611e9_idx'),
        ),
    ]
