# Generated by Django 4.2.27 on 2025-12-30 09:08

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0031_merge_20251230_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('STAFFING', 'Staffing Report'), ('LEAVE', 'Leave Report'), ('SHIFTS', 'Shift Report'), ('TRAINING', 'Training Report'), ('COMPLIANCE', 'Compliance Report'), ('INCIDENTS', 'Incident Report'), ('RESIDENTS', 'Resident Report'), ('CUSTOM', 'Custom Report')], default='CUSTOM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_fields', models.JSONField(default=list, help_text='List of field names to include in report')),
                ('filters', models.JSONField(default=dict, help_text='Filter criteria (date ranges, homes, units, staff, etc.)')),
                ('grouping', models.JSONField(default=dict, help_text='Grouping and aggregation settings')),
                ('sorting', models.JSONField(default=list, help_text='Sort order for report data')),
                ('output_format', models.CharField(choices=[('PDF', 'PDF Document'), ('EXCEL', 'Excel Spreadsheet'), ('CSV', 'CSV File')], default='PDF', max_length=10)),
                ('is_public', models.BooleanField(default=False, help_text='Allow other managers to use this template')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Report Template',
                'verbose_name_plural': 'Saved Report Templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], default='WEEKLY', max_length=20)),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly reports (0=Monday, 6=Sunday)', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly reports', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('time_of_day', models.TimeField(default=datetime.time(9, 0), help_text='Time to generate report')),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses to send report to')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling.savedreport')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['next_run'],
            },
        ),
    ]
