# Generated by Django 4.2.27 on 2025-12-30 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0038_staffcertification_regulatorycheck_audittrail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_shifts', models.IntegerField(default=0)),
                ('shifts_attended', models.IntegerField(default=0)),
                ('shifts_late', models.IntegerField(default=0)),
                ('shifts_absent', models.IntegerField(default=0)),
                ('unauthorized_absences', models.IntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (0-100)', max_digits=5)),
                ('punctuality_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (0-100)', max_digits=5)),
                ('shifts_completed', models.IntegerField(default=0)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (0-100)', max_digits=5)),
                ('total_minutes_late', models.IntegerField(default=0)),
                ('average_minutes_late', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, help_text='Score 0-100', max_digits=5)),
                ('punctuality_score', models.DecimalField(decimal_places=2, default=0, help_text='Score 0-100', max_digits=5)),
                ('completion_score', models.DecimalField(decimal_places=2, default=0, help_text='Score 0-100', max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, help_text='Score 0-100', max_digits=5)),
                ('performance_rating', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs Improvement'), ('POOR', 'Poor')], default='SATISFACTORY', max_length=20)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_performance', to='scheduling.carehome')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_reviews_given', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Performance',
                'verbose_name_plural': 'Staff Performance Records',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('PROBATION', 'Probation Review'), ('QUARTERLY', 'Quarterly Review'), ('ANNUAL', 'Annual Review'), ('DISCIPLINARY', 'Disciplinary Review'), ('EXCELLENCE', 'Excellence Recognition')], max_length=20)),
                ('review_date', models.DateField()),
                ('quality_of_work', models.IntegerField(default=5, help_text='Score 1-10')),
                ('reliability', models.IntegerField(default=5, help_text='Score 1-10')),
                ('teamwork', models.IntegerField(default=5, help_text='Score 1-10')),
                ('communication', models.IntegerField(default=5, help_text='Score 1-10')),
                ('professionalism', models.IntegerField(default=5, help_text='Score 1-10')),
                ('achievements', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('development_goals', models.TextField(blank=True)),
                ('action_plan', models.TextField(blank=True)),
                ('staff_comments', models.TextField(blank=True)),
                ('staff_acknowledged', models.BooleanField(default=False)),
                ('staff_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('CONTINUE', 'Continue as Normal'), ('IMPROVE', 'Improvement Plan'), ('PROMOTE', 'Promotion Recommended'), ('WARNING', 'Formal Warning'), ('TERMINATE', 'Termination Recommended')], default='CONTINUE', max_length=20)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='scheduling.carehome')),
                ('performance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formal_reviews', to='scheduling.staffperformance')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('SICK', 'Sick Leave'), ('AUTHORIZED', 'Authorized Absence'), ('UNAUTHORIZED', 'Unauthorized Absence')], default='PRESENT', max_length=20)),
                ('scheduled_start', models.TimeField()),
                ('actual_start', models.TimeField(blank=True, null=True)),
                ('scheduled_end', models.TimeField()),
                ('actual_end', models.TimeField(blank=True, null=True)),
                ('minutes_late', models.IntegerField(default=0, help_text='Minutes late for shift start')),
                ('minutes_early_departure', models.IntegerField(default=0, help_text='Minutes left before shift end')),
                ('shift_completed', models.BooleanField(default=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('reason_for_absence', models.TextField(blank=True)),
                ('documentation_provided', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='scheduling.shift')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='staffperformance',
            index=models.Index(fields=['staff_member', '-period_end'], name='scheduling__staff_m_71c4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='staffperformance',
            index=models.Index(fields=['care_home', 'performance_rating'], name='scheduling__care_ho_0ae5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='staffperformance',
            index=models.Index(fields=['overall_score'], name='scheduling__overall_1e8144_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffperformance',
            unique_together={('staff_member', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['staff_member', '-review_date'], name='scheduling__staff_m_2e4b12_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['review_type', 'outcome'], name='scheduling__review__117097_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['staff_member', '-date'], name='scheduling__staff_m_4198a3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'status'], name='scheduling__date_dbbd36_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['shift', 'status'], name='scheduling__shift_i_ee308e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('staff_member', 'shift')},
        ),
    ]
