# Generated by Django 4.2.27 on 2025-12-30 13:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0043_customreporttemplate_reportdatasource_reportschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('client_type', models.CharField(choices=[('HR', 'HR System'), ('PAYROLL', 'Payroll System'), ('ANALYTICS', 'Analytics Platform'), ('MOBILE', 'Mobile Application'), ('WEBHOOK', 'Webhook Integration'), ('CUSTOM', 'Custom Integration')], max_length=20)),
                ('client_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('api_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('allowed_endpoints', models.JSONField(default=list, help_text='List of endpoint patterns this client can access')),
                ('allowed_methods', models.JSONField(default=list, help_text='HTTP methods allowed (GET, POST, PUT, DELETE)')),
                ('ip_whitelist', models.JSONField(default=list, help_text='IP addresses allowed to use this client')),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_hour', models.IntegerField(default=1000)),
                ('rate_limit_per_day', models.IntegerField(default=10000)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('successful_requests', models.BigIntegerField(default=0)),
                ('failed_requests', models.BigIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('event_types', models.JSONField(default=list, help_text='Event types this webhook subscribes to')),
                ('secret', models.CharField(help_text='Secret for HMAC signature verification', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('retry_delay_seconds', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='scheduling.apiclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField()),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='scheduling.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook', '-created_at'], name='scheduling__webhook_95eb09_idx'), models.Index(fields=['status', 'next_retry_at'], name='scheduling__status_efb61c_idx'), models.Index(fields=['event_id'], name='scheduling__event_i_efb658_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('STAFF_EXPORT', 'Staff Data Export'), ('STAFF_IMPORT', 'Staff Data Import'), ('SHIFT_EXPORT', 'Shift Data Export'), ('LEAVE_EXPORT', 'Leave Data Export'), ('PAYROLL_EXPORT', 'Payroll Data Export'), ('FULL_SYNC', 'Full System Sync')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_succeeded', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_details', models.JSONField(default=list)),
                ('export_file_path', models.CharField(blank=True, max_length=500)),
                ('export_file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='scheduling.apiclient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='scheduling__client__fb5b73_idx'), models.Index(fields=['status', '-created_at'], name='scheduling__status_607c44_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('token_type', models.CharField(choices=[('ACCESS', 'Access Token'), ('REFRESH', 'Refresh Token')], max_length=20)),
                ('scope', models.JSONField(default=list, help_text='Specific permissions granted to this token')),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='scheduling.apiclient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='scheduling__token_b9cf11_idx'), models.Index(fields=['expires_at', 'is_active'], name='scheduling__expires_edf068_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('query_params', models.JSONField(default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('response_size', models.IntegerField(default=0, help_text='Response size in bytes')),
                ('error_message', models.TextField(blank=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='scheduling.apiclient')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['client', '-timestamp'], name='scheduling__client__824085_idx'), models.Index(fields=['endpoint', '-timestamp'], name='scheduling__endpoin_72030e_idx'), models.Index(fields=['status_code', '-timestamp'], name='scheduling__status__bec8b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_type', models.CharField(choices=[('MINUTE', 'Per Minute'), ('HOUR', 'Per Hour'), ('DAY', 'Per Day')], max_length=10)),
                ('window_start', models.DateTimeField()),
                ('request_count', models.IntegerField(default=0)),
                ('endpoint', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to='scheduling.apiclient')),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'window_start'], name='scheduling__client__ed8da8_idx'), models.Index(fields=['window_type', 'window_start'], name='scheduling__window__566f86_idx')],
                'unique_together': {('client', 'window_type', 'window_start', 'endpoint')},
            },
        ),
        migrations.AddIndex(
            model_name='apiclient',
            index=models.Index(fields=['client_id'], name='scheduling__client__18122e_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclient',
            index=models.Index(fields=['api_key'], name='scheduling__api_key_ee7186_idx'),
        ),
        migrations.AddIndex(
            model_name='apiclient',
            index=models.Index(fields=['status', 'is_active'], name='scheduling__status_88a70f_idx'),
        ),
    ]
