# Generated by Django 4.2.27 on 2025-12-30 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduling', '0050_video_tutorial_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeedWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('recent', 'Recent Activities'), ('category', 'Category-Specific Feed'), ('user', 'User Activities'), ('priority', 'Priority Activities'), ('unread', 'Unread Activities')], max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small (5 items)'), ('medium', 'Medium (10 items)'), ('large', 'Large (20 items)')], default='medium', max_length=10)),
                ('filter_category', models.CharField(blank=True, help_text='Filter by category', max_length=20)),
                ('filter_priority', models.CharField(blank=True, help_text='Filter by priority', max_length=10)),
                ('days_to_show', models.IntegerField(default=7, help_text='Number of days to display')),
                ('show_read', models.BooleanField(default=True, help_text='Include read activities')),
                ('show_icons', models.BooleanField(default=True)),
                ('show_timestamps', models.BooleanField(default=True)),
                ('show_user_avatars', models.BooleanField(default=True)),
                ('auto_refresh', models.BooleanField(default=True, help_text='Auto-refresh with AJAX')),
                ('refresh_interval', models.IntegerField(default=30, help_text='Refresh interval in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Feed Widget',
                'verbose_name_plural': 'Activity Feed Widgets',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('shift', 'Shift Management'), ('staff', 'Staff Management'), ('leave', 'Leave Requests'), ('training', 'Training & Development'), ('document', 'Documents'), ('compliance', 'Compliance'), ('system', 'System Events'), ('workflow', 'Workflows'), ('communication', 'Communications')], db_index=True, max_length=20)),
                ('activity_type', models.CharField(choices=[('shift_created', 'Shift Created'), ('shift_updated', 'Shift Updated'), ('shift_deleted', 'Shift Deleted'), ('shift_assigned', 'Shift Assigned'), ('shift_cancelled', 'Shift Cancelled'), ('shift_filled', 'Shift Filled'), ('staff_added', 'Staff Added'), ('staff_updated', 'Staff Updated'), ('staff_deleted', 'Staff Deleted'), ('staff_activated', 'Staff Activated'), ('staff_deactivated', 'Staff Deactivated'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('leave_cancelled', 'Leave Cancelled'), ('training_assigned', 'Training Assigned'), ('training_completed', 'Training Completed'), ('training_expired', 'Training Expired'), ('certification_earned', 'Certification Earned'), ('document_uploaded', 'Document Uploaded'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('document_shared', 'Document Shared'), ('compliance_alert', 'Compliance Alert'), ('compliance_resolved', 'Compliance Resolved'), ('review_completed', 'Review Completed'), ('workflow_started', 'Workflow Started'), ('workflow_completed', 'Workflow Completed'), ('workflow_failed', 'Workflow Failed'), ('notification_sent', 'Notification Sent'), ('email_sent', 'Email Sent'), ('sms_sent', 'SMS Sent'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('settings_changed', 'Settings Changed'), ('error_occurred', 'Error Occurred')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('icon', models.CharField(default='fa-bell', help_text='FontAwesome icon class', max_length=50)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-archive after this date', null=True)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recent Activity',
                'verbose_name_plural': 'Recent Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', '-created_at'], name='scheduling__categor_abd306_idx'), models.Index(fields=['user', '-created_at'], name='scheduling__user_id_3f276f_idx'), models.Index(fields=['care_home', '-created_at'], name='scheduling__care_ho_6ca81f_idx'), models.Index(fields=['priority', '-created_at'], name='scheduling__priorit_143515_idx'), models.Index(fields=['is_read', '-created_at'], name='scheduling__is_read_a95971_idx'), models.Index(fields=['-created_at', 'category', 'is_archived'], name='scheduling__created_6b49d5_idx')],
            },
        ),
    ]
