# Generated by Django 4.2.27 on 2025-12-30 23:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0052_enforce_six_digit_sap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Widget name for management (not displayed to users)', max_length=200)),
                ('widget_type', models.CharField(choices=[('single_metric', 'Single Metric Card'), ('category_summary', 'Category Summary'), ('traffic_light', 'Traffic Light Grid'), ('trend_chart', 'Trend Chart'), ('red_flags', 'Red Flags Alert'), ('ci_dashboard', 'CI Inspection Dashboard')], help_text='Type of widget display', max_length=50)),
                ('size', models.CharField(choices=[('small', 'Small (4 cols)'), ('medium', 'Medium (6 cols)'), ('large', 'Large (8 cols)'), ('full', 'Full Width (12 cols)')], default='medium', help_text='Widget size (Bootstrap columns)', max_length=20)),
                ('category_filter', models.CharField(blank=True, help_text='Show only metrics from this category (blank = all categories)', max_length=50)),
                ('metric_ids', models.JSONField(blank=True, help_text='Specific metric IDs to display (for single_metric type)', null=True)),
                ('title', models.CharField(help_text='Widget title displayed to users', max_length=200)),
                ('show_trend', models.BooleanField(default=True, help_text='Show trend arrows/indicators')),
                ('show_counts', models.BooleanField(default=True, help_text='Show compliant/non-compliant counts')),
                ('show_ci_theme', models.BooleanField(default=False, help_text='Show Care Inspectorate theme labels')),
                ('show_last_updated', models.BooleanField(default=True, help_text='Show last calculation timestamp')),
                ('auto_refresh', models.BooleanField(default=True, help_text='Auto-refresh widget data via AJAX')),
                ('refresh_interval', models.IntegerField(default=300, help_text='Auto-refresh interval in seconds (30-3600, default 5 min)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(3600)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this widget currently active?')),
                ('is_public', models.BooleanField(default=False, help_text='Can all users see this widget? (False = creator only)')),
                ('display_order', models.IntegerField(default=0, help_text='Display order on dashboards (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(blank=True, help_text='Filter to specific care home (null = all homes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_widgets', to='scheduling.carehome')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_widgets', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, help_text='Filter to specific unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_widgets', to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Compliance Widget',
                'verbose_name_plural': 'Compliance Widgets',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('training', 'Training Compliance'), ('supervision', 'Supervision Compliance'), ('wtd', 'Working Time Directive'), ('incidents', 'Incident Management'), ('induction', 'Induction Progress'), ('medication', 'Medication Administration'), ('safeguarding', 'Safeguarding'), ('care_plans', 'Care Plan Reviews'), ('overall', 'Overall Compliance')], db_index=True, help_text='Type of compliance metric', max_length=50)),
                ('metric_name', models.CharField(help_text='Display name for the metric (e.g., "Mandatory Training Completion")', max_length=200)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current compliance percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_value', models.DecimalField(decimal_places=2, default=95.0, help_text='Target compliance percentage (default 95%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('green', 'Compliant'), ('amber', 'At Risk'), ('red', 'Non-Compliant')], help_text='Traffic light status based on current_value vs target', max_length=10)),
                ('compliant_count', models.IntegerField(default=0, help_text='Number of compliant items/staff')),
                ('at_risk_count', models.IntegerField(default=0, help_text='Number of items/staff at risk (e.g., expiring soon)')),
                ('non_compliant_count', models.IntegerField(default=0, help_text='Number of non-compliant items/staff')),
                ('total_count', models.IntegerField(default=0, help_text='Total items/staff assessed')),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, help_text='Previous period value for trend calculation', max_digits=5, null=True)),
                ('trend_direction', models.CharField(blank=True, choices=[('up', 'Improving'), ('down', 'Declining'), ('stable', 'Stable')], help_text='Trend direction compared to previous period', max_length=10, null=True)),
                ('calculation_date', models.DateTimeField(auto_now=True, help_text='When this metric was last calculated')),
                ('period_start', models.DateField(help_text='Start date of measurement period')),
                ('period_end', models.DateField(help_text='End date of measurement period')),
                ('notes', models.TextField(blank=True, help_text='Additional context or alerts (e.g., "2 staff certifications expire this week")')),
                ('ci_relevant', models.BooleanField(default=True, help_text='Is this metric relevant for Care Inspectorate inspections?')),
                ('ci_theme', models.CharField(blank=True, choices=[('care_wellbeing', 'Care and Wellbeing'), ('staff_team', 'Staff Team'), ('leadership', 'Leadership and Management'), ('environment', 'Environment'), ('planning', 'Planning')], help_text='Related Care Inspectorate quality theme', max_length=100)),
                ('care_home', models.ForeignKey(help_text='Care home this metric applies to (null = organization-wide)', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_metrics', to='scheduling.carehome')),
                ('unit', models.ForeignKey(blank=True, help_text='Specific unit (optional, for unit-level metrics)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_metrics', to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Compliance Metric',
                'verbose_name_plural': 'Compliance Metrics',
                'ordering': ['-calculation_date', 'category', 'care_home'],
                'indexes': [models.Index(fields=['care_home', 'category', '-calculation_date'], name='scheduling__care_ho_da7d5b_idx'), models.Index(fields=['unit', 'category', '-calculation_date'], name='scheduling__unit_id_7d2f91_idx'), models.Index(fields=['status', '-calculation_date'], name='scheduling__status_795ed5_idx'), models.Index(fields=['ci_relevant', 'care_home'], name='scheduling__ci_rele_3c0c81_idx')],
            },
        ),
    ]
