# Generated by Django 4.2.27 on 2026-01-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0055_week6_power_user_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='care_home',
            field=models.ForeignKey(blank=True, help_text='Care home this unit belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='scheduling.carehome'),
        ),
    ]
