# Generated by Django 4.2.27 on 2026-01-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0058_alter_user_sms_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shift_preference',
            field=models.CharField(blank=True, choices=[('DAY', 'Day Shift Preferred'), ('NIGHT', 'Night Shift Preferred'), ('NO_PREFERENCE', 'No Preference'), ('DAY_SENIOR', 'Day Shift (SSCW/SCW)'), ('DAY_ASSISTANT', 'Day Shift (SCA)'), ('NIGHT_SENIOR', 'Night Shift (SSCW/SCW)'), ('NIGHT_ASSISTANT', 'Night Shift (SCA)')], max_length=15, null=True),
        ),
    ]
