# Generated by Django 4.2.27 on 2026-01-13 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0058_alter_user_sms_notifications_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDSACycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField(default=1, help_text='Auto-increments for each cycle in project')),
                ('hypothesis', models.TextField(help_text='We believe that [CHANGE] will result in [OUTCOME] because [THEORY]')),
                ('prediction', models.TextField(help_text='What do we expect to happen?')),
                ('change_idea', models.TextField(help_text='What specific change will we test?')),
                ('data_collection_plan', models.TextField(help_text='What will we measure? How? How often?')),
                ('plan_start_date', models.DateField()),
                ('plan_end_date', models.DateField()),
                ('ai_hypothesis_used', models.BooleanField(default=False, help_text='Did user select AI-suggested hypothesis?')),
                ('execution_log', models.TextField(blank=True, help_text='Daily/weekly implementation notes')),
                ('observations', models.TextField(blank=True, help_text='What actually happened during execution?')),
                ('deviations', models.TextField(blank=True, help_text='Any unplanned events or changes?')),
                ('staff_feedback', models.TextField(blank=True, help_text='Comments from team members during execution')),
                ('do_start_date', models.DateField(blank=True, null=True)),
                ('do_end_date', models.DateField(blank=True, null=True)),
                ('data_analysis', models.TextField(blank=True, help_text='Analysis of collected data')),
                ('ai_data_insights', models.JSONField(blank=True, help_text='AI-generated statistical insights stored as JSON', null=True)),
                ('findings', models.TextField(blank=True, help_text='What did the data show?')),
                ('comparison_to_prediction', models.TextField(blank=True, help_text='Did results match our prediction?')),
                ('lessons_learned', models.TextField(blank=True, help_text="What worked? What didn't?")),
                ('unexpected_outcomes', models.TextField(blank=True, help_text='Any surprises?')),
                ('study_completed_date', models.DateField(blank=True, null=True)),
                ('act_decision', models.CharField(choices=[('ADOPT', 'Adopt - Implement permanently'), ('ADAPT', 'Adapt - Modify and test again'), ('ABANDON', 'Abandon - Try different approach'), ('PENDING', 'Pending - Not yet decided')], default='PENDING', max_length=20)),
                ('next_steps', models.TextField(blank=True, help_text='What happens next? If Adapt, what will we change?')),
                ('new_cycle_planned', models.BooleanField(default=False, help_text='Will we create another PDSA cycle?')),
                ('spread_plan', models.TextField(blank=True, help_text='If Adopt, how will we roll out to other units/homes?')),
                ('act_completed_date', models.DateField(blank=True, null=True)),
                ('auto_analysis_completed', models.BooleanField(default=False, help_text='Has AI completed statistical analysis?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDSA Cycle',
                'verbose_name_plural': 'PDSA Cycles',
                'ordering': ['project', 'cycle_number'],
            },
        ),
        migrations.CreateModel(
            name='PDSAProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Concise project title', max_length=200)),
                ('aim_statement', models.TextField(help_text='SMART aim: By [DATE], improve [MEASURE] from [BASELINE] to [TARGET] for [POPULATION] by [METHOD]')),
                ('problem_description', models.TextField(help_text='Current state analysis - what problem are we solving?')),
                ('target_population', models.CharField(help_text='Which residents/units/homes are affected?', max_length=200)),
                ('category', models.CharField(choices=[('CLINICAL', 'Clinical Quality'), ('WELLBEING', 'Staff Wellbeing'), ('EXPERIENCE', 'Resident Experience'), ('SAFETY', 'Safety'), ('COMPLIANCE', 'Compliance'), ('EFFICIENCY', 'Operational Efficiency')], default='CLINICAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='PLANNING', max_length=20)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current state measurement', max_digits=10, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, help_text='Desired state measurement', max_digits=10, null=True)),
                ('measurement_unit', models.CharField(blank=True, help_text="E.g., 'falls per month', 'percentage', 'hours'", max_length=50)),
                ('start_date', models.DateField()),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('ai_aim_generated', models.BooleanField(default=False, help_text='Was the aim statement AI-assisted?')),
                ('ai_success_score', models.IntegerField(default=0, help_text='AI-predicted success likelihood (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_suggested_hypotheses', models.JSONField(blank=True, help_text='AI-generated hypothesis suggestions stored as JSON', null=True)),
                ('chatbot_interactions', models.IntegerField(default=0, help_text='Number of AI chatbot interactions for guidance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdsa_projects', to='scheduling.carehome')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pdsa_projects', to=settings.AUTH_USER_MODEL)),
                ('lead_user', models.ForeignKey(help_text='Project lead - typically Quality Manager', on_delete=django.db.models.deletion.PROTECT, related_name='led_pdsa_projects', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, help_text='Specific unit if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdsa_projects', to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'PDSA Project',
                'verbose_name_plural': 'PDSA Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDSADataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, help_text='Measured value (e.g., number of falls, compliance percentage)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Context about this measurement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, help_text='Who entered this data?', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='quality_audits.pdsacycle')),
            ],
            options={
                'verbose_name': 'PDSA Data Point',
                'verbose_name_plural': 'PDSA Data Points',
                'ordering': ['measurement_date'],
            },
        ),
        migrations.AddField(
            model_name='pdsacycle',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='quality_audits.pdsaproject'),
        ),
        migrations.CreateModel(
            name='PDSAChatbotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField(help_text="User's question to chatbot")),
                ('chatbot_response', models.TextField(help_text='AI-generated response')),
                ('context_phase', models.CharField(choices=[('PLAN', 'Plan Phase'), ('DO', 'Do Phase'), ('STUDY', 'Study Phase'), ('ACT', 'Act Phase'), ('GENERAL', 'General Question')], default='GENERAL', max_length=20)),
                ('was_helpful', models.BooleanField(blank=True, help_text='Did user find response helpful?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_logs', to='quality_audits.pdsacycle')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_logs', to='quality_audits.pdsaproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdsa_chatbot_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDSA Chatbot Log',
                'verbose_name_plural': 'PDSA Chatbot Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDSATeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text="E.g., 'Data Collector', 'Clinical Lead', 'Analyst'", max_length=50)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='quality_audits.pdsaproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdsa_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDSA Team Member',
                'verbose_name_plural': 'PDSA Team Members',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='pdsaproject',
            index=models.Index(fields=['status', 'priority'], name='quality_aud_status_1d28f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pdsaproject',
            index=models.Index(fields=['care_home', 'status'], name='quality_aud_care_ho_a3fd91_idx'),
        ),
        migrations.AddIndex(
            model_name='pdsaproject',
            index=models.Index(fields=['category'], name='quality_aud_categor_aba2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='pdsadatapoint',
            index=models.Index(fields=['cycle', 'measurement_date'], name='quality_aud_cycle_i_161f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='pdsacycle',
            index=models.Index(fields=['project', 'cycle_number'], name='quality_aud_project_502740_idx'),
        ),
        migrations.AddIndex(
            model_name='pdsacycle',
            index=models.Index(fields=['act_decision'], name='quality_aud_act_dec_f33bbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pdsacycle',
            unique_together={('project', 'cycle_number')},
        ),
    ]
