# Generated by Django 4.2.27 on 2026-01-23 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0059_alter_user_shift_preference'),
        ('experience_feedback', '0003_yousaidwedidaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yousaidwedidaction',
            options={'ordering': ['-feedback_date'], 'verbose_name': 'You Said, We Did Action', 'verbose_name_plural': 'You Said, We Did Actions'},
        ),
        migrations.RemoveIndex(
            model_name='yousaidwedidaction',
            name='experience__care_ho_idx',
        ),
        migrations.RemoveIndex(
            model_name='yousaidwedidaction',
            name='experience__status_idx',
        ),
        migrations.RemoveIndex(
            model_name='yousaidwedidaction',
            name='experience__display_idx',
        ),
        migrations.RemoveField(
            model_name='yousaidwedidaction',
            name='action_date',
        ),
        migrations.RemoveField(
            model_name='yousaidwedidaction',
            name='action_taken_by',
        ),
        migrations.RemoveField(
            model_name='yousaidwedidaction',
            name='communicated_back',
        ),
        migrations.RemoveField(
            model_name='yousaidwedidaction',
            name='communication_details',
        ),
        migrations.RemoveField(
            model_name='yousaidwedidaction',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='yousaidwedidaction',
            name='display_end_date',
        ),
        migrations.RemoveField(
            model_name='yousaidwedidaction',
            name='display_start_date',
        ),
        migrations.RemoveField(
            model_name='yousaidwedidaction',
            name='person_raised',
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='action_taken_date',
            field=models.DateField(blank=True, help_text='When was the action completed?', null=True),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='communicated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='communicated_to_residents',
            field=models.BooleanField(default=False, help_text='Has this been communicated to residents/families?'),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='communication_method',
            field=models.CharField(blank=True, help_text='How was it communicated? (e.g., notice board, newsletter, meeting)', max_length=50),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='display_until',
            field=models.DateField(blank=True, help_text='Display until this date (leave blank for indefinite)', null=True),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='impact_assessment',
            field=models.TextField(blank=True, help_text='What impact did this action have?'),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='related_complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yswda_actions', to='experience_feedback.complaint'),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='related_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yswda_actions', to='experience_feedback.satisfactionsurvey'),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='related_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yswda_actions', to='experience_feedback.feedbacktheme'),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yswda_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yousaidwedidaction',
            name='who_said_it',
            field=models.CharField(blank=True, help_text='Who provided the feedback (optional for anonymity)', max_length=200),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='care_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yswda_actions', to='scheduling.carehome'),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='category',
            field=models.CharField(choices=[('CARE_QUALITY', 'Quality of Care'), ('STAFF', 'Staff & Staffing'), ('ACTIVITIES', 'Activities & Social'), ('MEALS', 'Meals & Nutrition'), ('ENVIRONMENT', 'Environment & Facilities'), ('COMMUNICATION', 'Communication'), ('FAMILY_INVOLVEMENT', 'Family Involvement'), ('DIGNITY_RESPECT', 'Dignity & Respect'), ('SAFETY', 'Safety & Security'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yswda_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='display_on_board',
            field=models.BooleanField(default=True, help_text="Display on 'You Said, We Did' notice board?"),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='feedback_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When was this feedback received?'),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='sentiment',
            field=models.CharField(choices=[('POSITIVE', 'Positive - Compliment'), ('CONCERN', 'Concern - Area for Improvement'), ('COMPLAINT', 'Complaint - Issue to Resolve'), ('SUGGESTION', 'Suggestion - New Idea')], default='CONCERN', max_length=20),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='source_type',
            field=models.CharField(choices=[('SURVEY', 'Satisfaction Survey'), ('COMPLAINT', 'Complaint'), ('MEETING', 'Resident/Family Meeting'), ('INFORMAL', 'Informal Feedback'), ('SUGGESTION_BOX', 'Suggestion Box'), ('CARE_REVIEW', 'Care Review Meeting')], help_text='Where did this feedback come from?', max_length=30),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Feedback Received'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'Action In Progress'), ('COMPLETED', 'Action Completed'), ('ONGOING', 'Ongoing Monitoring'), ('NO_ACTION', 'No Action Required')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='we_did',
            field=models.TextField(blank=True, help_text='What we did in response to this feedback'),
        ),
        migrations.AlterField(
            model_name='yousaidwedidaction',
            name='you_said',
            field=models.TextField(help_text='What residents/families told us (the feedback received)'),
        ),
        migrations.AddIndex(
            model_name='yousaidwedidaction',
            index=models.Index(fields=['care_home', 'display_on_board', 'display_until'], name='experience__care_ho_ae3747_idx'),
        ),
        migrations.AddIndex(
            model_name='yousaidwedidaction',
            index=models.Index(fields=['status', '-feedback_date'], name='experience__status_f8bd77_idx'),
        ),
    ]
