# Generated by Django 4.2.27 on 2026-01-23 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience_feedback', '0004_alter_yousaidwedidaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakeholder_type', models.CharField(choices=[('COMPLAINANT', 'Complainant'), ('RESIDENT', 'Resident'), ('FAMILY_MEMBER', 'Family Member'), ('STAFF_WITNESS', 'Staff Witness'), ('CARE_MANAGER', 'Care Manager'), ('SENIOR_MANAGEMENT', 'Senior Management'), ('EXTERNAL_PROFESSIONAL', 'External Professional'), ('CARE_INSPECTORATE', 'Care Inspectorate'), ('LOCAL_AUTHORITY', 'Local Authority'), ('POLICE', 'Police'), ('OTHER', 'Other')], help_text='Type of stakeholder', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('role_title', models.CharField(blank=True, max_length=100)),
                ('contact_details', models.CharField(blank=True, max_length=200)),
                ('involvement_description', models.TextField(help_text='How is this person involved in the complaint?')),
                ('date_contacted', models.DateField(blank=True, null=True)),
                ('statement_received', models.BooleanField(default=False)),
                ('statement_date', models.DateField(blank=True, null=True)),
                ('statement_notes', models.TextField(blank=True)),
                ('requires_update', models.BooleanField(default=False, help_text='Does this stakeholder require updates on progress?')),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('update_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'), ('MONTHLY', 'Monthly'), ('AS_NEEDED', 'As Needed')], default='WEEKLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='experience_feedback.complaint')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stakeholders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Stakeholder',
                'verbose_name_plural': 'Complaint Stakeholders',
                'ordering': ['complaint', 'stakeholder_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintInvestigationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('INITIAL_REVIEW', 'Initial Review & Triage'), ('EVIDENCE_GATHERING', 'Evidence Gathering'), ('STAFF_INTERVIEWS', 'Staff Interviews'), ('RESIDENT_INTERVIEW', 'Resident/Family Interview'), ('DOCUMENTATION_REVIEW', 'Documentation Review'), ('ROOT_CAUSE_ANALYSIS', 'Root Cause Analysis'), ('ACTION_PLAN', 'Action Plan Development'), ('IMPLEMENTATION', 'Action Implementation'), ('FOLLOW_UP', 'Follow-up & Verification'), ('CLOSURE', 'Closure & Feedback')], help_text='Stage of the investigation process', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, help_text='Findings from this investigation stage')),
                ('evidence_collected', models.TextField(blank=True, help_text='Evidence collected during this stage')),
                ('actions_required', models.TextField(blank=True, help_text='Actions required as a result of this stage')),
                ('sequence_order', models.IntegerField(default=0, help_text='Order in the investigation process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_investigation_stages', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_stages', to='experience_feedback.complaint')),
            ],
            options={
                'verbose_name': 'Investigation Stage',
                'verbose_name_plural': 'Investigation Stages',
                'ordering': ['complaint', 'sequence_order'],
            },
        ),
    ]
