# Generated by Django 4.2.27 on 2026-01-23 23:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0059_alter_user_shift_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience_feedback', '0005_complaintstakeholder_complaintinvestigationstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDistributionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(help_text='Name for this distribution schedule', max_length=200)),
                ('survey_type', models.CharField(choices=[('RESIDENT_ADMISSION', 'Resident - Admission'), ('RESIDENT_ONGOING', 'Resident - Ongoing Care'), ('RESIDENT_DISCHARGE', 'Resident - Discharge'), ('FAMILY_ADMISSION', 'Family - Admission'), ('FAMILY_ONGOING', 'Family - Ongoing Care'), ('FAMILY_BEREAVEMENT', 'Family - Bereavement'), ('STAFF_EXPERIENCE', 'Staff - Experience Survey'), ('PROFESSIONAL_PARTNERSHIP', 'Professional - Partnership Survey')], help_text='Type of survey to distribute', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Is this schedule currently active?')),
                ('distribution_frequency', models.CharField(choices=[('ADMISSION', 'On Admission'), ('DISCHARGE', 'On Discharge'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUAL', 'Every 6 Months'), ('ANNUAL', 'Annually')], default='QUARTERLY', help_text='How often to send surveys', max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week for weekly surveys', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly/quarterly/annual surveys', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('days_after_event', models.IntegerField(default=7, help_text='Days after admission/discharge to send survey')),
                ('send_via_email', models.BooleanField(default=True, help_text='Send survey links via email')),
                ('send_via_sms', models.BooleanField(default=False, help_text='Send survey links via SMS')),
                ('print_qr_code', models.BooleanField(default=True, help_text='Generate QR code for printed materials')),
                ('send_to_residents', models.BooleanField(default=True, help_text='Send to residents directly')),
                ('send_to_families', models.BooleanField(default=True, help_text='Send to family contacts')),
                ('email_subject', models.CharField(default="We'd love your feedback", help_text='Email subject line', max_length=200)),
                ('email_intro', models.TextField(default='Your feedback helps us improve our care. Please take a few minutes to complete this survey.', help_text='Introduction text for email')),
                ('send_reminder', models.BooleanField(default=True, help_text='Send reminder to non-respondents')),
                ('reminder_days', models.IntegerField(default=7, help_text='Days after initial send to send reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.DateTimeField(blank=True, help_text='When was this schedule last executed?', null=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='When will this schedule next run?', null=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_schedules', to='scheduling.carehome')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_survey_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Survey Distribution Schedule',
                'verbose_name_plural': 'Survey Distribution Schedules',
                'ordering': ['care_home', 'survey_type'],
            },
        ),
        migrations.CreateModel(
            name='SurveyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('RESIDENT_ADMISSION', 'Resident - Admission'), ('RESIDENT_ONGOING', 'Resident - Ongoing Care'), ('RESIDENT_DISCHARGE', 'Resident - Discharge'), ('FAMILY_ADMISSION', 'Family - Admission'), ('FAMILY_ONGOING', 'Family - Ongoing Care'), ('FAMILY_BEREAVEMENT', 'Family - Bereavement'), ('STAFF_EXPERIENCE', 'Staff - Experience Survey'), ('PROFESSIONAL_PARTNERSHIP', 'Professional - Partnership Survey')], max_length=30)),
                ('recipient_name', models.CharField(help_text='Name of person receiving survey', max_length=200)),
                ('recipient_email', models.EmailField(blank=True, help_text='Email address for survey link', max_length=254)),
                ('recipient_phone', models.CharField(blank=True, help_text='Phone number for SMS survey link', max_length=20)),
                ('recipient_type', models.CharField(choices=[('RESIDENT', 'Resident'), ('FAMILY', 'Family Member'), ('POWER_OF_ATTORNEY', 'Power of Attorney'), ('OTHER', 'Other')], default='FAMILY', max_length=20)),
                ('survey_token', models.CharField(help_text='Unique token for survey link', max_length=64, unique=True)),
                ('qr_code_generated', models.BooleanField(default=False, help_text='Has QR code been generated?')),
                ('qr_code_path', models.CharField(blank=True, help_text='Path to generated QR code image', max_length=255)),
                ('sent_date', models.DateTimeField(blank=True, help_text='When was survey sent?', null=True)),
                ('sent_via', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('BOTH', 'Email & SMS'), ('QR_PRINTED', 'QR Code Printed'), ('MANUAL', 'Manual Distribution')], max_length=20)),
                ('response_received', models.BooleanField(default=False, help_text='Has recipient responded?')),
                ('response_date', models.DateTimeField(blank=True, help_text='When did recipient respond?', null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Has reminder been sent?')),
                ('reminder_sent_date', models.DateTimeField(blank=True, null=True)),
                ('email_delivered', models.BooleanField(default=False, help_text='Was email successfully delivered?')),
                ('email_opened', models.BooleanField(default=False, help_text='Did recipient open email?')),
                ('email_bounced', models.BooleanField(default=False, help_text='Did email bounce?')),
                ('sms_delivered', models.BooleanField(default=False, help_text='Was SMS successfully delivered?')),
                ('sms_failed', models.BooleanField(default=False, help_text='Did SMS fail to send?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Any notes about this distribution')),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_distributions', to='scheduling.carehome')),
                ('completed_survey', models.ForeignKey(blank=True, help_text='Link to completed survey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_record', to='experience_feedback.satisfactionsurvey')),
                ('resident', models.ForeignKey(help_text='Resident this survey is about', on_delete=django.db.models.deletion.CASCADE, related_name='survey_distributions', to='scheduling.resident')),
                ('schedule', models.ForeignKey(blank=True, help_text='The schedule that generated this distribution (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='experience_feedback.surveydistributionschedule')),
            ],
            options={
                'verbose_name': 'Survey Distribution',
                'verbose_name_plural': 'Survey Distributions',
                'ordering': ['-sent_date'],
                'indexes': [models.Index(fields=['care_home', '-sent_date'], name='experience__care_ho_029bfa_idx'), models.Index(fields=['survey_token'], name='experience__survey__cc5522_idx'), models.Index(fields=['response_received', '-sent_date'], name='experience__respons_873355_idx')],
            },
        ),
    ]
