# Generated by Django for experience_feedback app

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),  # Adjust if needed
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experience_feedback', '0006_surveydistributionschedule_surveydistribution'),
    ]

    operations = [
        # Family Member Model
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('relationship', models.CharField(help_text='e.g., Daughter, Son, Spouse, Power of Attorney', max_length=100)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Is this the primary family contact for the resident?')),
                ('is_power_of_attorney', models.BooleanField(default=False, help_text='Does this person have Power of Attorney?')),
                ('portal_access_granted', models.BooleanField(default=True)),
                ('access_level', models.CharField(choices=[('FULL', 'Full Access'), ('LIMITED', 'Limited Access'), ('VIEW_ONLY', 'View Only')], default='FULL', max_length=20)),
                ('receive_email_notifications', models.BooleanField(default=True)),
                ('receive_sms_notifications', models.BooleanField(default=False)),
                ('receive_survey_requests', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members_created', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(help_text='Resident this family member is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='scheduling.resident')),
                ('user', models.OneToOneField(help_text='Django user account for family member login', on_delete=django.db.models.deletion.CASCADE, related_name='family_member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ['resident', 'last_name', 'first_name'],
            },
        ),
        # Family Message Model
        migrations.CreateModel(
            name='FamilyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Enquiry'), ('CARE', 'Care Question'), ('MEDICAL', 'Medical Information'), ('VISIT', 'Visit Arrangement'), ('ACTIVITIES', 'Activities & Social'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other')], default='GENERAL', max_length=50)),
                ('staff_responded', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('read_by_staff', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_messages', to='scheduling.carehome')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='experience_feedback.familymember')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_messages', to='scheduling.resident')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_messages_responded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Message',
                'verbose_name_plural': 'Family Messages',
                'ordering': ['-sent_date'],
            },
        ),
        # Family Portal Activity Model
        migrations.CreateModel(
            name='FamilyPortalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW_DASHBOARD', 'Viewed Dashboard'), ('VIEW_SURVEYS', 'Viewed Surveys'), ('COMPLETE_SURVEY', 'Completed Survey'), ('SEND_MESSAGE', 'Sent Message'), ('VIEW_MESSAGE', 'Viewed Message'), ('DOWNLOAD_DOCUMENT', 'Downloaded Document'), ('VIEW_CARE_PLAN', 'Viewed Care Plan')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_activity', to='experience_feedback.familymember')),
            ],
            options={
                'verbose_name': 'Family Portal Activity',
                'verbose_name_plural': 'Family Portal Activities',
                'ordering': ['-timestamp'],
            },
        ),
        # Indexes
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['resident', 'is_primary_contact'], name='experience__residen_a7b4c1_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['email'], name='experience__email_5f9d82_idx'),
        ),
        migrations.AddIndex(
            model_name='familymessage',
            index=models.Index(fields=['care_home', '-sent_date'], name='experience__care_ho_3e8f91_idx'),
        ),
        migrations.AddIndex(
            model_name='familymessage',
            index=models.Index(fields=['resident', '-sent_date'], name='experience__residen_7c9e42_idx'),
        ),
        migrations.AddIndex(
            model_name='familymessage',
            index=models.Index(fields=['staff_responded', '-sent_date'], name='experience__staff_r_8a2f73_idx'),
        ),
        migrations.AddIndex(
            model_name='familyportalactivity',
            index=models.Index(fields=['family_member', '-timestamp'], name='experience__family__9b3e61_idx'),
        ),
        migrations.AddIndex(
            model_name='familyportalactivity',
            index=models.Index(fields=['activity_type', '-timestamp'], name='experience__activit_4d7c52_idx'),
        ),
    ]
