# Generated by Django 4.2.27 on 2026-01-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience_feedback', '0007_familymember_familymessage_familyportalactivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='familymember',
            new_name='experience__residen_e9ed1e_idx',
            old_name='experience__residen_a7b4c1_idx',
        ),
        migrations.RenameIndex(
            model_name='familymember',
            new_name='experience__email_dd5020_idx',
            old_name='experience__email_5f9d82_idx',
        ),
        migrations.RenameIndex(
            model_name='familymessage',
            new_name='experience__care_ho_b3cc1c_idx',
            old_name='experience__care_ho_3e8f91_idx',
        ),
        migrations.RenameIndex(
            model_name='familymessage',
            new_name='experience__residen_95e170_idx',
            old_name='experience__residen_7c9e42_idx',
        ),
        migrations.RenameIndex(
            model_name='familymessage',
            new_name='experience__staff_r_2fdfd1_idx',
            old_name='experience__staff_r_8a2f73_idx',
        ),
        migrations.RenameIndex(
            model_name='familyportalactivity',
            new_name='experience__family__d64768_idx',
            old_name='experience__family__9b3e61_idx',
        ),
        migrations.RenameIndex(
            model_name='familyportalactivity',
            new_name='experience__activit_d8227c_idx',
            old_name='experience__activit_4d7c52_idx',
        ),
    ]
