# Generated by Django 4.2.27 on 2026-01-25 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance_kpis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('MODULE_1', 'Module 1: Quality Audits'), ('MODULE_2', 'Module 2: Incident & Safety'), ('MODULE_3', 'Module 3: Experience & Feedback'), ('MODULE_4', 'Module 4: Training & Competency'), ('MODULE_5', 'Module 5: Policies & Procedures'), ('MODULE_6', 'Module 6: Risk Management'), ('MODULE_7', 'Module 7: Dashboard')], max_length=20)),
                ('warning_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('critical_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comparison_operator', models.CharField(choices=[('GT', 'Greater Than'), ('LT', 'Less Than'), ('GTE', 'Greater Than or Equal'), ('LTE', 'Less Than or Equal')], max_length=3)),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_recipients', models.ManyToManyField(blank=True, related_name='alert_threshold_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Threshold',
                'verbose_name_plural': 'Alert Thresholds',
                'ordering': ['module', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='KPIAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('module', models.CharField(choices=[('MODULE_1', 'Module 1: Quality Audits'), ('MODULE_2', 'Module 2: Incident & Safety'), ('MODULE_3', 'Module 3: Experience & Feedback'), ('MODULE_4', 'Module 4: Training & Competency'), ('MODULE_5', 'Module 5: Policies & Procedures'), ('MODULE_6', 'Module 6: Risk Management'), ('MODULE_7', 'Module 7: Dashboard')], max_length=20)),
                ('metric_name', models.CharField(max_length=100)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_kpi_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Alert',
                'verbose_name_plural': 'KPI Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='performance_status_2421c3_idx'), models.Index(fields=['module'], name='performance_module_12378b_idx'), models.Index(fields=['created_at'], name='performance_created_b99cd1_idx')],
            },
        ),
    ]
