# Generated by Django 5.2.7 on 2025-12-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_add_permission_level'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['date', 'status'], name='scheduling__date_ef48d3_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['unit', 'date', 'status'], name='scheduling__unit_id_3f34f1_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['care_home', 'is_active'], name='scheduling__care_ho_16265f_idx'),
        ),
    ]
