# Generated by Django 4.2.27 on 2025-12-27 23:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0028_usertip_onboardingtourstep_onboardingprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeCoverageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(max_length=50)),
                ('required_role', models.CharField(help_text='RN, SSW, HCA, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Responses'), ('FILLED', 'Shift Filled'), ('UNFILLED', 'Could Not Fill'), ('CANCELLED', 'Request Cancelled')], default='PENDING', max_length=20)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('total_contacted', models.IntegerField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('total_acceptances', models.IntegerField(default=0)),
                ('time_to_fill_minutes', models.IntegerField(blank=True, help_text='How long it took to fill this shift (minutes)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coverage_requests', to=settings.AUTH_USER_MODEL)),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_shifts_filled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime Coverage Request',
                'verbose_name_plural': 'Overtime Coverage Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffOvertimePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_for_overtime', models.BooleanField(default=False, help_text='Is this staff member willing to work overtime?')),
                ('available_early_shifts', models.BooleanField(default=True)),
                ('available_late_shifts', models.BooleanField(default=True)),
                ('available_night_shifts', models.BooleanField(default=True)),
                ('available_weekdays', models.BooleanField(default=True)),
                ('available_weekends', models.BooleanField(default=True)),
                ('preferred_contact_method', models.CharField(choices=[('SMS', 'Text Message'), ('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('APP', 'Mobile App')], default='SMS', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Mobile number for SMS alerts', max_length=20)),
                ('total_requests_sent', models.IntegerField(default=0)),
                ('total_requests_accepted', models.IntegerField(default=0)),
                ('total_shifts_worked', models.IntegerField(default=0)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('last_worked_overtime', models.DateTimeField(blank=True, null=True)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of requests accepted', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_hours_per_week', models.IntegerField(blank=True, help_text='Maximum OT hours willing to work per week', null=True)),
                ('min_notice_hours', models.IntegerField(default=2, help_text='Minimum notice required (hours)')),
                ('notes', models.TextField(blank=True, help_text='Additional preferences or constraints')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_preference', to=settings.AUTH_USER_MODEL)),
                ('willing_to_work_at', models.ManyToManyField(blank=True, help_text='Which homes is this staff member willing to work at?', related_name='overtime_staff', to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Staff Overtime Preference',
                'verbose_name_plural': 'Staff Overtime Preferences',
                'ordering': ['-acceptance_rate', '-total_shifts_worked'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeCoverageResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('contact_method', models.CharField(choices=[('SMS', 'Text Message'), ('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('APP', 'Mobile App')], max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('NO_RESPONSE', 'No Response')], default='NO_RESPONSE', max_length=20)),
                ('decline_reason', models.CharField(blank=True, choices=[('UNAVAILABLE', 'Not Available'), ('TOO_SHORT_NOTICE', 'Too Short Notice'), ('DIFFERENT_HOME', 'Prefer Different Home'), ('DIFFERENT_SHIFT', 'Prefer Different Shift'), ('PERSONAL', 'Personal Reasons'), ('OTHER', 'Other')], max_length=100)),
                ('reliability_score_when_sent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='scheduling.overtimecoveragerequest')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime Coverage Response',
                'verbose_name_plural': 'Overtime Coverage Responses',
                'ordering': ['-contacted_at'],
                'unique_together': {('request', 'staff')},
            },
        ),
        migrations.AddField(
            model_name='overtimecoveragerequest',
            name='staff_contacted',
            field=models.ManyToManyField(related_name='overtime_requests_received', through='scheduling.OvertimeCoverageResponse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimecoveragerequest',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='scheduling.unit'),
        ),
    ]
