# Generated by Django 4.2.27 on 2025-12-30 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0037_costanalysis_budgetforecast_agencycostcomparison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_type', models.CharField(choices=[('FIRST_AID', 'First Aid'), ('MANUAL_HANDLING', 'Manual Handling'), ('FIRE_SAFETY', 'Fire Safety'), ('FOOD_HYGIENE', 'Food Hygiene'), ('MEDICATION', 'Medication Administration'), ('SAFEGUARDING', 'Safeguarding'), ('INFECTION_CONTROL', 'Infection Control'), ('DEMENTIA_CARE', 'Dementia Care'), ('PALLIATIVE_CARE', 'Palliative Care'), ('PVG', 'PVG Scheme'), ('SSSC', 'SSSC Registration'), ('OTHER', 'Other')], max_length=50)),
                ('certification_name', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('renewal_date', models.DateField(blank=True, help_text='Expected renewal date', null=True)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending Renewal')], default='VALID', max_length=20)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('days_before_expiry_alert', models.IntegerField(default=30, help_text='Days before expiry to send alert')),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certifications', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Certification',
                'verbose_name_plural': 'Staff Certifications',
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['staff_member', 'expiry_date'], name='scheduling__staff_m_40f5ad_idx'), models.Index(fields=['certification_type', 'status'], name='scheduling__certifi_6bd401_idx'), models.Index(fields=['expiry_date', 'status'], name='scheduling__expiry__1b2835_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('TRAINING', 'Training Compliance'), ('CERTIFICATION', 'Certification Check'), ('STAFFING_RATIO', 'Staffing Ratio'), ('DOCUMENTATION', 'Documentation Review'), ('HEALTH_SAFETY', 'Health & Safety'), ('CARE_STANDARDS', 'Care Standards'), ('MEDICATION', 'Medication Management'), ('FIRE_SAFETY', 'Fire Safety'), ('INFECTION_CONTROL', 'Infection Control')], max_length=50)),
                ('check_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('check_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('WARNING', 'Warning'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('compliance_score', models.DecimalField(blank=True, decimal_places=2, help_text='Compliance score (0-100%)', max_digits=5, null=True)),
                ('findings', models.TextField(blank=True, help_text='Detailed findings from the check')),
                ('violations_found', models.IntegerField(default=0)),
                ('action_required', models.BooleanField(default=False)),
                ('action_plan', models.TextField(blank=True)),
                ('action_deadline', models.DateField(blank=True, null=True)),
                ('action_completed', models.BooleanField(default=False)),
                ('action_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_checks', to='scheduling.carehome')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_checks_performed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regulatory_checks_reviewed', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_checks', to='scheduling.unit')),
            ],
            options={
                'verbose_name': 'Regulatory Check',
                'verbose_name_plural': 'Regulatory Checks',
                'ordering': ['-check_date'],
                'indexes': [models.Index(fields=['care_home', '-check_date'], name='scheduling__care_ho_6bf016_idx'), models.Index(fields=['check_type', 'status'], name='scheduling__check_t_ac7ea0_idx'), models.Index(fields=['status', 'severity'], name='scheduling__status_8e31b2_idx'), models.Index(fields=['due_date', 'action_completed'], name='scheduling__due_dat_1555b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('OVERRIDE', 'Override')], max_length=20)),
                ('entity_type', models.CharField(choices=[('SHIFT', 'Shift'), ('STAFF', 'Staff'), ('LEAVE', 'Leave Request'), ('SWAP', 'Shift Swap'), ('CERTIFICATION', 'Certification'), ('COMPLIANCE', 'Compliance Check'), ('REPORT', 'Report'), ('COST', 'Cost Analysis'), ('FORECAST', 'Budget Forecast'), ('USER', 'User'), ('SYSTEM', 'System')], max_length=50)),
                ('entity_id', models.IntegerField(blank=True, help_text='ID of the affected entity', null=True)),
                ('description', models.TextField()),
                ('before_state', models.JSONField(blank=True, help_text='State before change', null=True)),
                ('after_state', models.JSONField(blank=True, help_text='State after change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Contains sensitive data')),
                ('requires_review', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='scheduling.carehome')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail Entry',
                'verbose_name_plural': 'Audit Trail Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['care_home', '-timestamp'], name='scheduling__care_ho_55fa9b_idx'), models.Index(fields=['user', '-timestamp'], name='scheduling__user_id_f32b1a_idx'), models.Index(fields=['action_type', 'entity_type'], name='scheduling__action__91527d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='scheduling__entity__dca36d_idx'), models.Index(fields=['is_sensitive', 'reviewed'], name='scheduling__is_sens_7604df_idx')],
            },
        ),
    ]
