# Generated by Django 4.2.27 on 2025-12-30 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0039_staffperformance_performancereview_attendancerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('SEASONAL', 'Seasonal (e.g., summer, winter)'), ('MONTHLY', 'Monthly recurring'), ('WEEKLY', 'Weekly recurring'), ('EVENT_BASED', 'Event-based (e.g., school holidays)'), ('RANDOM', 'No clear pattern')], max_length=20)),
                ('pattern_name', models.CharField(max_length=100)),
                ('pattern_description', models.TextField()),
                ('typical_duration_days', models.IntegerField(help_text='Typical leave duration')),
                ('frequency_per_year', models.DecimalField(decimal_places=2, help_text='How often per year', max_digits=5)),
                ('preferred_months', models.JSONField(blank=True, default=list, help_text='List of preferred months (1-12)')),
                ('preferred_days_of_week', models.JSONField(blank=True, default=list, help_text='List of preferred days (0-6)')),
                ('occurrences_found', models.IntegerField(default=0, help_text='Number of times pattern occurred')),
                ('pattern_strength', models.DecimalField(decimal_places=2, default=0, help_text='0-100% strength', max_digits=5)),
                ('last_occurrence', models.DateField(blank=True, null=True)),
                ('analyzed_from', models.DateField()),
                ('analyzed_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pattern_strength', '-created_at'],
                'indexes': [models.Index(fields=['staff_member', 'pattern_type'], name='scheduling__staff_m_be6a11_idx'), models.Index(fields=['care_home', '-pattern_strength'], name='scheduling__care_ho_f90891_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveImpactAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_leave_days', models.IntegerField(default=0)),
                ('staff_on_leave_count', models.IntegerField(default=0)),
                ('concurrent_leave_peak', models.IntegerField(default=0, help_text='Max staff on leave at once')),
                ('concurrent_leave_peak_date', models.DateField(blank=True, null=True)),
                ('impact_severity', models.CharField(choices=[('MINIMAL', 'Minimal (<10% impact)'), ('MODERATE', 'Moderate (10-25% impact)'), ('SIGNIFICANT', 'Significant (25-50% impact)'), ('SEVERE', 'Severe (>50% impact)')], default='MINIMAL', max_length=20)),
                ('coverage_gap_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_hours_required', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('agency_shifts_needed', models.IntegerField(default=0)),
                ('estimated_cost_impact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('understaffing_days', models.IntegerField(default=0, help_text='Days below minimum staffing')),
                ('critical_skill_gaps', models.TextField(blank=True, help_text='Missing critical skills/roles')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('mitigation_strategies', models.TextField(blank=True)),
                ('recommended_hires', models.IntegerField(default=0, help_text='Suggested additional staff')),
                ('suggested_policy_changes', models.TextField(blank=True)),
                ('impact_by_day', models.JSONField(blank=True, default=dict, help_text='Daily impact breakdown')),
                ('affected_staff_list', models.JSONField(blank=True, default=list, help_text='List of affected staff IDs')),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.unit')),
            ],
            options={
                'ordering': ['-analysis_date', '-risk_level'],
                'indexes': [models.Index(fields=['care_home', 'period_start'], name='scheduling__care_ho_0a8ff9_idx'), models.Index(fields=['risk_level', 'impact_severity'], name='scheduling__risk_le_7e20f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('PERSONAL', 'Personal Leave'), ('ALL', 'All Leave Types')], default='ALL', max_length=20)),
                ('forecast_date', models.DateField()),
                ('forecast_start', models.DateField()),
                ('forecast_end', models.DateField()),
                ('predicted_days', models.IntegerField(help_text='Predicted leave days in period')),
                ('predicted_peak_month', models.CharField(blank=True, help_text='Month with highest predicted leave', max_length=20)),
                ('predicted_pattern', models.TextField(blank=True, help_text='Description of predicted pattern')),
                ('historical_period_months', models.IntegerField(default=12, help_text='Months of history analyzed')),
                ('total_historical_days', models.IntegerField(default=0)),
                ('average_days_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High (>80%)'), ('MEDIUM', 'Medium (60-80%)'), ('LOW', 'Low (<60%)')], default='MEDIUM', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100%', max_digits=5)),
                ('prediction_range_min', models.IntegerField(help_text='Minimum predicted days')),
                ('prediction_range_max', models.IntegerField(help_text='Maximum predicted days')),
                ('seasonal_factor', models.BooleanField(default=False, help_text='Seasonal pattern detected')),
                ('trend_factor', models.CharField(blank=True, help_text='INCREASING/DECREASING/STABLE', max_length=20)),
                ('special_events', models.TextField(blank=True, help_text='Known events affecting forecast')),
                ('impact_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('recommended_actions', models.TextField(blank=True)),
                ('coverage_requirements', models.TextField(blank=True, help_text='Suggested coverage needs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.carehome')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-forecast_date', '-created_at'],
                'indexes': [models.Index(fields=['staff_member', 'forecast_date'], name='scheduling__staff_m_0c305a_idx'), models.Index(fields=['care_home', 'forecast_type'], name='scheduling__care_ho_a4a4ec_idx'), models.Index(fields=['confidence_level', 'impact_level'], name='scheduling__confide_06b884_idx')],
            },
        ),
    ]
