# Generated by Django 4.2.27 on 2026-01-02 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0054_update_unit_choices_correct_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Filter name (e.g., "My Team Sickness", "This Week Rota")', max_length=100)),
                ('filter_type', models.CharField(choices=[('staff', 'Staff Search'), ('rota', 'Rota Filter'), ('leave', 'Leave Requests'), ('training', 'Training Records'), ('sickness', 'Sickness Records'), ('reports', 'Report Filters')], help_text='Type of filter/search', max_length=20)),
                ('filter_params', models.JSONField(help_text='Saved filter parameters as JSON')),
                ('is_default', models.BooleanField(default=False, help_text='Auto-apply this filter when viewing the page')),
                ('is_shared', models.BooleanField(default=False, help_text='Share with other users in the same care home')),
                ('use_count', models.IntegerField(default=0, help_text='How many times this filter has been applied')),
                ('last_used', models.DateTimeField(blank=True, help_text='When this filter was last applied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Search Filter',
                'verbose_name_plural': 'Saved Search Filters',
                'db_table': 'scheduling_saved_search_filter',
                'ordering': ['-last_used', '-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BulkOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('leave_approve', 'Bulk Leave Approval'), ('leave_reject', 'Bulk Leave Rejection'), ('training_assign', 'Bulk Training Assignment'), ('training_complete', 'Bulk Training Completion'), ('shift_assign', 'Bulk Shift Assignment'), ('staff_notify', 'Bulk Staff Notification')], max_length=30)),
                ('item_count', models.IntegerField(help_text='Number of items processed')),
                ('success_count', models.IntegerField(default=0, help_text='Number of successful operations')),
                ('failure_count', models.IntegerField(default=0, help_text='Number of failed operations')),
                ('details', models.JSONField(help_text='Operation details (IDs, reasons, etc.)')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Operation Log',
                'verbose_name_plural': 'Bulk Operation Logs',
                'db_table': 'scheduling_bulk_operation_log',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_id', models.CharField(help_text='Unique identifier for the widget (e.g., sickness_widget, training_widget)', max_length=50)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the widget is visible on the dashboard')),
                ('position', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Widget Preference',
                'verbose_name_plural': 'Dashboard Widget Preferences',
                'db_table': 'scheduling_dashboard_widget_preference',
                'ordering': ['position', 'widget_id'],
                'unique_together': {('user', 'widget_id')},
            },
        ),
    ]
