# Generated by Django 5.2.7 on 2025-10-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_role_required_headcount_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B'), ('C', 'Team C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.unit'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SCW', 'Social Care Worker'), ('SCA', 'Social Care Assistant'), ('SSCW', 'Senior Social Care Worker'), ('ACTC', 'Activities Coordinator'), ('ACTA', 'Activities Assistant'), ('SEC', 'Security'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(choices=[('DEMENTIA', 'Dementia Unit'), ('BLUE', 'Blue Unit'), ('GREEN', 'Green Unit'), ('ROSE', 'Rose Unit'), ('VIOLET', 'Violet Unit'), ('ORANGE', 'Orange Unit'), ('PEACH', 'Peach Unit'), ('GRAPE', 'Grape Unit'), ('ADMIN', 'Administration')], max_length=50, unique=True),
        ),
    ]
