# Generated by Django 5.2.7 on 2025-10-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_user_team_user_unit_alter_role_name_alter_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift_preference',
            field=models.CharField(blank=True, choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('OPERATIONS_MANAGER', 'Operations Manager'), ('SSCW', 'Senior Social Care Worker'), ('SCW', 'Social Care Worker'), ('SCA', 'Social Care Assistant')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shifttype',
            name='name',
            field=models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift')], max_length=50, unique=True),
        ),
    ]
