# Generated by Django 5.2.7 on 2025-11-27 20:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduling', '0009_staffingrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short code for the rule (e.g., WTD_48_HOURS)', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('WORKING_TIME', 'Working Time Directive'), ('REST_PERIOD', 'Rest Period Requirements'), ('ANNUAL_LEAVE', 'Annual Leave Entitlement'), ('STAFFING_LEVELS', 'Minimum Staffing Levels'), ('TRAINING', 'Training & Certification'), ('DATA_PROTECTION', 'Data Protection (GDPR)'), ('HEALTH_SAFETY', 'Health & Safety'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('parameters', models.JSONField(default=dict, help_text='Rule-specific parameters')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('remediation_steps', models.TextField(blank=True, help_text='Steps to resolve violations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(default=django.utils.timezone.now)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('violations_found', models.IntegerField(default=0)),
                ('items_checked', models.IntegerField(default=0)),
                ('check_results', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='scheduling.compliancerule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Informational')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ACCEPTED_RISK', 'Accepted Risk'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_violations', to=settings.AUTH_USER_MODEL)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_violations', to=settings.AUTH_USER_MODEL)),
                ('compliance_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='scheduling.compliancecheck')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.compliancerule')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DataChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('APPROVE', 'Approved'), ('DENY', 'Denied'), ('CANCEL', 'Cancelled')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempt', models.CharField(blank=True, help_text='Username used (for failed attempts)', max_length=150, null=True)),
                ('access_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Failed Login'), ('SESSION_EXPIRED', 'Session Expired'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY_ACTIVITY', 'Daily Activity Log'), ('WEEKLY_SUMMARY', 'Weekly Summary'), ('MONTHLY_COMPLIANCE', 'Monthly Compliance Report'), ('USER_ACTIVITY', 'User Activity Report'), ('DATA_CHANGES', 'Data Changes Report'), ('COMPLIANCE_VIOLATIONS', 'Compliance Violations Report'), ('SHIFT_AUDIT', 'Shift Audit Report'), ('LEAVE_AUDIT', 'Leave Request Audit'), ('CUSTOM', 'Custom Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='GENERATING', max_length=20)),
                ('report_data', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='audit_reports/')),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('total_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'generated_at'], name='scheduling__report__7764ff_idx'), models.Index(fields=['generated_by', 'generated_at'], name='scheduling__generat_5c7005_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['rule', 'check_date'], name='scheduling__rule_id_ad32d6_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancecheck',
            index=models.Index(fields=['status', 'started_at'], name='scheduling__status_a71c22_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceviolation',
            index=models.Index(fields=['status', 'severity'], name='scheduling__status_47164b_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceviolation',
            index=models.Index(fields=['affected_user', 'status'], name='scheduling__affecte_f039c8_idx'),
        ),
        migrations.AddIndex(
            model_name='datachangelog',
            index=models.Index(fields=['content_type', 'object_id'], name='scheduling__content_d1ea19_idx'),
        ),
        migrations.AddIndex(
            model_name='datachangelog',
            index=models.Index(fields=['user', 'timestamp'], name='scheduling__user_id_d6dede_idx'),
        ),
        migrations.AddIndex(
            model_name='datachangelog',
            index=models.Index(fields=['action', 'timestamp'], name='scheduling__action_510689_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='scheduling__user_id_fcea91_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccesslog',
            index=models.Index(fields=['access_type', 'timestamp'], name='scheduling__access__904402_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccesslog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='scheduling__ip_addr_2f25ae_idx'),
        ),
    ]
