# Generated by Django 5.2.7 on 2025-12-12 11:41

from django.db import migrations, models
import django.db.models.deletion


def assign_units_to_orchard_grove(apps, schema_editor):
    """
    Assign all existing units to Orchard Grove care home.
    """
    Unit = apps.get_model('scheduling', 'Unit')
    CareHome = apps.get_model('scheduling', 'CareHome')
    
    # Get Orchard Grove
    try:
        orchard_grove = CareHome.objects.get(name='ORCHARD_GROVE')
    except CareHome.DoesNotExist:
        # If Orchard Grove doesn't exist, skip this migration
        print("WARNING: Orchard Grove not found. Run 'python3 manage.py initialize_care_homes' first.")
        return
    
    # Assign all units to Orchard Grove
    units_updated = Unit.objects.all().update(care_home=orchard_grove)
    print(f"✅ Assigned {units_updated} units to Orchard Grove")


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_automated_workflow_and_multi_home'),
    ]

    operations = [
        # Step 1: Add care_home field (nullable initially)
        migrations.AddField(
            model_name='unit',
            name='care_home',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='units',
                to='scheduling.carehome',
                help_text='Care home this unit belongs to'
            ),
        ),
        # Step 2: Assign existing units to Orchard Grove
        migrations.RunPython(
            assign_units_to_orchard_grove,
            reverse_code=migrations.RunPython.noop
        ),
        # Step 3: Make care_home required (non-nullable)
        migrations.AlterField(
            model_name='unit',
            name='care_home',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='units',
                to='scheduling.carehome',
                help_text='Care home this unit belongs to'
            ),
        ),
    ]
