# Generated by Django 5.2.7 on 2025-12-19 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0022_demofeedback_featurerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text="User's query text")),
                ('success', models.BooleanField(default=False, help_text='Whether query was understood and answered')),
                ('response_type', models.CharField(blank=True, choices=[('vacancy', 'Vacancy Report'), ('staff_query', 'Staff Query'), ('careplan', 'Care Plan Query'), ('home_performance', 'Home Performance'), ('staffing_report', 'Staffing Report'), ('leave_report', 'Leave Report'), ('sickness', 'Sickness Report'), ('shortage', 'Staffing Shortage'), ('agency', 'Agency Usage'), ('error', 'Error/Unknown')], max_length=30, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if query failed', null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scheduling__created_6fd89e_idx'), models.Index(fields=['success', '-created_at'], name='scheduling__success_d8269c_idx'), models.Index(fields=['response_type', '-created_at'], name='scheduling__respons_bc4974_idx')],
            },
        ),
    ]
