# Generated by Django 4.2.27 on 2025-12-30 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0045_alertrule_errorlog_healthcheckendpoint_systemuptime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='Search query entered by user', max_length=255)),
                ('search_type', models.CharField(default='all', help_text='Type of search: all, staff, shifts, leave, homes', max_length=50)),
                ('result_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the search', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Analytics',
                'verbose_name_plural': 'Search Analytics',
                'db_table': 'scheduling_search_analytics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='scheduling__timesta_8ea7f3_idx'), models.Index(fields=['query'], name='scheduling__query_f5b9c3_idx'), models.Index(fields=['user'], name='scheduling__user_id_527546_idx')],
            },
        ),
    ]
