# Generated by Django 4.2.27 on 2026-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0063_create_staffcertification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('HOS', 'Head of Service'), ('IDI', 'Improvement, Development & Innovation Manager'), ('SM', 'Service Manager'), ('OM', 'Operations Manager'), ('SSCW', 'Senior Social Care Worker'), ('SCW', 'Social Care Worker'), ('SCA', 'Social Care Assistant')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission_level',
            field=models.CharField(choices=[('FULL', 'Full Access - HOS/IDI/SM/OM can approve, manage rotas, view all homes portfolio-wide'), ('MOST', 'Most Access - SSCW can view schedules, team data, submit requests'), ('LIMITED', 'Limited Access - Staff can view own info, submit requests only')], default='LIMITED', help_text='Access level for home-specific dashboards', max_length=20),
        ),
    ]
