# Generated by Django 4.2.27 on 2026-01-25 10:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0059_alter_user_shift_preference'),
        ('quality_audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityImprovementAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qia_reference', models.CharField(editable=False, help_text='Auto-generated: QIA-2026-001', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Brief description of the improvement action', max_length=200)),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Corrective Action - Fix identified problem'), ('PREVENTIVE', 'Preventive Action - Prevent potential problem')], default='CORRECTIVE', max_length=20)),
                ('source_type', models.CharField(choices=[('INCIDENT', 'Incident Investigation'), ('AUDIT', 'Audit Finding'), ('RISK', 'Risk Assessment'), ('COMPLAINT', 'Complaint Resolution'), ('TREND', 'Trend Analysis'), ('PDSA', 'PDSA Project'), ('INSPECTION', 'Care Inspectorate Inspection')], help_text='What triggered this QIA?', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Reference number of source (e.g., INC-2026-001)', max_length=100)),
                ('problem_description', models.TextField(help_text='What is the problem or potential problem?')),
                ('root_cause', models.TextField(blank=True, help_text='Root cause analysis findings (from RCA if available)')),
                ('impact_analysis', models.TextField(blank=True, help_text='Who/what is affected? What are the consequences?')),
                ('action_plan', models.TextField(help_text='Detailed steps to address the issue')),
                ('success_criteria', models.TextField(help_text='How will we know the action was successful?')),
                ('resources_needed', models.TextField(blank=True, help_text='Budget, staff time, equipment, training required')),
                ('identified_date', models.DateField(default=django.utils.timezone.now, help_text='When was this QIA identified?')),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(help_text='When should this QIA be completed?')),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified - Not Yet Planned'), ('PLANNED', 'Planned - Action Plan Created'), ('APPROVED', 'Approved - Ready for Implementation'), ('IMPLEMENTING', 'Implementation in Progress'), ('IMPLEMENTED', 'Implemented - Awaiting Verification'), ('VERIFIED', 'Verified - Effectiveness Confirmed'), ('CLOSED', 'Closed - Action Complete'), ('REJECTED', 'Rejected - Not Required')], default='IDENTIFIED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low - Monitor'), ('MEDIUM', 'Medium - Address within 90 days'), ('HIGH', 'High - Address within 30 days'), ('CRITICAL', 'Critical - Immediate action required')], default='MEDIUM', max_length=20)),
                ('percent_complete', models.IntegerField(default=0, help_text='Overall completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_notes', models.TextField(blank=True, help_text='Implementation progress updates')),
                ('verification_method', models.TextField(blank=True, help_text='How will effectiveness be verified? (audit, measurement, observation)')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('effectiveness_rating', models.IntegerField(blank=True, help_text='1=Not Effective, 5=Very Effective', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('effectiveness_notes', models.TextField(blank=True, help_text='Evidence of effectiveness')),
                ('regulatory_requirement', models.CharField(blank=True, help_text='Care Inspectorate QI, HSCS theme, legislation reference', max_length=200)),
                ('requires_ci_notification', models.BooleanField(default=False, help_text='Must Care Inspectorate be notified?')),
                ('ci_notification_date', models.DateField(blank=True, help_text='Date Care Inspectorate was notified', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qia_actions', to='scheduling.carehome')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_qias', to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(help_text='Person accountable for implementing this QIA', on_delete=django.db.models.deletion.PROTECT, related_name='responsible_qias', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, help_text='Additional team members involved', related_name='qia_team_memberships', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_qias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality Improvement Action (QIA)',
                'verbose_name_plural': 'Quality Improvement Actions (QIAs)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QIAUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_change', models.CharField(blank=True, help_text='Status change (if any)', max_length=100)),
                ('percent_complete', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('update_notes', models.TextField(help_text='Progress update, barriers encountered, adjustments made')),
                ('evidence_description', models.CharField(blank=True, help_text='Description of evidence (photos, documents, data)', max_length=200)),
                ('qia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='quality_audits.qualityimprovementaction')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qia_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QIA Progress Update',
                'verbose_name_plural': 'QIA Progress Updates',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='QIAReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('is_effective', models.BooleanField(help_text='Did this QIA achieve its objectives?')),
                ('effectiveness_rating', models.IntegerField(help_text='1=Not Effective, 5=Very Effective', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('effectiveness_evidence', models.TextField(help_text='Data, observations, measurements supporting rating')),
                ('is_sustainable', models.BooleanField(help_text='Will improvements be maintained long-term?')),
                ('sustainability_plan', models.TextField(blank=True, help_text='How will improvements be embedded in practice?')),
                ('follow_up_required', models.BooleanField(default=False, help_text='Is additional action needed?')),
                ('follow_up_actions', models.TextField(blank=True, help_text='What additional actions are needed?')),
                ('lessons_learned', models.TextField(help_text="What worked well? What didn't? Key insights?")),
                ('recommend_spread', models.BooleanField(default=False, help_text='Should this QIA be replicated in other units/homes?')),
                ('spread_notes', models.TextField(blank=True, help_text='How could this be spread to other areas?')),
                ('approved_for_closure', models.BooleanField(default=False, help_text='Can this QIA be closed?')),
                ('closure_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quality_audits.qualityimprovementaction')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_qia_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QIA Effectiveness Review',
                'verbose_name_plural': 'QIA Effectiveness Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.AddIndex(
            model_name='qualityimprovementaction',
            index=models.Index(fields=['qia_reference'], name='quality_aud_qia_ref_52ba77_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityimprovementaction',
            index=models.Index(fields=['care_home', 'status'], name='quality_aud_care_ho_4d8e20_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityimprovementaction',
            index=models.Index(fields=['source_type', 'source_reference'], name='quality_aud_source__2f9b7e_idx'),
        ),
    ]
